Repository arduino/library-registry, pull requests merged in 2021-09, with the labels that each got.

#445 More clearly communicate that new PR is not required to resolve submission problem
  .github/workflows/manage-prs.yml
Labels: other

#446 Added NanoBLEFlashPrefs library
  repositories.txt
Labels: submission

#447 Add PrintCppVersion
  repositories.txt
Labels: submission

#448 SparkFun_AS6212_Qwiic_Arduino_Library
  repositories.txt
Labels: submission

#211 Update URL of "UbxGps"
  registry.txt
Labels: modification, URL change

#443 Update URL and name of "M5_FPC1020A"
  registry.txt
Labels: rename, URL change

#430 Remove "BME33M251"
  registry.txt
Labels: removal

#449 Update repositories.txt
  repositories.txt
Labels: submission

#450 Update repositories.txt
  repositories.txt
Labels: submission

#452 Update repositories.txt
  repositories.txt
Labels: submission

#453 Update repositories.txt
  repositories.txt
Labels: submission

#454 Add Z80 library for the Arduino Mega
  repositories.txt
Labels: submission

#455 Update repositories.txt
  repositories.txt
Labels: submission

#456 Add FastLEDManager
  repositories.txt
Labels: submission

#457 Update repositories.txt
  repositories.txt
Labels: submission

#458 Update repositories.txt
  repositories.txt
Labels: submission

#460 Update repositories.txt
  repositories.txt
Labels: submission

#461 Added Seeed_Arduino_Mic
  repositories.txt
Labels: submission

#462 Update repositories.txt
  repositories.txt
Labels: submission

#463 Added the LithiumPowered Library
  repositories.txt
Labels: submission

#464 Update repositories.txt
  repositories.txt
Labels: submission

#465 Add LittleFS_Portenta_H7 Library
  repositories.txt
Labels: submission

#468 SparkFun_FS3000_Arduino_Library
  repositories.txt
Labels: submission

#470 Add more RAKwireless libraries
  repositories.txt
Labels: submission

#472 Add SHT3x library
  repositories.txt
Labels: submission

#473 Update repositories.txt
  repositories.txt
Labels: submission

#471 URL change: dustpancake -> fjebaker
  repositories.txt
Labels: modification

#475 Handle submission merge failures caused by outdated fork
  .github/workflows/manage-prs.yml
Labels: other

#476 Add PikaBot library
  repositories.txt
Labels: submission

#477 Add Open-Acidification/TankController
  repositories.txt
Labels: submission

#478 Add WiFiManager_Portenta_H7_Lite Library
  repositories.txt
Labels: submission

#480 Add Ethernet_Manager_Portenta_H7 Library
  repositories.txt
Labels: submission

#481 Please add new library
  repositories.txt
Labels: submission

#482 Update repositories.txt
  repositories.txt
Labels: submission

#484 Update repositories.txt
  repositories.txt
Labels: submission

#485 Adding Adafruit IS31FL3741.
  repositories.txt
Labels: submission

#486 Add Portenta_H7_TimerInterrupt Library
  repositories.txt
Labels: submission

#487 Added MD_Stepper to the list
  repositories.txt
Labels: submission

#488 Update repositories.txt
  repositories.txt
Labels: submission

#489 Update repositories.txt
  repositories.txt
Labels: submission

#490 Update repositories.txt
  repositories.txt
Labels: status: waiting for information

#492 added newdigate/teensy-audio-launch-ctrl
  repositories.txt
Labels: submission

#493 Add Portenta_H7_ISR_Servo Library
  repositories.txt
Labels: submission

#494 Add Seeed Arduino Sketchbook
  repositories.txt
Labels: submission

#495 Update repositories.txt
  repositories.txt
Labels: submission

#496 Update ref for KerbalSimpit
  repositories.txt
Labels: modification

#498 Update repositories.txt
  repositories.txt
Labels: submission

#499 Update repositories.txt
  repositories.txt
Labels: submission

#502 Update repositories.txt
  repositories.txt
Labels: submission

#503 Update repositories.txt
  repositories.txt
Labels: submission

#504 Add ESP32_PWM Library
  repositories.txt
Labels: submission

#505 add TAMC_FT62X6
  repositories.txt
Labels: submission

#506 Update repositories.txt
  repositories.txt
Labels: submission

#507 Add ESP8266_PWM Library
  repositories.txt
Labels: submission

#509 Add Portenta_H7_PWM Library
  repositories.txt
Labels: submission

#508 Change link to github
  repositories.txt
Labels: modification

#512 Update repositories.txt
  repositories.txt
Labels: submission

#519 Update repositories.txt
  repositories.txt
Labels: submission

#520 Update repositories.txt - Add TinyDatabase
  repositories.txt
Labels: submission

#521 Add libasm cross assemble/disassemble library
  repositories.txt
Labels: submission

#522 Add SparkFun_AVR_ISP_Programming_Library
  repositories.txt
Labels: submission

#523 Update repositories.txt
  repositories.txt
Labels: submission

#524 Update repositories.txt
  repositories.txt
Labels: submission

#525 Add Portenta_H7_Slow_PWM Library
  repositories.txt
Labels: submission

#142 Update BBQ10Keyboard URL
  registry.txt
Labels: modification, URL change

#221 Remove "EC_Salinity", "pH Probe Interface", "ISE Probe Interface"
  registry.txt
Labels: removal

#252 Remove "RV8803 For MegaTinyCore" and "tiny-mega-i2c"
  registry.txt
Labels: removal

#335 Remove "UULM-MCP23008"
  registry.txt
Labels: removal

#491 Remove "DFRobot GDL"
  registry.txt
Labels: removal

#342 Change Library Name
  registry.txt
Labels: rename

#347 Update name of "I2CHelper"
  registry.txt
Labels: rename

#423 Update name of "DailyStruggleButton"
  registry.txt
Labels: rename

#474 Update URL of "MQ7Sensor"
  registry.txt
Labels: URL change

#510 Update URL of "TAMC_FT62X6"
  registry.txt
Labels: URL change

#497 Update URL and name of "KerbalSimpit"
  registry.txt
Labels: URL change, rename

#528 Update repositories.txt
  repositories.txt
Labels: submission

#529 Add RP2040_PWM Library
  repositories.txt
Labels: submission

#530 Add MBED_RP2040_Slow_PWM Library
  repositories.txt
Labels: submission

#532 Add RP2040_Slow_PWM Library
  repositories.txt
Labels: submission

#531 STAMP-PICO
  repositories.txt
Labels: submission

#535 Update repositories.txt
  repositories.txt
Labels: submission

#536 Add nRF52_MBED_Slow_PWM Library
  repositories.txt
Labels: submission

#537 Add nRF52_Slow_PWM Library
  repositories.txt
Labels: submission

#538 Adding library ADS1115-Driver
  repositories.txt
Labels: submission

#539 Add DFRobot library
  repositories.txt
Labels: submission

#540 Add AVR_Slow_PWM Library
  repositories.txt
Labels: submission

#542 Update repositories.txt
  repositories.txt
Labels: submission

#543 Add megaAVR_Slow_PWM Library
  repositories.txt
Labels: submission

#544 Add SHT2x library
  repositories.txt
Labels: submission

#546 Add Teensy_Slow_PWM Library
  repositories.txt
Labels: submission

#548 Add SAMDUE_Slow_PWM Library
  repositories.txt
Labels: submission

#549 Add DFRobot_RGBLCD1602 library
  repositories.txt
Labels: submission

#541 Add CI workflow to synchronize with shared repository labels
  .github/label-configuration-files/labels.yml
  .github/workflows/manage-prs.yml
  .github/workflows/sync-labels.yml
Labels: other

#550 add analogUVsensor library
  repositories.txt
Labels: topic: submission

#551 Update repositories.txt
  repositories.txt
Labels: topic: submission

#552 Add STM32_Slow_PWM Library
  repositories.txt
Labels: topic: submission

#553 Update repositories.txt to add MeshGnome
  repositories.txt
Labels: topic: submission
