Repository arduino/library-registry, pull requests merged in 2021-08, with the labels that each got.

#307 Update repositories.txt
  repositories.txt
Labels: submission

#308 Update repositories.txt
  repositories.txt
Labels: submission

#309 Add Azure RTOS library
  repositories.txt
Labels: submission

#310 XMC_Servo again
  repositories.txt
Labels: submission

#311 Update repositories.txt
  repositories.txt
Labels: submission

#312 Update repositories.txt
  repositories.txt
Labels: submission

#317 added SparkFun_Tsunami_Qwiic_Arduino_Library
  repositories.txt
Labels: submission

#319 Add new ESP32_S2_ISR_Servo library
  repositories.txt
Labels: submission

#320 Add ESP32_C3_ISR_Servo library
  repositories.txt
Labels: submission

#322 Update repositories.txt
  repositories.txt
Labels: submission

#323 Adding AVR controller repo for examples and wrapper to use the shield
  repositories.txt
Labels: submission

#324 Update repositories.txt
  repositories.txt
Labels: submission

#327 Update repositories.txt
  repositories.txt
Labels: submission

#329 Update repositories.txt
  repositories.txt
Labels: submission

#333 Update repositories.txt with SimpleFusion Library
  repositories.txt
Labels: submission

#334 Update repositories.txt - remove mcp23008 library
  repositories.txt
Labels: removal

#336 Update repositories.txt with WMM_Tinier library
  repositories.txt
Labels: submission

#337 Add FlashStorage_RTL8720 library
  repositories.txt
Labels: submission

#339 Update repositories.txt
  repositories.txt
Labels: submission

#340 Update repositories.txt
  repositories.txt
Labels: submission

#344 Add RTL8720_TimerInterrupt Library
  repositories.txt
Labels: submission

#345 Update repositories.txt
  repositories.txt
Labels: submission

#348 Add SwarmTile to Arduino Library Manager
  repositories.txt
Labels: submission

#349 RAKWireless libraries for RAK12010, RAK13005, RAK12004, RAK12008, RAK12009 WisBlock modules
  repositories.txt
Labels: submission

#350 Add RTL8720_RTC Library
  repositories.txt
Labels: submission

#351 Update repositories.txt
  repositories.txt
Labels: submission

#352 Sync "Check License" CI workflow with template
  .github/workflows/check-license.yml
Labels: other

#354 Use Go 1.16 for registry validator
  .github/workflows/assets/validate-registry/go.mod
  .github/workflows/assets/validate-registry/go.sum
  .github/workflows/check-go-task.yml
  .github/workflows/check-registry.yml
  .github/workflows/test-go-integration-task.yml
  Taskfile.yml
Labels: type: enhancement, topic: infrastructure

#355 Added JPEGENG library
  repositories.txt
Labels: submission

#356 Update repositories.txt
  repositories.txt
Labels: submission

#359 Add AGS20MA
  repositories.txt
Labels: submission

#357 Sync CI assets to their "templates"
  .editorconfig
  .github/workflows/assets/validate-registry/tests/__init__.py
  .github/workflows/assets/validate-registry/tests/test_all.py
  .github/workflows/check-yaml-task.yml
  .github/workflows/test-go-integration-task.yml
Labels: type: enhancement, topic: infrastructure

#358 Make "Check Go" workflow module path support extendable
  .github/workflows/check-go-task.yml
  Taskfile.yml
Labels: type: enhancement, topic: infrastructure

#360 Add ESP32_New_TimerInterrupt Library
  repositories.txt
Labels: submission

#361 Add ESP32_New_ISR_Servo Library
  repositories.txt
Labels: submission

#362 Update repositories.txt
  repositories.txt
Labels: submission

#364 Update repositories.txt
  repositories.txt
Labels: submission

#365 Add FlashStorage_STM32F1 Library
  repositories.txt
Labels: submission

#366 Update repositories.txt
  repositories.txt
Labels: submission

#369 TinyGPSPlus
  repositories.txt
Labels: submission

#370 Add AceSegment, AceSegmentWriter, AceSPI, AceTMI, AceWire
  repositories.txt
Labels: submission

#371 M5_BMM150
  repositories.txt
Labels: submission

#372 M5_ADS1115
  repositories.txt
Labels: submission

#375 Add ArduPID
  repositories.txt
Labels: submission

#377 M5_AD9833
  repositories.txt
Labels: submission

#378 PCA9554
  repositories.txt
Labels: submission

#380 Update repositories.txt
  repositories.txt
Labels: submission

#376 Update repositories.txt
  repositories.txt
Labels: submission

#381 Add STM32_ISR_Servo Library
  repositories.txt
Labels: submission

#382 Update repositories.txt
  repositories.txt
Labels: submission

#383 Update repositories.txt
  repositories.txt
Labels: submission

#384 Add RP2040_ISR_Servo Library
  repositories.txt
Labels: submission

#385 Update repositories.txt
  repositories.txt
Labels: submission

#386 Add SAMD_ISR_Servo Library
  repositories.txt
Labels: submission

#388 Add NRF52_ISR_Servo Library
  repositories.txt
Labels: submission

#390 add MTP40C CO2 and air pressure sensor
  repositories.txt
Labels: submission

#391 Added Simple5641AS library
  repositories.txt
Labels: submission

#392 Update repositories.txt
  repositories.txt
Labels: submission

#393 Add AceSorting
  repositories.txt
Labels: submission

#398 Update repositories.txt
  repositories.txt
Labels: submission

#401 Update repositories.txt
  repositories.txt
Labels: submission

#402 Added custom libraries
  repositories.txt
Labels: submission

#403 Update repositories.txt
  repositories.txt
Labels: submission

#424 Update repositories.txt
  repositories.txt
Labels: submission

#425 Add experimental DAC8550 library
  repositories.txt
Labels: submission

#426 Add FS_Nano33BLE Library
  repositories.txt
Labels: submission

#427 Update repositories.txt
  repositories.txt
Labels: removal

#431 Add Arduino_APA102
  repositories.txt
Labels: submission

#432 Update repositories.txt
  repositories.txt
Labels: submission

#433 Add 107-Arduino-BoostUnits to Library Index.
  repositories.txt
Labels: submission

#434 Add AT42QT
  repositories.txt
Labels: submission

#435 Add 107-Arduino-Sensor to Library Index.
  repositories.txt
Labels: submission

#441 Change the name of the library
  repositories.txt
Labels: modification

#444 Update repositories.txt
  repositories.txt
Labels: submission
