Repository arduino/library-registry, pull requests merged in 2021-07, with the labels that each got.

#145 Add TCS34725AutoGain library
  repositories.txt
Labels: submission

#146 Added Arduino_PortentaBreakout
  repositories.txt
Labels: submission

#148 add MaquinitasParameters
  repositories.txt
Labels: submission

#149 Submitting new Library Sidereal Planets to repository.txt file
  repositories.txt
Labels: submission

#152 Update repositories.txt
  repositories.txt
Labels: submission

#153 A C/C++ library to use DS1302 RTC chip
  repositories.txt
Labels: submission

#154 Add libraries for new RAKwireless modules
  repositories.txt
Labels: submission

#155 Update repositories.txt
  repositories.txt
Labels: submission

#157 add library
  repositories.txt
Labels: submission

#151 change library name
  repositories.txt
Labels: modification

#160 Add WebServer_WT32_ETH01 library
  repositories.txt
Labels: submission

#161 New library: FlashStringTable
  repositories.txt
Labels: submission

#162 Add the TSC2004 library
  repositories.txt
Labels: submission

#163 Add radarIQ library
  repositories.txt
Labels: submission

#164 Added Infineon PAS CO2 Arduino Library
  repositories.txt
Labels: submission

#165 Update repositories.txt
  repositories.txt
Labels: submission

#166 Update repositories.txt
  repositories.txt
Labels: submission

#167 add SiguesAhi to libraries
  repositories.txt
Labels: submission

#170 miathedev/KomootBLEConnect
  repositories.txt
Labels: submission

#171 add MaquinitasRitmos
  repositories.txt
Labels: submission

#172 Add BM64 Library
  repositories.txt
Labels: submission

#175 Add Marlin U8glib-HAL. Modified U8glib for Marlin 2.0
  repositories.txt
Labels: submission

#176 Add ZMPT101B library
  repositories.txt
Labels: submission

#177 Add AsyncUDP_WT32_ETH01
  repositories.txt
Labels: submission

#178 Update repositories.txt
  repositories.txt
Labels: submission

#181 Add library Arduino-SchmittTrigger
  repositories.txt
Labels: submission

#184 Update repositories.txt
  repositories.txt
Labels: submission

#185 add flinduino-sensorkit
  repositories.txt
Labels: submission

#186 Remove instructions for library re-release
  FAQ.md
Labels: other

#187 Remove non-existent step from submission instructions
  README.md
Labels: other

#188 Adding youtube-livestream-arduino
  repositories.txt
Labels: submission

#189 Approve submission PRs before auto-merging
  .github/workflows/manage-prs.yml
Labels: other

#190 Update repositories.txt
  repositories.txt
Labels: submission

#191 Make submission instructions comprehensive
  README.md
Labels: other

#182 Change library name
  registry.txt
Labels: modification

#158 Update URL and change name of "MaquinitasParameters"
  registry.txt
Labels: modification

#193 Add WiFiWebServer_RTL8720 library
  repositories.txt
Labels: submission

#192 Add CI workflow to check general file formatting in `production` branch
  .ecrc
  .editorconfig
  .github/workflows/check-general-formatting-task.yml
  Taskfile.yml
Labels: topic: infrastructure, type: enhancement

#194 Configure Dependabot for updates to production branch workflows
  .github/dependabot.yml
Labels: other

#196 Update repositories.txt
  repositories.txt
Labels: submission

#198 Add prefix to error messages in bot comments
  .github/workflows/manage-prs.yml
Labels: other

#201 adding new library TeensyAudioFlashLoader
  repositories.txt
Labels: submission

#200 Configure Dependabot for updates to `production` branch deps
  .github/dependabot.yml
Labels: other

#203 add TeensyAudioSampler
  repositories.txt
Labels: submission

#204 Update repositories.txt
  repositories.txt
Labels: submission

#205 Update repositories.txt
  repositories.txt
Labels: submission

#206 Add AsyncWebServer_WT32_ETH01 to Library Manager
  repositories.txt
Labels: submission

#207 Update repository URL for UbxGps library
  repositories.txt
Labels: modification

#209 Update repositories.txt
  repositories.txt
Labels: submission

#210 Update repositories.txt
  repositories.txt
Labels: submission

#213 Update repositories.txt
  repositories.txt
Labels: submission

#214 Add lbussy/mDNSResolver
  repositories.txt
Labels: submission

#215 Add WireGuard-ESP32 library
  repositories.txt
Labels: submission

#219 Update repositories.txt
  repositories.txt
Labels: submission

#220 Add submission # 217
  registry.txt
Labels: submission

#217 Add Microfire Mod-EC, Mod-pH and Mod-ORP libraries
  repositories.txt
Labels: modification

#202 Add data file to "Check Registry Data File" workflow's paths filter
  .github/workflows/check-registry.yml
Labels: topic: infrastructure, type: bug

#212 Only fail "Manage PRs" workflow on unexpected error
  .github/workflows/manage-prs.yml
Labels: other

#224 Remove workflow runs link from comment trigger reply
  .github/workflows/manage-prs.yml
Labels: other

#225 Added Tweakly Library
  repositories.txt
Labels: submission

#226 Update repositories.txt
  repositories.txt
Labels: submission

#227 Update repositories.txt
  repositories.txt
Labels: submission

#229 Update repositories.txt
  repositories.txt
Labels: submission

#237 Update repositories.txt
  repositories.txt
Labels: submission

#242 Bump submission parser version to 1.0.1
  .github/workflows/manage-prs.yml
Labels: other

#243 Update repositories.txt
  repositories.txt
Labels: submission

#245 Added RV8803 support for new ATTINYs
  repositories.txt
Labels: submission

#231 Avoid linkification of bot user name in comment
  .github/workflows/manage-prs.yml
Labels: other

#235 Add duplicate name check to registry data file validator
  .github/workflows/assets/validate-registry/main.go
  .github/workflows/assets/validate-registry/tests/test_all.py
  .github/workflows/assets/validate-registry/tests/testdata/duplicate-name.txt
  registry.txt
Labels: topic: infrastructure, type: bug, type: enhancement

#249 Update repositories.txt
  repositories.txt
Labels: submission

#251 Update repositories.txt
  repositories.txt
Labels: removal

#254 Update repositories.txt
  repositories.txt
Labels: submission

#255 Update repositories.txt
  repositories.txt
Labels: submission

#256 Update repositories.txt
  repositories.txt
Labels: submission

#257 Update repositories.txt
  repositories.txt
Labels: submission

#260 Update repositories.txt
  repositories.txt
Labels: submission

#262 add M5STACK 4RELAY ENV-III ATOM-DTU-LoRaWAN/NBIoT lib
  repositories.txt
Labels: submission

#263 Update repositories.txt
  repositories.txt
Labels: modification

#264 Add submission # 263
  registry.txt
Labels: submission

#265 Add EmbUI framework
  repositories.txt
Labels: submission

#266 Update repositories.txt
  repositories.txt
Labels: submission

#267 Add Battery1865Stats lib
  repositories.txt
Labels: submission

#269 Update repositories.txt
  repositories.txt
Labels: submission

#270 Add PololuOLED library
  repositories.txt
Labels: submission

#271 Update repositories.txt
  repositories.txt
Labels: submission

#274 Update repositories.txt
  repositories.txt
Labels: submission

#276 Update repositories.txt
  repositories.txt
Labels: submission

#277 new entry: add Bluepad32 library to registry
  repositories.txt
Labels: submission

#268 Add library type check to registry data file validator
  .github/workflows/assets/validate-registry/main.go
  .github/workflows/assets/validate-registry/tests/test_all.py
  .github/workflows/assets/validate-registry/tests/testdata/invalid-type.txt
  .github/workflows/assets/validate-registry/tests/testdata/no-type.txt
Labels: topic: infrastructure, type: enhancement

#281 Handle general problems with pull request
  .github/workflows/manage-prs.yml
Labels: other

#282 Bump library registry submission parser version used by "Manage PRs" workflow
  .github/workflows/manage-prs.yml
Labels: other

#278 Remove "UltraDistSensor"
  repositories.txt
Labels: removal

#283 Update repositories.txt
  repositories.txt
Labels: submission

#287 add m5stack grbl module and update env unit lib
  repositories.txt
Labels: modification

#288 Add submission # 287
  registry.txt
Labels: submission

#289 Update name and URL of "UNIT_ENV"
  registry.txt
Labels: URL change, modification

#290 Update repositories.txt
  repositories.txt
Labels: submission

#291 Add hideakitai/ESP32SPISlave
  repositories.txt
Labels: submission

#292 Update repositories.txt
  repositories.txt
Labels: submission

#295 Update repositories.txt
  repositories.txt
Labels: submission

#296 Update repositories.txt
  repositories.txt
Labels: submission

#297 Update repositories.txt
  repositories.txt
Labels: submission

#298 Update repositories.txt
  repositories.txt
Labels: submission

#299 Update repositories.txt
  repositories.txt
Labels: submission

#300 Add ESP32_C3_TimerInterrupt Library
  repositories.txt
Labels: submission

#302 Add MotorController
  repositories.txt
Labels: submission

#304 Update repositories.txt
  repositories.txt
Labels: submission

#303 Require that PR head matches that of diff when merging
  .github/workflows/manage-prs.yml
Labels: other

#293 Update URL for "RTCMemory"
  repositories.txt
Labels: modification

#130 Update URL for "RTCMemory"
  registry.txt
Labels: modification

#305 Update repositories.txt
  repositories.txt
Labels: submission

#306 adding https://github.com/noah1510/unit-system to library list
  repositories.txt
Labels: submission
