Repository arduino/library-registry, pull requests merged in 2021-11, with the labels that each got.

#626 Update repositories.txt
  repositories.txt
Labels: topic: submission

#629 Update repositories.txt
  repositories.txt
Labels: topic: submission

#628 Update name of "CIE1931"
  registry.txt
Labels: topic: rename

#631 Added https://github.com/ArminJo/AvrTracing
  repositories.txt
Labels: topic: submission

#632 M5_BM8563
  repositories.txt
Labels: topic: submission

#633 Update repositories.txt
  repositories.txt
Labels: topic: submission

#634 Update repositories.txt
  repositories.txt
Labels: topic: submission

#635 Update repositories.txt
  repositories.txt
Labels: topic: submission

#636 Update repositories.txt
  repositories.txt
Labels: topic: submission

#637 Update repositories.txt
  repositories.txt
Labels: topic: submission

#640 Update repositories.txt
  repositories.txt
Labels: topic: submission

#642 Update repositories.txt
  repositories.txt
Labels: topic: submission

#645 Add new RAKwireless libraries
  repositories.txt
Labels: topic: submission

#644 Update repositories.txt
  repositories.txt
Labels: topic: submission

#647 Add incbin library
  repositories.txt
Labels: topic: submission

#648 Update repositories.txt
  repositories.txt
Labels: topic: submission

#650 Update repositories.txt
  repositories.txt
Labels: topic: submission

#651 Update repositories.txt
  repositories.txt
Labels: topic: submission

#653 add DFRobot_MLX90614 library
  repositories.txt
Labels: topic: submission

#654 add m5stack/M5Unified library
  repositories.txt
Labels: topic: submission

#655 Update repositories.txt
  repositories.txt
Labels: topic: submission

#657 Update repositories.txt
  repositories.txt
Labels: topic: submission

#658 Added the awesome SoftI2CMaster library
  repositories.txt
Labels: topic: submission

#659 Remove "SusiOverI2c"
  repositories.txt
Labels: topic: removal

#662 Update repositories.txt
  repositories.txt
Labels: topic: modification, topic: URL change

#666 Update repositories.txt
  repositories.txt
Labels: topic: submission

#667 Update repositories.txt
  repositories.txt
Labels: topic: submission

#668 Add asukiaaa/arduino-A89306
  repositories.txt
Labels: topic: submission

#669 add https://github.com/Jueff/SoftwareSerialTX
  repositories.txt
Labels: topic: submission

#671 Update repositories.txt
  repositories.txt
Labels: topic: submission

#670 Update repositories.txt
  repositories.txt
Labels: topic: submission

#673 Update repositories.txt
  repositories.txt
Labels: topic: submission

#675 Add https://github.com/0neblock/Arduino_SNMP
  repositories.txt
Labels: topic: submission

#676 Add `Indicator` library
  repositories.txt
Labels: topic: submission

#677 Update repositories.txt
  repositories.txt
Labels: topic: submission

#678 Update repositories.txt
  repositories.txt
Labels: topic: submission

#679 Update repositories.txt
  repositories.txt
Labels: topic: submission

#680 Update repositories.txt
  repositories.txt
Labels: topic: submission

#681 Add FTTech_Swarm
  repositories.txt
Labels: topic: submission

#682 Update repositories.txt
  repositories.txt
Labels: topic: submission

#683 Add Artron_DS1338 lib
  repositories.txt
Labels: topic: submission

#687 add MatrixLaserSensor
  repositories.txt
Labels: topic: submission

#688 add glpi_esp8266
  repositories.txt
Labels: topic: submission

#689 Update repositories.txt
  repositories.txt
Labels: topic: submission

#690 Update repositories.txt
  repositories.txt
Labels: topic: submission

#691 Update repositories.txt - Add "List" Library
  repositories.txt
Labels: topic: submission

#692 Update repositories.txt
  repositories.txt
Labels: topic: submission

#693 Update repositories.txt
  repositories.txt
Labels: topic: submission

#694 add tinySHT2X
  repositories.txt
Labels: topic: submission

#695 Add AIS 4G Board library
  repositories.txt
Labels: topic: submission

#697 ESP32 Library to interact with OVH API
  repositories.txt
Labels: topic: submission

#701 Removing libraries
  repositories.txt
Labels: topic: removal

#705 Update repositories.txt
  repositories.txt
Labels: topic: submission

#706 Add TimedState library
  repositories.txt
Labels: topic: submission

#707 Adding SmartCar2 library
  repositories.txt
Labels: topic: submission

#714 Update repositories.txt
  repositories.txt
Labels: topic: submission

#547 Add RREFont
  repositories.txt
Labels: topic: submission

#715 added porcupine-arduino-en package from Picovoice
  repositories.txt
Labels: topic: submission

#716 Publish IoTeX-blockchain-client library
  repositories.txt
Labels: topic: submission

#717 added picovoice and porcupine packages
  repositories.txt
Labels: topic: submission

#718 Configure manager workflow to prevent parallel runs for one PR
  .github/workflows/manage-prs.yml
Labels: type: enhancement, topic: infrastructure, topic: other

#721 Update repositories.txt
  repositories.txt
Labels: topic: submission

#719 Update repositories.txt
  repositories.txt
Labels: topic: submission

#722 Update SimpleCLI library URL
  repositories.txt
Labels: topic: modification

#724 Update repositories.txt
  repositories.txt
Labels: topic: submission

#726 Update repositories.txt
  repositories.txt
Labels: topic: submission

#727 add pressure conversion library
  repositories.txt
Labels: topic: submission

#728 Add RAK12035 Soil Moisture Sensor library
  repositories.txt
Labels: topic: submission

#730 add float16
  repositories.txt
Labels: topic: submission

#736 Update repositories.txt
  repositories.txt
Labels: topic: submission

#737 Update repositories.txt
  repositories.txt
Labels: topic: submission

#739 Update repositories.txt
  repositories.txt
Labels: topic: submission

#740 Update repositories.txt
  repositories.txt
Labels: topic: submission

#742 added sdpsensor-esp-arduino repo
  repositories.txt
Labels: topic: submission

#743 Add PioSPI library to the repositories
  repositories.txt
Labels: topic: submission

#744 Update repositories.txt
  repositories.txt
Labels: topic: submission

#746 Update repositories.txt
  repositories.txt
Labels: topic: submission
