Repository arduino/library-registry, pull requests merged in 2021-12, with the labels that each got.

#747 Update repositories.txt
  repositories.txt
Labels: topic: submission

#749 Update repositories.txt
  repositories.txt
Labels: topic: submission

#750 Update repositories.txt
  repositories.txt
Labels: topic: submission

#751 Add two new libraries
  repositories.txt
Labels: topic: submission

#752 Update repositories.txt
  repositories.txt
Labels: topic: submission

#753 Update repositories.txt
  repositories.txt
Labels: topic: submission

#754 add palindrome
  repositories.txt
Labels: topic: submission

#755 Add SolarCalculator
  repositories.txt
Labels: topic: submission

#756 Update repositories.txt
  repositories.txt
Labels: topic: submission

#757 add map2colour
  repositories.txt
Labels: topic: submission

#758 Add ATCommands
  repositories.txt
Labels: topic: submission

#759 Update repositories.txt
  repositories.txt
Labels: topic: submission

#760 Update repositories.txt
  repositories.txt
Labels: topic: submission

#761 Update repositories.txt
  repositories.txt
Labels: topic: submission

#762 Update repositories.txt
  repositories.txt
Labels: topic: submission

#764 Update repositories.txt
  repositories.txt
Labels: topic: submission

#765 Update repositories.txt
  repositories.txt
Labels: topic: submission

#766 Update repositories.txt
  repositories.txt
Labels: topic: submission

#767 Added simple collections library in the davetcc repository
  repositories.txt
Labels: topic: submission

#768 Add official Microsoft Azure SDK for C Arduino library.
  repositories.txt
Labels: topic: submission

#769 Added MCUOS library to list
  repositories.txt
Labels: topic: submission

#771 Update repositories.txt
  repositories.txt
Labels: topic: submission

#773 Added library for 24LC64F EEPROM chip
  repositories.txt
Labels: topic: submission

#774 Update repositories.txt
  repositories.txt
Labels: topic: submission

#770 Avoid manager workflow run cancelation by incidental events
  .github/workflows/manage-prs.yml
Labels: topic: other

#776 Added uc-OS3 Arduino Due Library
  repositories.txt
Labels: topic: submission

#777 Update repositories.txt
  repositories.txt
Labels: topic: submission

#778 Add SparkFun Qwiic Fan Arduino Library
  repositories.txt
Labels: topic: submission

#784 Update repositories.txt
  repositories.txt
Labels: topic: submission

#785 Add QNEthernet library for Teensy 4.1
  repositories.txt
Labels: topic: submission

#788 Add two new module libraries for RAKwireless WisBlock modules
  repositories.txt
Labels: topic: submission

#789 Initial release of Robbus Kidsy V1.0.0 library
  repositories.txt
Labels: topic: submission

#786 Update Viralink-Arduino-SDK
  repositories.txt
Labels: topic: modification

#794 Update repositories.txt
  repositories.txt
Labels: topic: submission

#795 Add TMC2209
  repositories.txt
Labels: topic: submission

#796 Add SparkFun RHT03 library
  repositories.txt
Labels: topic: submission

#797 Update repositories.txt
  repositories.txt
Labels: topic: submission

#799 add device controller library to repositories.txt
  repositories.txt
Labels: topic: submission

#802 Add soracom-labs/soracom-arc-esp32-arduino
  repositories.txt
Labels: topic: submission

#803 Update repositories.txt
  repositories.txt
Labels: topic: submission

#804 Update repositories.txt
  repositories.txt
Labels: topic: submission

#806 add m5stack/UNIT_KMeter.
  repositories.txt
Labels: topic: submission

#801 Update URL of "Indicator"
  repositories.txt
Labels: topic: modification

#660 Remove "SusiOverI2c"
  registry.txt
Labels: topic: removal

#741 Rename "TwiLiquidCrystal by Arnakazim"
  registry.txt
Labels: topic: rename

#734 Rename "SimpleFTPServer"
  registry.txt
Labels: topic: rename

#735 Rename "controlVoltage"
  registry.txt
Labels: topic: rename

#710 Rename "IoTGuru"
  registry.txt
Labels: topic: rename

#704 Remove "xxtea-iot-crypt"
  registry.txt
Labels: topic: removal

#703 Remove "rBase64"
  registry.txt
Labels: topic: removal

#702 Remove "PString-Arduino-lib"
  registry.txt
Labels: topic: removal

#663 Rename "RTTStream"
  registry.txt
Labels: topic: URL change, topic: rename

#790 Update URL and name of "ViraLink-MQTT-Client"
  registry.txt
Labels: topic: URL change, topic: rename

#723 Update URL of "SimpleCLI"
  registry.txt
Labels: topic: URL change

#809 Add asukiaaa/arduino-TC78B009FTG
  repositories.txt
Labels: topic: submission

#810 Update repositories.txt
  repositories.txt
Labels: topic: submission

#811 Update repositories.txt
  repositories.txt
Labels: topic: submission

#812 Add asukiaaa/arduino-HzMeter
  repositories.txt
Labels: topic: submission

#813 Update repositories.txt
  repositories.txt
Labels: topic: submission

#818 Use major version ref of `carlosperate/download-file-action`
  .github/workflows/check-taskfiles.yml
Labels: type: enhancement, topic: infrastructure

#819 Update repositories.txt
  repositories.txt
Labels: topic: submission

#820 Update repositories.txt
  repositories.txt
Labels: topic: submission

#808 Update URL and name of "Blinkenlight
  registry.txt
Labels: topic: URL change, topic: rename

#822 Add "pending backend" repository label
  .github/label-configuration-files/labels.yml
Labels: type: enhancement, topic: infrastructure, topic: other

#823 Adding Carduino library
  repositories.txt
Labels: topic: submission

#824 Update repositories.txt
  repositories.txt
Labels: topic: submission

#825 Update repositories.txt
  repositories.txt
Labels: topic: submission

#826 Update repositories.txt added rneurink pca9622
  repositories.txt
Labels: topic: submission

#827 Update repositories.txt
  repositories.txt
Labels: topic: submission

#829 Update repositories.txt
  repositories.txt
Labels: topic: submission

#830 Update repositories.txt
  repositories.txt
Labels: topic: submission

#814 Update repositories.txt
  repositories.txt
Labels: topic: submission

#831 Add Arduino_EMBRYO_2 library
  repositories.txt
Labels: topic: submission

#832 Update repositories.txt
  repositories.txt
Labels: topic: submission

#833 Update repositories.txt
  repositories.txt
Labels: topic: submission

#835 Update repositories.txt
  repositories.txt
Labels: topic: submission

#836 add 3bc language libary
  repositories.txt
Labels: topic: submission

#837 Update repositories.txt
  repositories.txt
Labels: topic: submission

#838 Update repositories.txt
  repositories.txt
Labels: topic: submission

#839 Update repositories.txt
  repositories.txt
Labels: topic: submission

#840 Update repositories.txt
  repositories.txt
Labels: topic: submission

#841 Update repositories.txt
  repositories.txt
Labels: topic: submission

#842 Update repositories.txt
  repositories.txt
Labels: topic: submission

#843 Update repositories.txt
  repositories.txt
Labels: topic: submission

#844 Update repositories.txt
  repositories.txt
Labels: topic: submission

#848 Add iot ble decoder library
  repositories.txt
Labels: topic: submission

#849 Update repositories.txt
  repositories.txt
Labels: topic: submission

#791 Update repositories.txt
  repositories.txt
Labels: topic: submission

#850 Update repositories.txt
  repositories.txt
Labels: topic: submission
