Repository arduino/library-registry, pull requests merged in 2021-06, with the labels that each got.

#40 Add https://github.com/ARTS37/SerialMenuCmd
  repositories.txt
Labels: submission

#42 Add https://github.com/ArduinoShop/Seg7
  repositories.txt
Labels: submission

#43 Add https://github.com/RobTillaart/TSL235R
  repositories.txt
Labels: submission

#44 Add https://github.com/RobTillaart/relativity
  repositories.txt
Labels: submission

#45 Add https://github.com/atc1441/NETSGPClient
  repositories.txt
Labels: submission

#41 Rename Sqlite3 to Sqlite3 for ESP8266
  registry.txt
Labels: modification

#46 Add https://github.com/noah1510/generic-Arduino
  repositories.txt
Labels: submission

#47 Add https://github.com/bitbank2/PNGdec
  repositories.txt
Labels: submission

#48 Add https://github.com/sparkfun/SparkFun_Qwiic_6DoF_LSM6DSO_Arduino_Library
  repositories.txt
Labels: submission

#49 Add https://github.com/RobTillaart/MAX14661
  repositories.txt
Labels: submission

#50 Add RCmags libraries
  repositories.txt
Labels: submission

#51 Add https://github.com/pierremolinaro/rp2040-charlieplexing
  repositories.txt
Labels: submission

#53 Add https://github.com/Mysues/ERO
  repositories.txt
Labels: submission

#54 Add https://github.com/dimag0g/PPM-reader
  repositories.txt
Labels: submission

#52 NRF_HAL library URL fix
  repositories.txt
Labels: modification

#55 Update NRF_HAL repository URL
  registry.txt
Labels: modification

#56 Add fpgaarcade replay mkrvidor4000
  repositories.txt
Labels: submission

#57 Update repositories.txt
  repositories.txt
Labels: submission

#58 Add MBED_RPI_PICO_TimerInterrupt Library
  repositories.txt
Labels: submission

#60 Added sACNSource library
  repositories.txt
Labels: submission

#61 Added Infineon BGT60 Radar
  repositories.txt
Labels: submission

#62 PodEnoSim library url added
  repositories.txt
Labels: submission

#68 Added unzipLIB
  repositories.txt
Labels: submission

#69 Add ESP32 Canon BLE Remote Library
  repositories.txt
Labels: submission

#72 Add Grove-Ranging-sensor-VL53L0X Library
  repositories.txt
Labels: submission

#73 add TCA9555
  repositories.txt
Labels: submission

#67 Rename Sercom SPI Slave to SercomSPISlave
  registry.txt
Labels: modification

#76 Add LittleFS_Mbed_RP2040 to Library Manager
  repositories.txt
Labels: submission

#77 Add Loki and Prometheus clients with supporting libraries
  repositories.txt
Labels: submission

#79 Update repositories.txt
  repositories.txt
Labels: submission

#82 Update repositories.txt
  repositories.txt
Labels: submission

#83 Update repositories.txt
  repositories.txt
Labels: submission

#84 Add RP2040_RTC to Library Manager
  repositories.txt
Labels: submission

#85 Add Seeed_Arduino_Audio Library
  repositories.txt
Labels: submission

#86 Add VL53L1X_ULD library
  repositories.txt
Labels: submission

#87 Update repositories.txt
  repositories.txt
Labels: submission

#88 Added GLEE2023 Arduino Library to Libraries manager list
  repositories.txt
Labels: submission

#91 add controlVoltage library
  repositories.txt
Labels: submission

#94 Add ClockForSeg Library
  repositories.txt
Labels: submission

#96 Update repositories.txt
  repositories.txt
Labels: submission

#97 OTAdriveESP
  repositories.txt
Labels: submission

#98 Add RP2040_SD library to Library Manager
  repositories.txt
Labels: submission

#99 Update repositories.txt
  repositories.txt
Labels: submission

#100 Update repositories.txt
  repositories.txt
Labels: submission

#102 Update repositories.txt
  repositories.txt
Labels: submission

#104 Adding TinyUSBSimplePacketComs library
  repositories.txt
Labels: submission

#105 Update repositories.txt
  repositories.txt
Labels: submission

#106 Update repositories.txt
  repositories.txt
Labels: submission

#107 Added 2 libraries
  repositories.txt
Labels: submission

#108 Update repositories.txt
  repositories.txt
Labels: submission

#109 Update repositories.txt.
  repositories.txt
Labels: submission

#111 Adding FANTM libdevlpr to Arduino library registry.
  repositories.txt
Labels: submission

#114 Update repositories.txt
  repositories.txt
Labels: submission

#115 add TeensyVariablePlayback library
  repositories.txt
Labels: submission

#116 add RobTIllaart/SGP30
  repositories.txt
Labels: submission

#117 MacroLogger apm submission request
  repositories.txt
Labels: submission

#118 Add ESP8266_multipart library
  repositories.txt
Labels: submission

#119 Update repositories.txt
  repositories.txt
Labels: submission

#121 Update repositories.txt
  repositories.txt
Labels: submission

#122 Added AT24Cxx EEPROM Library
  repositories.txt
Labels: submission

#124 Update repositories.txt
  repositories.txt
Labels: submission

#125 Update repositories.txt
  repositories.txt
Labels: removal

#129 Adding RFCodes library
  repositories.txt
Labels: submission

#128 Update repositories.txt
  repositories.txt
Labels: modification

#131 Adding Arduino_PortentaBreakoutLibrary
  repositories.txt
Labels: submission

#132 Add SparkFun_SCD4x_Arduino_Library
  repositories.txt
Labels: submission

#133 Update repositories.txt
  repositories.txt
Labels: submission

#134 Remove Arduino_PortentaBreakoutCarrier
  repositories.txt
Labels: removal

#136 Update repositories.txt
  repositories.txt
Labels: submission

#137 Add Controller Utilities library
  repositories.txt
Labels: submission

#138 Update repositories.txt
  repositories.txt
Labels: submission

#139 Add TinyDebug library
  repositories.txt
Labels: submission

#126 Remove "Matrix Color Sensor Library" and "Matrix Motion Sensor Library"
  registry.txt
Labels: removal

#140 Change the BBQ10Keyboard url
  repositories.txt
Labels: modification
