Repository arduino/library-registry, pull requests merged in 2022-10, with the labels that each got.

#1925 Update repositories.txt
  repositories.txt
Labels: topic: submission

#1926 gyroturn.txt
  repositories.txt
Labels: topic: submission

#1928 clicli.txt
  repositories.txt
Labels: topic: submission

#1929 Update repositories.txt
  repositories.txt
Labels: topic: submission

#1930 add jled-pca9685-hal
  repositories.txt
Labels: topic: submission

#1931 Add LCD FeatherWing from Oddly Specific Objects
  repositories.txt
Labels: topic: submission

#1932 Update repositories.txt
  repositories.txt
Labels: topic: submission

#1934 Update repositories.txt
  repositories.txt
Labels: topic: submission

#1935 Add RAKwireless Autumn Launch Module libraries
  repositories.txt
Labels: topic: submission

#1936 Update repositories.txt
  repositories.txt
Labels: topic: submission

#1938 Update repositories.txt
  repositories.txt
Labels: topic: submission

#1940 Add DRV8870 Motor Drive Library
  repositories.txt
Labels: topic: submission

#1941 Update repositories.txt
  repositories.txt
Labels: topic: submission

#1943 Add ClusterDuck-Protocol to Arduino Libraries
  repositories.txt
Labels: topic: submission

#1944 Update repositories.txt
  repositories.txt
Labels: topic: submission

#1945 Add library of ABLIC S-5813A, S-5814A
  repositories.txt
Labels: topic: submission

#1946 Update repositories.txt
  repositories.txt
Labels: topic: submission

#1949 Update repositories.txt
  repositories.txt
Labels: topic: submission

#1951 Add library of AD22100A
  repositories.txt
Labels: topic: submission

#1952 Add library of AD22100A
  repositories.txt
Labels: topic: submission

#1953 Add library of AD22100S
  repositories.txt
Labels: topic: submission

#1954 Update repositories.txt
  repositories.txt
Labels: topic: submission

#1955 Add Arduino_BMI270_BMM150
  repositories.txt
Labels: topic: submission

#1956 Update repositories.txt
  repositories.txt
Labels: topic: submission

#1957 Update repositories.txt
  repositories.txt
Labels: topic: submission

#1958 Add DRV8434S library
  repositories.txt
Labels: topic: submission

#1959 Added MAX30001 repo
  repositories.txt
Labels: topic: submission

#1960 add m5stack/M5Unit-Thermal2.
  repositories.txt
Labels: topic: submission

#1962 Update repositories.txt
  repositories.txt
Labels: topic: submission

#1963 Add library of MAX6613MXK, MAX6613MXKV
  repositories.txt
Labels: topic: submission

#1965 Update repositories.txt
  repositories.txt
Labels: topic: submission

#1919 Update name of "Signature"
  registry.txt
Labels: topic: rename, status: pending backend

#1942 Update name of "EoH Platform"
  registry.txt
Labels: topic: rename, status: pending backend

#1964 Update name of "Deneyap Dokunmatik Tus Takimi"
  registry.txt
Labels: topic: rename, status: pending backend

#1966 Update repositories.txt
  repositories.txt
Labels: topic: submission

#1967 Update repositories.txt
  repositories.txt
Labels: topic: submission

#1970 Add library of MAX6605MXK
  repositories.txt
Labels: topic: submission

#1971 Add library of MAX6605MXKV
  repositories.txt
Labels: topic: submission

#1968 Update repositories.txt
  repositories.txt
Labels: topic: submission

#1972 Added a new library
  repositories.txt
Labels: topic: submission

#1974 Update repositories.txt
  repositories.txt
Labels: topic: submission

#1978 YAMLDuino + ESP32-ENC28J60
  repositories.txt
Labels: topic: submission

#1979 ABLE button library
  repositories.txt
Labels: topic: submission

#1980 New library for Selectrix modeltrain control
  repositories.txt
Labels: topic: modification, topic: URL change

#1981 Add PERIPUMP library
  repositories.txt
Labels: topic: submission

#1982 Add SecureMQTT
  repositories.txt
Labels: topic: submission

#1983 Update repositories.txt
  repositories.txt
Labels: topic: submission

#1984 Add Aranet4-ESP32
  repositories.txt
Labels: topic: submission

#1986 Update repositories.txt
  repositories.txt
Labels: topic: submission

#1987 Update repositories.txt
  repositories.txt
Labels: topic: submission

#1990 Add library of MCP9700, MCP9700A
  repositories.txt
Labels: topic: submission

#1991 Add library of MCP9701, MCP9701A
  repositories.txt
Labels: topic: submission

#1992 Add library of TC1046
  repositories.txt
Labels: topic: submission

#1993 Add library of TC1047, TC1047A
  repositories.txt
Labels: topic: submission

#1994 Update repositories.txt
  repositories.txt
Labels: topic: submission

#1995 Add moduloMap
  repositories.txt
Labels: topic: submission

#1998 Update repositories.txt
  repositories.txt
Labels: topic: submission

#1999 Update repositories.txt
  repositories.txt
Labels: topic: submission

#2001 Update repositories.txt
  repositories.txt
Labels: topic: submission

#1997 Update name of "IoT Suite"
  registry.txt
Labels: topic: rename, status: pending backend

#1976 Update name of "Makerlabvn_I2C_Motor_Driver"
  registry.txt
Labels: topic: rename, status: pending backend

#2002 Add library of MPX5999D
  repositories.txt
Labels: topic: submission

#2005 Add libray of MPXHZ6250A
  repositories.txt
Labels: topic: submission

#2008 Update repositories.txt
  repositories.txt
Labels: topic: submission

#2009 Update repositories.txt
  repositories.txt
Labels: topic: submission

#2011 Add RAK12027 Seismic Sensor Library
  repositories.txt
Labels: topic: submission

#2012 Update repositories.txt
  repositories.txt
Labels: topic: submission

#2018 Update repositories.txt
  repositories.txt
Labels: topic: submission

#2019 Update repositories.txt
  repositories.txt
Labels: topic: submission

#2027 Update repositories.txt
  repositories.txt
Labels: topic: submission

#2028 Add Arduino-Base32 library
  repositories.txt
Labels: topic: submission

#2029 TOTP generator
  repositories.txt
Labels: topic: submission

#2030 [Library Manager] Add AVR_PWM Library
  repositories.txt
Labels: topic: submission

#2031 Add MCP4151 library
  repositories.txt
Labels: topic: submission

#2032 Update repositories.txt
  repositories.txt
Labels: topic: submission

#2035 Add library of BD1020HFV
  repositories.txt
Labels: topic: submission

#2036 Add library of STLM20DD9F
  repositories.txt
Labels: topic: submission

#2037 Add library of STLM20W87F
  repositories.txt
Labels: topic: submission

#2038 [Library Manager] Add megaAVR_PWM library
  repositories.txt
Labels: topic: submission

#2039 Added https://github.com/ArminJo/LCDBigNumbers
  repositories.txt
Labels: topic: submission
