Repository arduino/library-registry, pull requests merged in 2022-06, with the labels that each got.

#1455 Add PneumaticStepper library
  repositories.txt
Labels: topic: submission

#1456 Add Preferences library for ESP8266 and Particle devices
  repositories.txt
Labels: topic: submission

#1458 Update repositories.txt
  repositories.txt
Labels: topic: submission

#1460 Add SparkFun BMP384 library
  repositories.txt
Labels: topic: submission

#1461 Update repositories.txt
  repositories.txt
Labels: topic: submission

#1465 Added SIKTEC-EPD Library - For E-paper displays
  repositories.txt
Labels: topic: submission

#1466 Add janscience/TeeRec library
  repositories.txt
Labels: topic: submission

#1464 Update repositories.txt
  repositories.txt
Labels: topic: submission

#1467 Added ADC Buttons
  repositories.txt
Labels: topic: submission

#1468 Update repositories.txt
  repositories.txt
Labels: topic: submission

#1470 Update repositories.txt
  repositories.txt
Labels: topic: submission

#1472 adding BlueMicro Engine
  repositories.txt
Labels: topic: submission

#1473 Update repositories.txt
  repositories.txt
Labels: topic: submission

#1474 Update repositories.txt
  repositories.txt
Labels: topic: submission

#1475 NTPtime
  repositories.txt
Labels: topic: submission

#1479 Update repositories.txt
  repositories.txt
Labels: topic: submission

#1480 NEvents
  repositories.txt
Labels: topic: submission

#1481 Update repositories.txt
  repositories.txt
Labels: topic: submission

#1482 QRCodeEink
  repositories.txt
Labels: topic: submission

#1483 Update repositories.txt
  repositories.txt
Labels: topic: submission

#1484 Update repositories.txt
  repositories.txt
Labels: topic: submission

#1487 Update repositories.txt
  repositories.txt
Labels: topic: submission

#1488 Adding Bluemicro libraries
  repositories.txt
Labels: topic: submission

#1476 my username link updated
  repositories.txt
Labels: topic: modification, topic: URL change, status: pending backend

#1477 Update name of "ddns-nightly"
  registry.txt
Labels: topic: rename, status: pending backend

#1491 Update repositories.txt
  repositories.txt
Labels: topic: submission

#1495 Update repositories.txt
  repositories.txt
Labels: topic: submission

#1497 Update repositories.txt
  repositories.txt
Labels: topic: submission

#1498 Add Gravitone
  repositories.txt
Labels: topic: submission

#1499 Update repositories.txt
  repositories.txt
Labels: topic: submission

#1500 Add LeeLeahy2/SdCardServer
  repositories.txt
Labels: topic: submission

#1504 Inclusion of E220Lib
  repositories.txt
Labels: topic: submission

#1505 Update repositories.txt
  repositories.txt
Labels: topic: submission

#1509 Update repositories.txt
  repositories.txt
Labels: topic: submission

#1503 Update name of "Adafruit WipperSnapper"
  registry.txt
Labels: topic: rename, status: pending backend

#1490 Update name and URL of "107-Arduino-Cyphal"
  registry.txt
Labels: topic: URL change, topic: rename, status: pending backend

#1489 Replace 107-Arduino-UAVCAN with 107-Arduino-Cyphal.
  repositories.txt
Labels: conclusion: resolved, topic: modification, topic: URL change, status: pending backend

#1510 Update repositories.txt
  repositories.txt
Labels: topic: submission

#1516 Update repositories.txt
  repositories.txt
Labels: topic: submission

#1517 Add Deneyap 5x7 LED Matrix Arduino Library Manager
  repositories.txt
Labels: topic: submission

#1518 Add Deneyap OLED Display Module Arduino Library Manager
  repositories.txt
Labels: topic: submission

#1521 Add "Simple_HC-SR04_Control" to library manager
  repositories.txt
Labels: topic: submission

#1519 Update repositories.txt
  repositories.txt
Labels: topic: submission

#1523 Add Deneyap Rain Sensor Arduino Library Manager
  repositories.txt
Labels: topic: submission

#1524 Add Deneyap Relay Arduino Library Manager
  repositories.txt
Labels: topic: submission

#1527 Add Deneyap Joystick Arduino Library Manager
  repositories.txt
Labels: topic: submission

#1529 Add Sensirion SFM3000 I2C Arudion library
  repositories.txt
Labels: topic: submission

#1525 delete "Simple_Robot_Motor_Control"
  repositories.txt
Labels: topic: removal, status: pending backend

#1530 Update repositories.txt
  repositories.txt
Labels: topic: submission

#1531 Add Deneyap 6 Dof IMU LSM6DSM Arduino Library Manager
  repositories.txt
Labels: topic: submission

#1532 Add Deneyap Sensors and Modules Arduino Library Manager
  repositories.txt
Labels: topic: submission

#1535 Add Deneyap sensors Arduino Library Manager
  repositories.txt
Labels: topic: submission

#1537 Add Deneyap sensors Arduino Library Manager
  repositories.txt
Labels: topic: submission

#1538 Update repositories.txt
  repositories.txt
Labels: topic: submission

#1541 Add Deneyap sensors Arduino Library Manager
  repositories.txt
Labels: topic: submission

#1543 Update repositories.txt
  repositories.txt
Labels: topic: submission

#1544 Update repositories.txt
  repositories.txt
Labels: topic: submission

#1546 Update repositories.txt
  repositories.txt
Labels: topic: submission

#1549 Add Deneyap Real Time Clock and Deneyap Infrarad Receiver Transmitter Arduino Library Manager
  repositories.txt
Labels: topic: submission
