Repository arduino/library-registry, pull requests merged in 2022-05, with the labels that each got.

#1343 Update repositories.txt
  repositories.txt
Labels: topic: submission

#1344 Added PixieChromaLite
  repositories.txt
Labels: topic: submission

#1346 Update repositories.txt
  repositories.txt
Labels: topic: submission

#1347 Add Sim Racing library
  repositories.txt
Labels: topic: submission

#1348 Add BLESensorGateway
  repositories.txt
Labels: topic: submission

#1349 Update repositories.txt
  repositories.txt
Labels: topic: submission

#1352 Update repositories.txt
  repositories.txt
Labels: topic: submission

#1353 Sync "Check Go Dependencies" workflow with upstream
  .github/workflows/check-go-dependencies-task.yml
Labels: type: enhancement, topic: infrastructure, type: imperfection

#1354 Update repositories.txt
  repositories.txt
Labels: topic: submission

#1359 Update repositories.txt
  repositories.txt
Labels: topic: submission

#1360 Update repositories.txt
  repositories.txt
Labels: topic: submission

#1361 Update repositories.txt
  repositories.txt
Labels: topic: submission

#1363 Update repositories.txt
  repositories.txt
Labels: topic: submission

#1262 Update URL of "AntiKeyRepetition"
  registry.txt
Labels: topic: URL change, status: pending backend

#1261 chore: change address of AntiKeyRepetition.h
  repositories.txt
Labels: conclusion: resolved, topic: modification, status: pending backend

#1342 Remove "Aspen SIM800"
  registry.txt
Labels: topic: removal, status: pending backend

#1341 Update repositories.txt
  repositories.txt
Labels: topic: removal, status: pending backend

#1364 Update repositories.txt
  repositories.txt
Labels: topic: submission

#1365 Adding SIKTEC-MDSwitch library
  repositories.txt
Labels: topic: submission

#1366 Update repositories.txt
  repositories.txt
Labels: topic: submission

#1367 Added SIKTEC-SPI
  repositories.txt
Labels: topic: submission

#1368 Add ResistorReader_asukiaaa
  repositories.txt
Labels: topic: submission

#1369 Adding SIKTEC-SRAM library
  repositories.txt
Labels: topic: submission

#1370 submiting SimpleFSM library
  repositories.txt
Labels: topic: submission

#1371 Add Gauge_asukiaaa
  repositories.txt
Labels: topic: submission

#1372 Update repositories.txt
  repositories.txt
Labels: topic: submission

#1373 Add DHTINT
  repositories.txt
Labels: topic: submission

#1374 Update repositories.txt
  repositories.txt
Labels: topic: submission

#1375 Added NLibs
  repositories.txt
Labels: topic: submission

#1376 Update repositories.txt
  repositories.txt
Labels: topic: submission

#1377 Update repositories.txt
  repositories.txt
Labels: topic: submission

#1378 First releases
  repositories.txt
Labels: topic: submission

#1379 Update repositories.txt
  repositories.txt
Labels: topic: submission

#1380 Use form-based issue templates
  .github/ISSUE_TEMPLATE/bug-report.yml
  .github/ISSUE_TEMPLATE/config.yml
  .github/ISSUE_TEMPLATE/feature-request.yml
  .github/ISSUE_TEMPLATE/release-removal.yml
  .github/ISSUE_TEMPLATE/rename.yml
  FAQ.md
  README.md
Labels: type: enhancement, topic: infrastructure, topic: other

#1381 update repositories.txt
  repositories.txt
Labels: topic: submission

#1382 Update repositories.txt
  repositories.txt
Labels: topic: submission

#1384 Add `FTPClient_Generic` library
  repositories.txt
Labels: topic: submission

#1385 Added NDefs.h dependency
  repositories.txt
Labels: topic: submission

#1386 Adding the SparkFun ADIN1110 Arduino Library
  repositories.txt
Labels: topic: submission

#1388 Add CPUTemp
  repositories.txt
Labels: topic: submission

#1389 Add CPUVolt
  repositories.txt
Labels: topic: submission

#1390 Update repositories.txt
  repositories.txt
Labels: topic: submission

#1392 includes escalator switch gitlab project in repositories.txt
  repositories.txt
Labels: topic: submission

#1393 Add RAKwireless RAK12034 library
  repositories.txt
Labels: topic: submission

#1394 Adding RAK12033 WisBlock module library
  repositories.txt
Labels: topic: submission

#1395 [ADD] Added NTimer
  repositories.txt
Labels: topic: submission

#1399 Update repositories.txt
  repositories.txt
Labels: topic: submission

#1400 Add WiFiManager_RTL8720 Library
  repositories.txt
Labels: topic: submission

#1401 Update repositories.txt
  repositories.txt
Labels: topic: submission

#1402 Update repositories.txt
  repositories.txt
Labels: topic: submission

#1405 Update repositories.txt
  repositories.txt
Labels: topic: submission

#1407 Update repositories.txt
  repositories.txt
Labels: topic: submission

#1408 Update repositories.txt
  repositories.txt
Labels: topic: submission

#1409 Update repositories.txt
  repositories.txt
Labels: topic: modification

#1411 Update repositories.txt
  repositories.txt
Labels: topic: submission

#1412 Update repositories.txt
  repositories.txt
Labels: topic: submission

#1413 Update repositories.txt
  repositories.txt
Labels: topic: submission

#1414 Update repositories.txt
  repositories.txt
Labels: topic: submission

#1416 Update repositories.txt
  repositories.txt
Labels: topic: submission

#1415 Update repositories.txt
  repositories.txt
Labels: topic: submission

#1420 Update repositories.txt
  repositories.txt
Labels: topic: submission

#1421 Update repositories.txt
  repositories.txt
Labels: topic: submission

#1422 Update repositories.txt
  repositories.txt
Labels: topic: submission

#1423 Update repositories.txt
  repositories.txt
Labels: topic: submission

#1425 Add RS485 library
  repositories.txt
Labels: topic: submission

#1426 Update repositories.txt
  repositories.txt
Labels: topic: submission

#1427 Update repositories.txt
  repositories.txt
Labels: topic: submission

#1428 Add initial version of SIMON library
  repositories.txt
Labels: topic: submission

#1431 Update repositories.txt
  repositories.txt
Labels: topic: submission

#1433 Update repositories.txt
  repositories.txt
Labels: topic: submission

#1434 Update repositories.txt
  repositories.txt
Labels: topic: submission

#1436 includes daily service gitlab project in repositories.txt
  repositories.txt
Labels: topic: submission

#1438 Update repositories.txt
  repositories.txt
Labels: topic: submission

#1439 Update repositories.txt
  repositories.txt
Labels: topic: submission

#1443 NHC-SR04
  repositories.txt
Labels: topic: submission

#1444 Add AS5600
  repositories.txt
Labels: topic: submission

#1445 Initial Release
  repositories.txt
Labels: topic: submission

#1447 Update repositories.txt
  repositories.txt
Labels: topic: submission

#1448 Configure link check to use `Accept-Encoding` header for docs.github.com links
  .github/.markdown-link-check.json
Labels: topic: other

#1429 Remove aviancompany/LCD_I2C
  repositories.txt
Labels: conclusion: resolved, topic: removal, status: pending backend

#1450 Update repositories.txt
  repositories.txt
Labels: topic: submission

#1451 new library
  repositories.txt
Labels: topic: submission
