Repository arduino/library-registry, pull requests merged in 2022-04, with the labels that each got.

#1248 Update name and URL of "MovingAveragePlus"
  registry.txt
Labels: conclusion: resolved, topic: URL change, topic: rename, status: pending backend

#1247 Update repositories.txt - Change repository URL
  repositories.txt
Labels: topic: modification, topic: URL change, status: pending backend

#1254 Update repositories.txt
  repositories.txt
Labels: topic: submission

#1256 Update repositories.txt
  repositories.txt
Labels: topic: submission

#1257 Add Ethernet_Generic Library
  repositories.txt
Labels: topic: submission

#1258 added serial lcd
  repositories.txt
Labels: topic: submission

#1259 add LettersKeypad
  repositories.txt
Labels: topic: submission

#1260 Add repository for Sensirion STS4x and SF06-LF
  repositories.txt
Labels: topic: submission

#1264 Update repositories.txt
  repositories.txt
Labels: topic: submission

#1268 Update repositories.txt
  repositories.txt
Labels: topic: submission

#1270 Update repositories.txt
  repositories.txt
Labels: topic: submission

#1271 Added sitronlabs/SitronLabs_OPT3001_Arduino_Library
  repositories.txt
Labels: topic: submission

#1272 Add HUSB238Driver library
  repositories.txt
Labels: topic: submission

#1273 Add NST1001 driver library
  repositories.txt
Labels: topic: submission

#1275 Update repositories.txt
  repositories.txt
Labels: topic: submission

#1279 Update repositories.txt
  repositories.txt
Labels: topic: submission

#1280 Add SerialRecord library
  repositories.txt
Labels: topic: submission

#1281 Merge branch 'main' of https://github.com/arduino/library-registry
  repositories.txt
Labels: topic: submission

#1282 Update repositories.txt
  repositories.txt
Labels: topic: submission

#1285 Update repositories.txt
  repositories.txt
Labels: topic: submission

#1290 Update repositories.txt
  repositories.txt
Labels: topic: submission

#1291 Update repositories.txt
  repositories.txt
Labels: topic: submission

#1294 Add Arduino_MultiWiFi
  repositories.txt
Labels: topic: submission

#1296 Update repositories.txt
  repositories.txt
Labels: topic: submission

#1301 Update repositories.txt
  repositories.txt
Labels: topic: submission

#1302 Update repositories.txt
  repositories.txt
Labels: topic: submission

#1298 Update name and URL of "CAN_BUS_Shield"
  registry.txt
Labels: topic: URL change, topic: rename, status: pending backend

#1297 Update URL of "CAN_BUS_Shield"
  repositories.txt
Labels: topic: modification, topic: URL change, status: pending backend

#1299 Update repositories.txt
  repositories.txt
Labels: topic: removal, status: pending backend

#1269 Remove "ArreyExt"
  registry.txt
Labels: topic: removal, status: pending backend

#1266 Update repositories.txt
  repositories.txt
Labels: topic: removal, status: pending backend

#1303 Adding the SparkFun Qwiic TMF882X Arduino Library
  repositories.txt
Labels: topic: submission

#1304 Add SparkFun MMC5983MA library
  repositories.txt
Labels: topic: submission

#1305 Add AsyncWebServer_Ethernet Library
  repositories.txt
Labels: topic: submission

#1306 Add AsyncUDP_Ethernet Library
  repositories.txt
Labels: topic: submission

#1307 Update repositories.txt
  repositories.txt
Labels: topic: submission

#1310 Update repositories.txt
  repositories.txt
Labels: topic: submission

#1311 Update repositories.txt
  repositories.txt
Labels: topic: submission

#1312 Update repositories.txt
  repositories.txt
Labels: topic: submission

#1313 Update repositories.txt
  repositories.txt
Labels: topic: submission

#1314 Update repositories.txt
  repositories.txt
Labels: topic: submission

#1316 Update repositories.txt
  repositories.txt
Labels: topic: submission

#1318 Event driven Ethernet lib for Wiznet Pi Pico
  repositories.txt
Labels: topic: submission

#1319 New libraries: TCA9544A and AD5243
  repositories.txt
Labels: topic: submission

#1321 Update repositories.txt
  repositories.txt
Labels: topic: submission

#1322 Add luni64/EncoderTool
  repositories.txt
Labels: topic: submission

#1323 Update repositories.txt
  repositories.txt
Labels: topic: submission

#1324 Update repositories.txt
  repositories.txt
Labels: topic: submission

#1325 Update repositories.txt
  repositories.txt
Labels: topic: submission

#1327 Update repositories.txt
  repositories.txt
Labels: topic: submission

#1328 Update repositories.txt
  repositories.txt
Labels: topic: submission

#1330 Add Mini QOI Library
  repositories.txt
Labels: topic: submission

#1331 Add the ContinuousStepper library
  repositories.txt
Labels: topic: submission

#1332 Update repositories.txt
  repositories.txt
Labels: topic: submission

#1334 Update repositories.txt
  repositories.txt
Labels: topic: submission

#1335 Added Unexpected Maker ESP32-S3 helper library
  repositories.txt
Labels: topic: submission

#1337 Update repositories.txt
  repositories.txt
Labels: topic: submission

#1338 Update repositories.txt
  repositories.txt
Labels: topic: submission

#1339 Add FTP_Server_Teensy41 Library
  repositories.txt
Labels: topic: submission

#1340 Update repositories.txt
  repositories.txt
Labels: topic: submission
