Repository arduino/library-registry, pull requests merged in 2022-09, with the labels that each got.

#1781 Update repositories.txt
  repositories.txt
Labels: topic: submission

#1785 Added https://github.com/ArminJo/digitalWriteFast
  repositories.txt
Labels: topic: submission

#1786 Update repositories.txt
  repositories.txt
Labels: topic: submission

#1787 re-sorted https://github.com/icomedit/Arduino-KIMlib
  repositories.txt
Labels: topic: modification

#1788 Update repositories.txt
  repositories.txt
Labels: topic: submission

#1789 Add SparkFun_ST25DV64KC_Arduino_Library
  repositories.txt
Labels: topic: submission

#1791 adding DigiPot library
  repositories.txt
Labels: topic: submission

#1792 Add WisBlock Audio Library
  repositories.txt
Labels: topic: submission

#1793 Update repositories.txt
  repositories.txt
Labels: topic: submission

#1795 Update repositories.txt
  repositories.txt
Labels: topic: submission

#1805 Update repositories.txt
  repositories.txt
Labels: topic: submission

#1807 Update repositories.txt
  repositories.txt
Labels: topic: submission

#1809 Add MCP23017 library
  repositories.txt
Labels: topic: submission

#1810 NXP MPXA4250A library register
  repositories.txt
Labels: topic: submission

#1811 Add CheckDS18B20
  repositories.txt
Labels: topic: submission

#1812 Update repositories.txt
  repositories.txt
Labels: topic: submission

#1814 Add arduFPGA-app-common-arduino repository
  repositories.txt
Labels: topic: submission

#1816 Add experimental INA219 library
  repositories.txt
Labels: topic: submission

#1817 Add DLLN3X Zigbee Mesh Module Library
  repositories.txt
Labels: topic: submission

#1818 Update repositories.txt
  repositories.txt
Labels: topic: submission

#1819 Update repositories.txt
  repositories.txt
Labels: topic: submission

#1820 Update repositories.txt -- Adding MacroDebugger.
  repositories.txt
Labels: topic: submission

#1822 Update repositories.txt
  repositories.txt
Labels: topic: submission

#1823 Add IOXESP32Motor lib
  repositories.txt
Labels: topic: submission

#1824 Update repositories.txt
  repositories.txt
Labels: topic: submission

#1825 Update repositories.txt
  repositories.txt
Labels: topic: submission

#1826 Please include the library mrm-lid-d
  repositories.txt
Labels: topic: submission

#1827 Add Erin Gee's BioData library to the registry.
  repositories.txt
Labels: topic: submission

#1828 Update repositories.txt
  repositories.txt
Labels: topic: submission

#1831 Add xsens_mti library
  repositories.txt
Labels: topic: submission

#1832 Add React_Generic Library
  repositories.txt
Labels: topic: submission

#1844 Update repositories.txt
  repositories.txt
Labels: topic: submission

#1847 Update repositories.txt
  repositories.txt
Labels: topic: submission

#1850 Update repositories.txt
  repositories.txt
Labels: topic: submission

#1853 MAX7219Segment Library for 7 Segment
  repositories.txt
Labels: topic: submission

#1855 Adding link to MAX9744 library
  repositories.txt
Labels: topic: submission

#1856 SignatureRow Library
  repositories.txt
Labels: topic: submission

#1857 Update repositories.txt
  repositories.txt
Labels: topic: submission

#1852 ABLIC S-58LM20A Temperature sensor Library
  repositories.txt
Labels: topic: submission

#1858 Add pocketBME280 library
  repositories.txt
Labels: topic: submission

#1851 Rename "PROGMEMAssert"
  registry.txt
Labels: topic: rename, status: pending backend

#1860 Update repositories.txt
  repositories.txt
Labels: topic: submission

#1861 M5Hat-JoyC
  repositories.txt
Labels: topic: submission

#1862 Update repositories.txt
  repositories.txt
Labels: topic: submission

#1866 Update repositories.txt
  repositories.txt
Labels: topic: submission

#1867 Update repositories.txt
  repositories.txt
Labels: topic: submission

#1869 Update repositories.txt
  repositories.txt
Labels: topic: submission

#1872 Update repositories.txt
  repositories.txt
Labels: topic: submission

#1873 Update repositories.txt
  repositories.txt
Labels: topic: submission

#1874 Update repositories.txt
  repositories.txt
Labels: topic: submission

#1875 Update repositories.txt
  repositories.txt
Labels: topic: submission

#1876 ESP32PsramLock
  repositories.txt
Labels: topic: submission

#1881 Update repositories.txt
  repositories.txt
Labels: topic: submission

#1882 Update repositories.txt
  repositories.txt
Labels: topic: submission

#1883 Adding Adafruit-TCA8418 library
  repositories.txt
Labels: topic: submission

#1884 Update repositories.txt
  repositories.txt
Labels: topic: submission

#1892 Update repositories.txt
  repositories.txt
Labels: topic: submission

#1894 Update repositories.txt
  repositories.txt
Labels: topic: submission

#1896 New library marisa-esp32
  repositories.txt
Labels: topic: submission

#1897 Update repositories.txt
  repositories.txt
Labels: topic: submission

#1898 added Arduino-DumbDisplay
  repositories.txt
Labels: topic: submission

#1899 Add mupplet-sensor library of project muwerk
  repositories.txt
Labels: topic: submission

#1900 added https://github.com/teemune/TE_SM9000_library
  repositories.txt
Labels: topic: submission

#1901 Update repositories.txt
  repositories.txt
Labels: topic: submission

#1903 Add OWire LED Library
  repositories.txt
Labels: topic: submission

#1904 Update repositories.txt
  repositories.txt
Labels: topic: submission

#1906 Update repositories.txt
  repositories.txt
Labels: topic: submission

#1908 Update repositories.txt
  repositories.txt
Labels: topic: submission

#1909 Update repositories.txt
  repositories.txt
Labels: topic: submission

#1910 Update repositories.txt
  repositories.txt
Labels: topic: submission

#1915 Update repositories.txt
  repositories.txt
Labels: topic: submission

#1865 Remove some old links
  repositories.txt
Labels: topic: removal, status: pending backend

#1887 Remove M5Stack libraries
  registry.txt
Labels: topic: removal, status: pending backend

#1885 Update repositories.txt
  repositories.txt
Labels: topic: modification, status: pending backend

#1886 Update name and URL of "OSS-EC NXP MPXA4250A 00000057"
  registry.txt
Labels: topic: URL change, status: pending backend

#1905 Update name of "TE SM9000-series"
  registry.txt
Labels: conclusion: resolved, topic: rename, status: pending backend

#1911 rename Arduino-SignatureRow to Arduino-Signature
  repositories.txt
Labels: topic: modification, topic: URL change, status: pending backend

#1912 Update URL of "SignatureRow"
  registry.txt
Labels: topic: URL change, status: pending backend

#1922 Adding SparkFun_TPA2016D2_Arduino_Library
  repositories.txt
Labels: topic: submission

#1920 Adding the Library ReciclaBot
  repositories.txt
Labels: topic: submission
