Repository arduino/library-registry, pull requests merged in 2022-02, with the labels that each got.

#999 Update URL of "SparkFun Si7021 Humidity and Temperature Sensor"
  repositories.txt
Labels: topic: modification

#1001 Please add TSBridge library.
  repositories.txt
Labels: topic: submission

#1000 Update URL of "SparkFun Si7021 Humidity and Temperature Sensor"
  registry.txt
Labels: topic: URL change, status: pending backend

#996 Add Sensair S8 UART library
  repositories.txt
Labels: topic: submission

#1004 Added lwIOLink
  repositories.txt
Labels: topic: submission

#1005 Please add SimpleFOCDrivers library
  repositories.txt
Labels: topic: submission

#1006 Add EventButton
  repositories.txt
Labels: topic: submission

#1007 Add Soundex class
  repositories.txt
Labels: topic: submission

#1008 Update repositories.txt
  repositories.txt
Labels: topic: submission

#1010 Update repositories.txt
  repositories.txt
Labels: topic: submission

#1011 Create repositories.txt
  repositories.txt
Labels: topic: submission

#1020 Add EventAnalog
  repositories.txt
Labels: topic: submission

#1022 Update repositories.txt
  repositories.txt
Labels: topic: submission

#1026 Added link to DM8BA10 library
  repositories.txt
Labels: topic: submission

#1028 Update repositories.txt
  repositories.txt
Labels: topic: submission

#1030 Removed Kinematics library
  repositories.txt
Labels: topic: removal

#1032 Add nRF52_MBED_PWM
  repositories.txt
Labels: topic: submission

#1029 Update repositories.txt
  repositories.txt
Labels: topic: submission

#1033 Update repositories.txt
  repositories.txt
Labels: topic: submission

#1034 Add EmotiBit ADS1X15 to Arduino Library manager
  repositories.txt
Labels: topic: submission

#1035 Add MBED_RP2040_PWM Library
  repositories.txt
Labels: topic: submission

#1036 Add HAMqttDiscoveryHandler library
  repositories.txt
Labels: topic: submission

#1038 Update repositories.txt
  repositories.txt
Labels: topic: submission

#1039 Update repositories.txt
  repositories.txt
Labels: topic: submission

#1043 Update repositories.txt
  repositories.txt
Labels: topic: submission

#1045 Update repositories.txt
  repositories.txt
Labels: topic: submission

#1047 Update repositories.txt
  repositories.txt
Labels: topic: modification, topic: URL change

#1048 add X9C10X - digital potentiometer classes
  repositories.txt
Labels: topic: submission

#1049 Update repositories.txt
  repositories.txt
Labels: topic: submission

#1051 Update repositories.txt
  repositories.txt
Labels: topic: submission

#1052 Publishing Arduino_Braccio_plusplus!
  repositories.txt
Labels: topic: submission

#1053 Update repositories.txt
  repositories.txt
Labels: topic: submission

#1055 Update repositories.txt
  repositories.txt
Labels: topic: submission

#1056 Add WiFiMulti_Generic Library
  repositories.txt
Labels: topic: submission

#1031 Remove "Kinematics"
  registry.txt
Labels: topic: removal, status: pending backend

#1058 Update repositories.txt
  repositories.txt
Labels: topic: submission

#1060 add Ai COCOCAM library
  repositories.txt
Labels: topic: submission

#1061 Update repositories.txt
  repositories.txt
Labels: topic: submission

#1062 Update repositories.txt
  repositories.txt
Labels: topic: submission

#1063 Update repositories.txt
  repositories.txt
Labels: topic: submission

#1057 Update repositories.txt
  repositories.txt
Labels: topic: submission

#1065 Add justcallmekoko/SwitchLib to repository list
  repositories.txt
Labels: topic: submission

#1064 Adding BleepingLibrary - ESP32 Provisioning and configuration made easy.
  repositories.txt
Labels: topic: submission

#1067 add https://github.com/Jueff/FireplaceMLX
  repositories.txt
Labels: topic: submission

#1071 Update repositories.txt
  repositories.txt
Labels: topic: submission

#1075 Update repositories.txt
  repositories.txt
Labels: topic: submission

#1080 Update repositories.txt
  repositories.txt
Labels: topic: submission

#1081 Add new library - nexgen_filter
  repositories.txt
Labels: topic: submission

#1082 Update repositories.txt
  repositories.txt
Labels: topic: submission

#1083 add https://github.com/Jueff/InfraredMLX
  repositories.txt
Labels: topic: submission

#1085 Update repositories.txt
  repositories.txt
Labels: topic: submission

#1086 Add SparkFun_SGP4_Arduino_Library
  repositories.txt
Labels: topic: submission

#1088 Add SparkFun_Swarm_Satellite_Arduino_Library
  repositories.txt
Labels: topic: submission

#1089 Adding a new library
  repositories.txt
Labels: topic: submission

#1091 Update repositories.txt
  repositories.txt
Labels: topic: removal

#1093 Update repositories.txt
  repositories.txt
Labels: topic: submission

#1095 Update repositories.txt
  repositories.txt
Labels: topic: submission

#1097 Remove "Console"
  registry.txt
Labels: topic: code, type: imperfection

#1099 Update repositories.txt
  repositories.txt
Labels: topic: submission

#1103 Update repositories.txt
  repositories.txt
Labels: topic: submission

#1104 Update repositories.txt
  repositories.txt
Labels: topic: submission

#1105 Update repositories.txt
  repositories.txt
Labels: topic: submission

#1106 Update repositories.txt
  repositories.txt
Labels: topic: submission

#1109 added SimpleJ1939
  repositories.txt
Labels: topic: submission

#1110 Update repositories.txt
  repositories.txt
Labels: topic: submission

#1111 Update repositories.txt
  repositories.txt
Labels: topic: submission

#1115 Update repositories.txt
  repositories.txt
Labels: topic: submission

#1117 Update repositories.txt
  repositories.txt
Labels: topic: submission

#1118 Create repositories.txt
  repositories.txt
Labels: topic: submission

#1123 Update repositories.txt
  repositories.txt
Labels: topic: submission

#1128 Add L298NDriver library
  repositories.txt
Labels: topic: submission

#1129 Added `BetterOTA`.
  repositories.txt
Labels: topic: submission
