Repository arduino/library-registry, pull requests merged in 2022-08, with the labels that each got.

#1669 Update repositories.txt
  repositories.txt
Labels: topic: submission

#1671 Update repositories.txt
  repositories.txt
Labels: topic: submission

#1672 Add AD5245 library
  repositories.txt
Labels: topic: submission

#1673 Update repositories.txt
  repositories.txt
Labels: topic: submission

#1633 Update URL of "Beelan LoRaWAN"
  registry.txt
Labels: topic: URL change, status: pending backend

#1631 Change repo for Beelan Library
  repositories.txt
Labels: topic: modification, topic: URL change, status: pending backend

#1636 Update URL of "SuplaDevice"
  registry.txt
Labels: topic: URL change, status: pending backend

#1634 Change url for SuplaDevice library
  repositories.txt
Labels: topic: modification, topic: URL change, status: pending backend

#1640 Remove azure-iot-sdk-c libraries
  registry.txt
Labels: topic: removal, status: pending backend

#1639 Deprecating old github/azure-iot-sdk-c Arduino libraries
  repositories.txt
Labels: conclusion: resolved, topic: removal, status: pending backend

#1644 Rename "M5Module-4Relay"
  registry.txt
Labels: conclusion: resolved, topic: rename, status: pending backend

#1675 Update repositories.txt
  repositories.txt
Labels: topic: submission

#1676 Added lewisxhe/XPowersLib
  repositories.txt
Labels: topic: submission

#1678 Added TrueProx Arduino library
  repositories.txt
Labels: topic: submission

#1679 Added helper library for the Bee S3 board
  repositories.txt
Labels: topic: submission

#1680 added library for the Bee Motion S3
  repositories.txt
Labels: topic: submission

#1687 Create repositories.txt
  repositories.txt
Labels: topic: submission

#1688 M5Station
  repositories.txt
Labels: topic: submission

#1689 Add https://github.com/Bodmer/TFT_eWidget
  repositories.txt
Labels: topic: submission

#1690 Add Deneyap Speaker
  repositories.txt
Labels: topic: submission

#1691 Update repositories.txt
  repositories.txt
Labels: topic: submission

#1692 Update repositories.txt
  repositories.txt
Labels: topic: submission

#1693 Update repositories.txt
  repositories.txt
Labels: topic: submission

#1695 Update repositories.txt
  repositories.txt
Labels: topic: submission

#1696 Adds ISM330DHCX 6DoF Arduino Library
  repositories.txt
Labels: topic: submission

#1697 Update repositories.txt
  repositories.txt
Labels: topic: submission

#1698 Update repositories.txt
  repositories.txt
Labels: topic: submission

#1699 Update repositories.txt
  repositories.txt
Labels: topic: submission

#1700 add SmoothProgress bars library
  repositories.txt
Labels: topic: submission

#1701 Update repositories.txt
  repositories.txt
Labels: topic: submission

#1702 Added https://github.com/DanForever/DF-Print
  repositories.txt
Labels: topic: submission

#1703 Add AsyncTCP_RP2040W Library
  repositories.txt
Labels: topic: submission

#1704 Add AsyncWebServer_RP2040W Library
  repositories.txt
Labels: topic: submission

#1705 Add AsyncHTTPRequest_RP2040W Library
  repositories.txt
Labels: topic: submission

#1706 Update repositories.txt
  repositories.txt
Labels: topic: submission

#1707 Update repositories.txt
  repositories.txt
Labels: topic: submission

#1708 Add AsyncUDP_RP2040W Library
  repositories.txt
Labels: topic: submission

#1709 Add AsyncDNSServer_RP2040W Library
  repositories.txt
Labels: topic: submission

#1710 Add JTAG Interface library
  repositories.txt
Labels: topic: submission

#1711 Add DiodeIoT SI Series Boards
  repositories.txt
Labels: topic: submission

#1712 M5Unit-RELAY
  repositories.txt
Labels: topic: submission

#1715 Update repositories.txt
  repositories.txt
Labels: topic: submission

#1716 Update repositories.txt
  repositories.txt
Labels: topic: submission

#1717 Update repositories.txt
  repositories.txt
Labels: topic: submission

#1722 Update repositories.txt
  repositories.txt
Labels: topic: submission

#1723 Update repositories.txt
  repositories.txt
Labels: topic: submission

#1724 Update repositories.txt
  repositories.txt
Labels: topic: submission

#1725 Update repositories.txt
  repositories.txt
Labels: topic: submission

#1728 Update repositories.txt
  repositories.txt
Labels: topic: submission

#1729 M5-LoRaWAN
  repositories.txt
Labels: topic: submission

#1730 Update repositories.txt
  repositories.txt
Labels: topic: submission

#1732 Update repositories.txt
  repositories.txt
Labels: topic: submission

#1734 Add WiFiManager_RP2040W_Lite Library
  repositories.txt
Labels: topic: submission

#1735 add https://github.com/adafruit/Adafruit_MAX1704X
  repositories.txt
Labels: topic: submission

#1736 Add WiFiManager_RP2040W Library
  repositories.txt
Labels: topic: submission

#1737 Update repositories.txt
  repositories.txt
Labels: topic: submission

#1739 Add DIYsplay to the Arduino Library Registry
  repositories.txt
Labels: topic: submission

#1740 INA3221
  repositories.txt
Labels: topic: submission

#1741 add Bosch BME68x Library
  repositories.txt
Labels: topic: submission

#1742 Update repositories.txt
  repositories.txt
Labels: topic: submission

#1743 Add ATmega_TimerInterrupt Library
  repositories.txt
Labels: topic: submission

#1744 Add ATmega_Slow_PWM Library
  repositories.txt
Labels: topic: submission

#1746 Add Dx_TimerInterrupt Library
  repositories.txt
Labels: topic: submission

#1749 Update repositories.txt
  repositories.txt
Labels: topic: submission

#1750 Add Dx_Slow_PWM Library
  repositories.txt
Labels: topic: submission

#1752 Update repositories.txt
  repositories.txt
Labels: topic: submission

#1754 Update repositories.txt
  repositories.txt
Labels: topic: submission

#1755 Add ATtiny_TimerInterrupt Library
  repositories.txt
Labels: topic: submission

#1757 Update repositories.txt
  repositories.txt
Labels: topic: submission

#1759 Update repositories.txt
  repositories.txt
Labels: topic: submission

#1760 Add WebSerialLite Library
  repositories.txt
Labels: topic: submission

#1761 add Adafruit LTR-329 / LTR-303 library
  repositories.txt
Labels: topic: submission

#1763 Add TinyLiquidCrystal_I2C
  repositories.txt
Labels: topic: submission

#1764 Add ATtiny_Slow_PWM Library
  repositories.txt
Labels: topic: submission

#1767 Update repositories.txt
  repositories.txt
Labels: topic: submission

#1768 Add 107-Arduino-APDS-9950 .
  repositories.txt
Labels: topic: submission

#1769 Add I2C_SCANNER class
  repositories.txt
Labels: topic: submission

#1773 Update repositories.txt
  repositories.txt
Labels: topic: submission

#1774 Update repositories.txt
  repositories.txt
Labels: topic: submission

#1777 Adding 'Adafruit_SSD1306_EMULATOR'
  repositories.txt
Labels: topic: submission

#1778 Adding ESP32MSGraph
  repositories.txt
Labels: topic: submission

#1713 Remove VT1100 and VT1300 Libraries
  repositories.txt
Labels: topic: removal, status: pending backend

#1714 Remove "Vertorix_VT1100_Mini" and "VT1300_Shield"
  registry.txt
Labels: topic: removal, status: pending backend

#1731 Remove My Deleted Repository
  repositories.txt
Labels: topic: removal, status: pending backend

#1733 Remove "Simple QR Code"
  registry.txt
Labels: topic: removal, status: pending backend

#1745 Removal of libnapc and libnapc-nightly
  repositories.txt
Labels: topic: removal, status: pending backend

#1747 Remove "libnapc-nightly" and "libnapc"
  registry.txt
Labels: conclusion: resolved, topic: removal, status: pending backend

#1748 Remove TFLM from Arduino library download cache
  repositories.txt
Labels: topic: removal, status: pending backend

#1771 Remove "Arduino_TensorFlowLite"
  registry.txt
Labels: topic: removal, status: pending backend

#1758 Update repositories.txt
  repositories.txt
Labels: topic: removal

#1762 Remove "tasks"
  registry.txt
Labels: topic: removal, status: pending backend

#1779 Add libnapc
  repositories.txt
Labels: topic: submission
