Repository arduino/library-registry, pull requests merged in 2022-03, with the labels that each got.

#1131 Update repositories.txt
  repositories.txt
Labels: topic: submission

#1136 Update repositories.txt
  repositories.txt
Labels: topic: submission

#1137 Update repositories.txt
  repositories.txt
Labels: topic: submission

#1138 Create repositories.txt
  repositories.txt
Labels: topic: submission

#1139 Update repositories.txt
  repositories.txt
Labels: topic: submission

#1144 Update repositories.txt
  repositories.txt
Labels: topic: submission

#1145 Update repositories.txt
  repositories.txt
Labels: topic: submission

#1149 Update repositories.txt
  repositories.txt
Labels: topic: submission

#1141 Remove several akkoyun libraries
  repositories.txt
Labels: topic: removal, status: pending backend

#1142 Remove several akkoyun libraries
  registry.txt
Labels: topic: removal, status: pending backend

#1148 Remove "artemis-arduino"
  registry.txt
Labels: topic: removal, status: pending backend

#1147 Update repositories.txt
  repositories.txt
Labels: topic: removal, status: pending backend

#1087 Rename "I2C_Functions"
  registry.txt
Labels: topic: rename, status: pending backend

#1122 Update name of "MAX78630"
  registry.txt
Labels: topic: rename, status: pending backend

#1126 Updated repositories.txt with new URL
  repositories.txt
Labels: topic: modification, topic: URL change, status: pending backend

#1113 Update URL of "dWin"
  repositories.txt
Labels: topic: modification, topic: URL change, status: pending backend

#1151 Add plageoj/urlencode
  repositories.txt
Labels: topic: submission

#1152 Adding InqOnThat/InqPortal Library
  repositories.txt
Labels: topic: submission

#1153 Update repositories.txt
  repositories.txt
Labels: topic: submission

#1158 Update repositories.txt
  repositories.txt
Labels: topic: submission

#1156 Update repositories.txt
  repositories.txt
Labels: topic: submission

#1161 Update repositories.txt
  repositories.txt
Labels: topic: submission

#1162 Update repositories.txt
  repositories.txt
Labels: topic: submission

#1164 Update repositories.txt
  repositories.txt
Labels: topic: submission

#1166 Update repositories.txt
  repositories.txt
Labels: topic: submission

#1168 library to support application development using mcp23008 i/o expander
  repositories.txt
Labels: topic: submission

#1172 Adding STM32encoder library
  repositories.txt
Labels: topic: submission

#1174 Added my MicroFlow library
  repositories.txt
Labels: topic: submission

#1160 Update URLs of several fabianoriccardi libraries
  registry.txt
Labels: topic: URL change, status: pending backend

#1159 Update repositories.txt
  repositories.txt
Labels: topic: modification, status: pending backend

#1175 Add DEVFULL
  repositories.txt
Labels: topic: submission

#1176 Update repositories.txt
  repositories.txt
Labels: topic: submission

#1177 Update repositories.txt
  repositories.txt
Labels: topic: submission

#1180 Add AsyncMQTT_Generic Library
  repositories.txt
Labels: topic: submission

#1181 Update repositories.txt
  repositories.txt
Labels: topic: submission

#1186 adding STM32ad9833
  repositories.txt
Labels: topic: submission

#1187 M5_IP5209
  repositories.txt
Labels: topic: submission

#1184 Update to using Go 1.17 for registry validator tool
  .github/workflows/assets/validate-registry/go.mod
  .github/workflows/check-go-dependencies-task.yml
  .github/workflows/check-go-task.yml
  .github/workflows/check-registry.yml
  .github/workflows/test-go-integration-task.yml
Labels: type: enhancement, topic: infrastructure

#1179 Update URL of "KONNEKTING Device Library"
  registry.txt
Labels: conclusion: resolved, topic: URL change, status: pending backend

#1178 KONNEKTING library moved to gitlab
  repositories.txt
Labels: topic: modification, topic: URL change, status: pending backend

#1190 Update repositories.txt
  repositories.txt
Labels: topic: submission

#1191 Update repositories.txt
  repositories.txt
Labels: topic: submission

#1192 Update repositories.txt
  repositories.txt
Labels: topic: submission

#1193 Add hideakitai/PCA95x5
  repositories.txt
Labels: topic: submission

#1195 Update repositories.txt
  repositories.txt
Labels: topic: submission

#1196 Update repositories.txt
  repositories.txt
Labels: topic: submission

#1198 Add Teensy41_AsyncTCP Library
  repositories.txt
Labels: topic: submission

#1200 Update repositories.txt, add EEPROM_SPI_WE
  repositories.txt
Labels: topic: submission

#1201 Update repositories.txt
  repositories.txt
Labels: topic: submission

#1202 Add AsyncWebServer_Teensy41 Library
  repositories.txt
Labels: topic: submission

#1203 Add AsyncHTTPRequest_Teensy41 Library
  repositories.txt
Labels: topic: submission

#1204 Add AsyncUDP_Teensy41 Library
  repositories.txt
Labels: topic: submission

#1205 Update repositories.txt
  repositories.txt
Labels: topic: submission

#1206 Update repositories.txt
  repositories.txt
Labels: topic: submission

#1207 Update repositories.txt
  repositories.txt
Labels: topic: submission

#1209 Add italia/cie-PN532
  repositories.txt
Labels: topic: submission

#1211 Add PyArduinoDebug to repositories.txt
  repositories.txt
Labels: topic: submission

#1212 adding of STM32mcp4151
  repositories.txt
Labels: topic: submission

#1213 Update repositories.txt
  repositories.txt
Labels: topic: submission

#1215 Add patricklaf/SNMP
  repositories.txt
Labels: topic: submission

#1217 Update repositories.txt
  repositories.txt
Labels: topic: submission

#1218 Add AsyncDNSServer_Teensy41 Library
  repositories.txt
Labels: topic: submission

#1219 Update repositories.txt
  repositories.txt
Labels: topic: submission

#1220 Add hideakitai/MaxMtrParser
  repositories.txt
Labels: topic: submission

#1223 Update library-registry
  repositories.txt
Labels: topic: submission

#1224 Add SparkFun OLED Graphics library
  repositories.txt
Labels: topic: submission

#1225 Add Camino to repositories.txt
  repositories.txt
Labels: topic: submission

#1227 Add navduino.h
  repositories.txt
Labels: topic: submission

#1228 Update repositories.txt
  repositories.txt
Labels: topic: submission

#1229 Update repositories.txt
  repositories.txt
Labels: topic: submission

#1230 Add MQTTPubSubClient_Generic Library
  repositories.txt
Labels: topic: submission

#1231 Update repositories.txt
  repositories.txt
Labels: topic: submission

#1233 Update repositories.txt
  repositories.txt
Labels: topic: submission

#1234 Update repositories.txt
  repositories.txt
Labels: topic: submission

#1235 Add WaveMix
  repositories.txt
Labels: topic: submission

#1236 Update repositories.txt
  repositories.txt
Labels: topic: submission

#1237 Add Motoron library
  repositories.txt
Labels: topic: submission

#1238 Added Meshtastic-arduino
  repositories.txt
Labels: topic: submission

#1240 Update repositories.txt
  repositories.txt
Labels: topic: submission

#1241 Add /asukiaaa/arduino-XboxSeriesXControllerESP32
  repositories.txt
Labels: topic: submission

#1242 Update repositories.txt
  repositories.txt
Labels: topic: submission

#1245 Update repositories.txt
  repositories.txt
Labels: topic: submission

#1246 Update repositories.txt
  repositories.txt
Labels: topic: submission

#1250 Update repositories.txt
  repositories.txt
Labels: topic: submission

#1251 Remove `notes` field from label configuration file
  .github/label-configuration-files/labels.yml
Labels: topic: infrastructure, topic: other, type: imperfection

#1252 Update repositories.txt
  repositories.txt
Labels: topic: submission

#1253 Add KidMotor V4 library for Arduino IDE
  repositories.txt
Labels: topic: submission
