Repository arduino/library-registry, pull requests merged in 2022-12, with the labels that each got.

#2168 Update repositories.txt
  repositories.txt
Labels: topic: submission

#2096 Update URL of "SIM800_YL"
  registry.txt
Labels: topic: URL change, status: pending backend

#2092 Update changes
  repositories.txt
Labels: topic: modification, topic: URL change, status: pending backend

#2112 Update name of "AbleButtons"
  registry.txt
Labels: topic: rename, status: pending backend

#2123 Update name of "esp32-BG95"
  registry.txt
Labels: topic: rename, status: pending backend

#2171 Add AD56X8 - SPI based 8 channel DAC -library
  repositories.txt
Labels: topic: submission

#2172 Update repositories.txt
  repositories.txt
Labels: topic: submission

#2175 Update repositories.txt
  repositories.txt
Labels: topic: submission

#2177 Add A1301 - Arduino library for A1301 A1302 magnetometer.
  repositories.txt
Labels: topic: submission

#2178 Update repositories.txt
  repositories.txt
Labels: topic: submission

#2181 Add HTTPS_Server_Generic library
  repositories.txt
Labels: topic: submission

#2188 Add RAIN - Arduino library for a rain-sensor
  repositories.txt
Labels: topic: submission

#2191 Update repositories.txt
  repositories.txt
Labels: topic: submission

#2195 Update repositories.txt
  repositories.txt
Labels: topic: submission

#2196 Add AngleConvertor
  repositories.txt
Labels: topic: submission

#2197 Add SparkFun BMA400 and LPS28DFW libraries
  repositories.txt
Labels: topic: submission

#2198 Add AsyncESP32_W5500_Manager library
  repositories.txt
Labels: topic: submission

#2200 Add AsyncWT32_ETH01_Manager library
  repositories.txt
Labels: topic: submission

#2201 Update repositories.txt
  repositories.txt
Labels: topic: submission

#2202 Add AsyncESP8266_W5500_Manager library
  repositories.txt
Labels: topic: submission

#2203 Add AsyncESP8266_ENC_Manager library
  repositories.txt
Labels: topic: submission

#2205 Add AsyncESP8266_W5100_Manager library
  repositories.txt
Labels: topic: submission

#2206 Add ESP32_W5500_Manager library
  repositories.txt
Labels: topic: submission

#2207 Add ESP32_ENC_Manager library
  repositories.txt
Labels: topic: submission

#2208 Add asukiaaa/arduino-ControllerAsI2c
  repositories.txt
Labels: topic: submission

#2210 Add ESP8266_W5500_Manager library
  repositories.txt
Labels: topic: submission

#2213 Add ESP8266_ENC_Manager library
  repositories.txt
Labels: topic: submission

#2214 Add AsyncESP32_Ethernet_Manager library
  repositories.txt
Labels: topic: submission

#2215 Update repositories.txt
  repositories.txt
Labels: topic: submission

#2216 Update repositories.txt
  repositories.txt
Labels: topic: submission

#2218 Added Infineon MOTIX BTN99x0 library to registry
  repositories.txt
Labels: topic: submission

#2174 Update URL of "Arducam_Mega"
  registry.txt
Labels: topic: URL change, status: pending backend

#2173 Update URL of "Arducam_Mega"
  repositories.txt
Labels: topic: modification, status: pending backend

#2176 Update name of "Deneyap Gercek Zamanli Saat"
  registry.txt
Labels: topic: rename, status: pending backend

#2179 removed_pfodGUIdesigner_library
  repositories.txt
Labels: topic: removal, status: pending backend

#2180 Remove "pfodGUIdesigner"
  registry.txt
Labels: topic: removal, status: pending backend

#2190 Update URL of "Excelsior"
  registry.txt
Labels: topic: URL change, status: pending backend

#2194 Update name of "Digital Rain Animation"
  registry.txt
Labels: topic: rename, status: pending backend

#2220 Remove "MOTIX BTN99x0"
  registry.txt
Labels: topic: removal, status: pending backend

#2222 Add AsyncESP8266_Ethernet_Manager library
  repositories.txt
Labels: topic: submission

#2223 Add ESP8266_Ethernet_Manager library
  repositories.txt
Labels: topic: submission

#2225 Update repositories.txt
  repositories.txt
Labels: topic: submission

#2226 Update repositories.txt
  repositories.txt
Labels: topic: submission

#2227 Update repositories.txt
  repositories.txt
Labels: topic: submission

#2232 Add WebServer_ESP32_SC_W5500 library
  repositories.txt
Labels: topic: submission

#2234 Update repositories.txt
  repositories.txt
Labels: topic: submission

#2236 added https://github.com/ug-cp/precise_sntp
  repositories.txt
Labels: topic: submission

#2237 Add WebServer_ESP32_SC_ENC library
  repositories.txt
Labels: topic: submission

#2238 Add PIR library
  repositories.txt
Labels: topic: submission

#2239 Update repositories.txt
  repositories.txt
Labels: topic: submission

#2241 Update repositories.txt
  repositories.txt
Labels: topic: submission

#2242 Update repositories.txt
  repositories.txt
Labels: topic: submission

#2243 Add AsyncESP32_SC_ENC_Manager Library
  repositories.txt
Labels: topic: submission

#2244 Add AsyncESP32_SC_Ethernet_Manager Library
  repositories.txt
Labels: topic: submission

#2245 Add kimballa/button-debounce
  repositories.txt
Labels: topic: submission

#2246 Add the unPhone library
  repositories.txt
Labels: topic: submission

#2247 Add AsyncWebServer_ESP32_SC_W5500 library
  repositories.txt
Labels: topic: submission

#2248 Add AsyncWebServer_ESP32_SC_ENC library
  repositories.txt
Labels: topic: submission

#2249 Add ESP32_SC_W5500_Manager library
  repositories.txt
Labels: topic: submission

#2250 Add ESP32_SC_ENC_Manager library
  repositories.txt
Labels: topic: submission

#2251 Add ESP32_SC_Ethernet_Manager library
  repositories.txt
Labels: topic: submission

#2252 Update repositories.txt
  repositories.txt
Labels: topic: submission

#2253 Add Arduino_HS300x Library
  repositories.txt
Labels: topic: submission

#2257 Update repositories.txt
  repositories.txt
Labels: topic: submission

#2259 Update repositories.txt
  repositories.txt
Labels: topic: submission

#2261 Add AsyncHTTPRequest_ESP32_Ethernet Library
  repositories.txt
Labels: topic: submission

#2264 Add AsyncMQTT_ESP32 library
  repositories.txt
Labels: topic: submission

#2265 Add AsyncHTTPSRequest_ESP32_Ethernet library
  repositories.txt
Labels: topic: submission

#2262 Update repositories.txt
  repositories.txt
Labels: topic: submission

#2274 Update repositories.txt
  repositories.txt
Labels: topic: submission

#2275 Update repositories.txt
  repositories.txt
Labels: topic: submission

#2276 add osap-arduino to library-repository
  repositories.txt
Labels: topic: submission

#2277 Add AsyncUDP_ESP32_SC_W5500 library
  repositories.txt
Labels: topic: submission

#2278 Add AsyncUDP_ESP32_SC_ENC library
  repositories.txt
Labels: topic: submission

#2279 Add AsyncUDP_ESP32_SC_Ethernet library
  repositories.txt
Labels: topic: submission

#2280 Add AsyncDNSServer_ESP32_Ethernet library
  repositories.txt
Labels: topic: submission

#2281 Update repositories.txt
  repositories.txt
Labels: topic: submission

#2282 Update repositories.txt
  repositories.txt
Labels: topic: submission

#2283 Add kimballa/tiny-collections
  repositories.txt
Labels: topic: submission

#2285 Add kimballa/uiwidgets
  repositories.txt
Labels: topic: submission

#2288 Add DMM library
  repositories.txt
Labels: topic: submission

#2272 Update name and URL of "DunogeonFR"
  registry.txt
Labels: topic: URL change, topic: rename, status: pending backend

#2271 Update repositories.txt
  repositories.txt
Labels: topic: modification, status: pending backend

#2256 Update name and URL of "ESP_Ping"
  registry.txt
Labels: topic: URL change, topic: rename, status: pending backend

#2255 change library name
  repositories.txt
Labels: topic: modification, status: pending backend

#2266 Update name of "DunogeonENG"
  registry.txt
Labels: topic: rename, status: pending backend

#2231 Remove "David_Such" libraries
  registry.txt
Labels: topic: removal, status: pending backend

#2224 Update repositories.txt
  repositories.txt
Labels: topic: removal, status: pending backend

#2299 add plageoj/request-builder
  repositories.txt
Labels: topic: submission

#2297 Update repositories.txt
  repositories.txt
Labels: topic: submission

#2300 Update repositories.txt
  repositories.txt
Labels: topic: submission

#2302 Update repositories.txt
  repositories.txt
Labels: topic: submission

#2304 Add fast_math library
  repositories.txt
Labels: topic: submission

#2305 Add pulseInput library
  repositories.txt
Labels: topic: submission

#2306 Arduino Escornabot library to repositories.txt
  repositories.txt
Labels: topic: submission

#2307 Add library
  repositories.txt
Labels: topic: submission

#2308 Update repositories.txt
  repositories.txt
Labels: topic: submission

#2309 Update repositories.txt
  repositories.txt
Labels: topic: submission

#2310 Update repositories.txt
  repositories.txt
Labels: topic: submission

#2311 Add basicCalculus
  repositories.txt
Labels: topic: submission

#2312 Add M5Module-4IN8OUT
  repositories.txt
Labels: topic: submission

#2313 Update repositories.txt
  repositories.txt
Labels: topic: submission

#2315 Add LUHN checksum library
  repositories.txt
Labels: topic: submission

#2316 Update repositories.txt
  repositories.txt
Labels: topic: submission

#2317 Add tcUnicodeHelper to the main repository
  repositories.txt
Labels: topic: submission

#2318 Add AtomicWeight
  repositories.txt
Labels: topic: submission

#2319 Added SFM-V1.7
  repositories.txt
Labels: topic: submission

#2320 Add Eventually plugins
  repositories.txt
Labels: topic: submission

#2321 added my library.
  repositories.txt
Labels: topic: submission

#2322 Add EspUsbHost
  repositories.txt
Labels: topic: submission
