Repository arduino/library-registry, pull requests merged in 2022-01, with the labels that each got.

#851 Update repositories.txt
  repositories.txt
Labels: topic: submission

#852 Update repositories.txt
  repositories.txt
Labels: topic: submission

#853 Update repositories.txt
  repositories.txt
Labels: topic: submission

#854 Update repositories.txt
  repositories.txt
Labels: topic: submission

#855 Add PCA9634 8 channel PWM / led driver
  repositories.txt
Labels: topic: submission

#856 Update repositories.txt
  repositories.txt
Labels: topic: submission

#857 Update repositories.txt
  repositories.txt
Labels: topic: submission

#858 Update repositories.txt
  repositories.txt
Labels: topic: submission

#859 Add Max44007 library
  repositories.txt
Labels: topic: submission

#860 Update repositories.txt
  repositories.txt
Labels: topic: submission

#863 Add MaxEssentialToolkit
  repositories.txt
Labels: topic: submission

#864 Add AM2315 library
  repositories.txt
Labels: topic: submission

#865 Update repositories.txt
  repositories.txt
Labels: topic: submission

#866 Add Adafruit.io WipperSnapper Beta
  repositories.txt
Labels: topic: submission

#861 Update repositories.txt
  repositories.txt
Labels: topic: submission

#869 Update repositories.txt
  repositories.txt
Labels: topic: submission

#870 Submit new Library GU140X32F_7703A
  repositories.txt
Labels: topic: submission

#871 Update repositories.txt
  repositories.txt
Labels: topic: submission

#872 Add MCP23S17 - SPI based 16 channel port expander
  repositories.txt
Labels: topic: submission

#873 Update repositories.txt
  repositories.txt
Labels: topic: submission

#874 ok
  repositories.txt
Labels: topic: submission

#876 Add Tee Log
  repositories.txt
Labels: topic: submission

#877 Update repositories.txt
  repositories.txt
Labels: topic: submission

#879 update
  repositories.txt
Labels: topic: submission

#880 update
  repositories.txt
Labels: topic: submission

#881 Revert "Add submission # 880"
  registry.txt
Labels: topic: removal, type: imperfection

#883 Add Sensirion SEN5x library
  repositories.txt
Labels: topic: submission

#884 Add MCP23S08
  repositories.txt
Labels: topic: submission

#886 add iic to dual uart library.
  repositories.txt
Labels: topic: submission

#889 Update repositories.txt
  repositories.txt
Labels: topic: submission

#890 add mcp23017 moudle
  repositories.txt
Labels: topic: submission

#891 Add new RAKWireless libraries
  repositories.txt
Labels: topic: submission

#892 add bmm150 sensor
  repositories.txt
Labels: topic: submission

#893 Change of url to exiting library
  repositories.txt
Labels: topic: modification

#896 Adding high-side-switch-ino library to register
  repositories.txt
Labels: topic: submission

#897 add two library
  repositories.txt
Labels: topic: submission

#898 add AS3935
  repositories.txt
Labels: topic: submission

#899 Update repositories.txt
  repositories.txt
Labels: topic: submission

#900 Add MCP23008 - 8 channel IO extender
  repositories.txt
Labels: topic: submission

#901 Add DHT20 - I2C temperature and humidity sensor
  repositories.txt
Labels: topic: submission

#902 Add a library for working with Espressif's ESP32 Azure IoT Kit sensors
  repositories.txt
Labels: topic: submission

#903 Update repositories.txt
  repositories.txt
Labels: topic: submission

#907 add Adafruit_InternalFlash
  repositories.txt
Labels: topic: submission

#908 add two library
  repositories.txt
Labels: topic: submission

#909 Add LoRaRF-Arduino library
  repositories.txt
Labels: topic: submission

#911 Adding ArylicHTTP - ESP32 Library for Arylic Audio devices.
  repositories.txt
Labels: topic: submission

#912 Update repositories.txt
  repositories.txt
Labels: topic: submission

#914 Add library for Bosch Sensortec BME280
  repositories.txt
Labels: topic: submission

#915 Add library for Winsen MH-Z19
  repositories.txt
Labels: topic: submission

#913 Update repositories.txt
  repositories.txt
Labels: topic: removal

#917 Update repositories.txt
  repositories.txt
Labels: topic: submission

#919 Update repositories.txt
  repositories.txt
Labels: topic: submission

#920 https://github.com/dirkohme/LED
  repositories.txt
Labels: topic: submission

#921 Add DisplayUtils library
  repositories.txt
Labels: topic: submission

#922 Update repositories.txt
  repositories.txt
Labels: topic: submission

#923 adding bluemicro-hid library to repo list
  repositories.txt
Labels: topic: submission

#847 Update name of "I2C_LCD12864"
  registry.txt
Labels: topic: rename, status: pending backend

#878 Update name of "TinyGPSPlus-ESP32"
  registry.txt
Labels: topic: rename, status: pending backend

#916 Remove "AsyncTelegram"
  registry.txt
Labels: topic: removal, status: pending backend

#895 Update URL of "SDU_CAR"
  registry.txt
Labels: topic: URL change, status: pending backend

#926 Update URL of "Accelerometer And Gyroscope LSM6DS3"
  registry.txt
Labels: topic: URL change, status: pending backend

#906 Update name of "MCP23S17"
  registry.txt
Labels: topic: rename, status: pending backend

#925 Update URL of "Accelerometer And Gyroscope LSM6DS3"
  repositories.txt
Labels: topic: modification

#927 Update repositories.txt
  repositories.txt
Labels: topic: submission

#931 https://github.com/dirkohme/Beeper
  repositories.txt
Labels: topic: submission

#933 Update repositories.txt
  repositories.txt
Labels: topic: submission

#935 Update repositories.txt
  repositories.txt
Labels: topic: submission

#938 Update repositories.txt
  repositories.txt
Labels: topic: submission

#937 Update repositories.txt
  repositories.txt
Labels: topic: submission

#939 Update repositories.txt
  repositories.txt
Labels: topic: submission

#942 Update repositories.txt
  repositories.txt
Labels: topic: submission

#943 Update repositories.txt
  repositories.txt
Labels: topic: submission

#944 Add sourcesimian/uICAL library v0.0.1
  repositories.txt
Labels: topic: submission

#930 Rename "Seeed Arduino LSM6DS3"
  registry.txt
Labels: topic: rename, status: pending backend

#947 Update repositories.txt
  repositories.txt
Labels: topic: submission

#882 Add pixelgrid arduino library to the list.
  repositories.txt
Labels: topic: submission

#948 Add Seeed_Arduino_24GHz_Radar_Sensor library
  repositories.txt
Labels: topic: submission

#952 Update repositories.txt
  repositories.txt
Labels: topic: submission

#953 Added JAREL library
  repositories.txt
Labels: topic: submission

#954 Add TouchKeypad library
  repositories.txt
Labels: topic: submission

#110 Add TinyGPSPlus
  repositories.txt
Labels: topic: submission

#955 Update repositories.txt
  repositories.txt
Labels: topic: submission

#956 Added NoBlockEEPROM library
  repositories.txt
Labels: topic: submission

#960 Add Seeed_Arduino_8Channel_I2C_Hub
  repositories.txt
Labels: topic: submission

#963 Add MS5611_SPI
  repositories.txt
Labels: topic: submission

#962 Update repositories.txt
  repositories.txt
Labels: topic: submission

#964 Update repositories.txt
  repositories.txt
Labels: topic: submission

#965 Update repositories.txt
  repositories.txt
Labels: topic: submission

#966 Update repositories.txt
  repositories.txt
Labels: topic: submission

#967 Add PRDC_ServoHT
  repositories.txt
Labels: topic: submission

#968 Add PRDC_TMAESC
  repositories.txt
Labels: topic: submission

#969 Add PRDC_TMAESC
  repositories.txt
Labels: topic: submission

#971 Add PRDC_AD7194
  repositories.txt
Labels: topic: submission

#972 Update repositories.txt
  repositories.txt
Labels: topic: submission

#973 Add Fletcher checksum
  repositories.txt
Labels: topic: submission

#974 Update repositories.txt
  repositories.txt
Labels: topic: submission

#946 Remove "EdgeML"
  registry.txt
Labels: topic: removal, status: pending backend

#976 Publish 107-Arduino-AS504x for AMS angle position sensors.
  repositories.txt
Labels: topic: submission

#979 Add Adler 32 bit checksum library
  repositories.txt
Labels: topic: submission

#981 Update repositories.txt
  repositories.txt
Labels: topic: submission

#982 Update repositories.txt
  repositories.txt
Labels: topic: submission

#984 Create repositories.txt
  repositories.txt
Labels: topic: submission

#988 Update repositories.txt
  repositories.txt
Labels: topic: submission

#989 Update repositories.txt
  repositories.txt
Labels: topic: submission

#991 Update repositories.txt
  repositories.txt
Labels: topic: submission

#992 Update repositories.txt
  repositories.txt
Labels: topic: submission

#993 Update repositories.txt
  repositories.txt
Labels: topic: submission

#995 Adding LCD library
  repositories.txt
Labels: topic: submission
