Repository arduino/library-registry, pull requests merged in 2022-07, with the labels that each got.

#1553 Update repositories.txt
  repositories.txt
Labels: topic: submission

#1554 Update repositories.txt
  repositories.txt
Labels: topic: submission

#1555 added https://github.com/lpaseen/ht16k33
  repositories.txt
Labels: topic: submission

#1556 Update repositories.txt
  repositories.txt
Labels: topic: submission

#1558 Update repositories.txt and smooth library
  repositories.txt
Labels: topic: submission

#1563 Add electricui-embedded
  repositories.txt
Labels: topic: submission

#1564 Update repositories.txt
  repositories.txt
Labels: topic: submission

#1568 Update repositories.txt
  repositories.txt
Labels: topic: submission

#1569 M5Unit-ENV
  repositories.txt
Labels: topic: submission

#1571 M5Unit-KMeter
  repositories.txt
Labels: topic: submission

#1574 Add ggwave library v0.1.0
  repositories.txt
Labels: topic: submission

#1577 Add M5Unit-MQTT
  repositories.txt
Labels: topic: submission

#1578 M5-DLight
  repositories.txt
Labels: topic: submission

#1582 Update repositories.txt
  repositories.txt
Labels: topic: submission

#1583 M5Core-Ink
  repositories.txt
Labels: topic: submission

#1584 M5Unit-DDS
  repositories.txt
Labels: topic: submission

#1562 Update name of "M5Unit-EXTIO2"
  registry.txt
Labels: topic: rename, status: pending backend

#1566 Update name of "M5Unit-ACSSR"
  registry.txt
Labels: topic: rename, status: pending backend

#1559 Update URL of "ESPLogger"
  repositories.txt
Labels: conclusion: resolved, topic: modification, status: pending backend

#1575 Remove "UNIT_KMeter"
  registry.txt
Labels: topic: removal, status: pending backend

#1572 Delete Unit_KMeter
  repositories.txt
Labels: topic: removal, status: pending backend

#1580 Remove "M5_BH1750FVI"
  registry.txt
Labels: topic: removal, status: pending backend

#1579 Remove M5_BH1750FVI Migrate to M5-DLight
  repositories.txt
Labels: topic: removal, status: pending backend

#1587 add M5Unit-PoESP32
  repositories.txt
Labels: topic: submission

#1586 Sorting the M5Stack repository
  repositories.txt
Labels: topic: modification

#1581 Update repositories.txt
  repositories.txt
Labels: topic: submission

#1588 Update repositories.txt
  repositories.txt
Labels: topic: submission

#1589 Add DRV8825 stepper motor library
  repositories.txt
Labels: topic: submission

#1591 Add MegunoLink FileManager library for Arduino
  repositories.txt
Labels: topic: submission

#1592 Update repositories.txt
  repositories.txt
Labels: topic: submission

#1594 add https://github.com/adafruit/Adafruit_MMC56x3
  repositories.txt
Labels: topic: submission

#1595 add https://github.com/adafruit/Adafruit_PCF8574
  repositories.txt
Labels: topic: submission

#1596 Add Blues Wireless Notecard Auxiliary Wi-Fi
  repositories.txt
Labels: topic: submission

#1598 M5-ADS1115
  repositories.txt
Labels: topic: submission

#1599 Update repositories.txt
  repositories.txt
Labels: topic: submission

#1600 M5-ADS1100 & M5Unit-Encoder
  repositories.txt
Labels: topic: submission

#1603 Add mcp9808_arduino_driver to library-registry
  repositories.txt
Labels: topic: submission

#1608 Update repositories.txt - avr-iot-cellular
  repositories.txt
Labels: topic: submission

#1609 Update repositories.txt
  repositories.txt
Labels: topic: submission

#1610 Update repositories.txt
  repositories.txt
Labels: topic: submission

#1611 Add SparseMatrix library
  repositories.txt
Labels: topic: submission

#1590 Remove "M5-CoreInk"
  registry.txt
Labels: conclusion: resolved, topic: removal, status: pending backend

#1604 Remove "AccelStepperI2C"
  registry.txt
Labels: topic: removal, status: pending backend

#1606 Rename "AVR-IoT MCP9808"
  registry.txt
Labels: topic: rename, status: pending backend

#1613 Update repositories.txt
  repositories.txt
Labels: topic: submission

#1614 Update repositories.txt
  repositories.txt
Labels: topic: submission

#1615 Update repositories.txt
  repositories.txt
Labels: topic: submission

#1620 Add SparkFun BMP581 Library
  repositories.txt
Labels: topic: submission

#1621 Update repositories.txt
  repositories.txt
Labels: topic: submission

#1622 M5Unit-RTC
  repositories.txt
Labels: topic: submission

#1624 Publish Arduino_Threads.
  repositories.txt
Labels: topic: submission

#1625 Add ESPWiFiMqttWrapper
  repositories.txt
Labels: topic: submission

#1626 Add SparseArray library
  repositories.txt
Labels: topic: submission

#1627 Add Deneyap GPS and GLONASS Locator
  repositories.txt
Labels: topic: submission

#1619 Rename "AVR-IoT VEML3328"
  registry.txt
Labels: topic: rename, status: pending backend

#1617 Rename "AVR-IoT-Cellular"
  registry.txt
Labels: topic: rename, status: pending backend

#1628 Update repositories.txt
  repositories.txt
Labels: topic: submission

#1629 Update repositories.txt
  repositories.txt
Labels: topic: submission

#1630 Add Sensirion SCD30 I2C driver
  repositories.txt
Labels: topic: submission

#1632 Update repositories.txt
  repositories.txt
Labels: topic: submission

#1635 M5Unit-Sonic
  repositories.txt
Labels: topic: submission

#1637 M5Unit-UHF-RFID
  repositories.txt
Labels: topic: submission

#1638 M5-FPC1020A
  repositories.txt
Labels: topic: submission

#1641 M5Unit-4RELAY
  repositories.txt
Labels: topic: submission

#1645 Update repositories.txt
  repositories.txt
Labels: topic: submission

#1646 Add easyConfig lib
  repositories.txt
Labels: topic: submission

#1647 Update repositories.txt
  repositories.txt
Labels: topic: submission

#1651 Update repositories.txt
  repositories.txt
Labels: topic: submission

#1652 Added ESP32_BleSerial
  repositories.txt
Labels: topic: submission

#1653 Update repositories.txt
  repositories.txt
Labels: topic: submission

#1655 Add ellipse library
  repositories.txt
Labels: topic: submission

#1656 Add LSM6DSV16X and LIS2DU12 for stm32duino
  repositories.txt
Labels: topic: submission

#1657 Update repositories.txt
  repositories.txt
Labels: topic: submission

#1658 DS1624 Library
  repositories.txt
Labels: topic: submission

#1659 Update repositories.txt
  repositories.txt
Labels: topic: submission

#1660 Update repositories.txt
  repositories.txt
Labels: topic: submission

#1661 Update repositories.txt
  repositories.txt
Labels: topic: submission

#1662 Add "hellschreiberlib" library
  repositories.txt
Labels: topic: submission

#1663 M5Unit-CatM
  repositories.txt
Labels: topic: submission

#1664 Update repositories.txt
  repositories.txt
Labels: topic: submission

#1665 Adding the ESPboy library
  repositories.txt
Labels: topic: submission

#1666 Update repositories.txt
  repositories.txt
Labels: topic: submission

#1667 Update repositories.txt
  repositories.txt
Labels: topic: submission
