Repository arduino/library-registry, pull requests merged in 2022-11, with the labels that each got.

#2040 Added https://github.com/botletics/Botletics-SIM7000.
  repositories.txt
Labels: topic: submission

#2042 [Library Manager] Add ESP32_FastPWM library
  repositories.txt
Labels: topic: submission

#2043 new library ILI9341_T4
  repositories.txt
Labels: topic: submission

#2015 Adding duktape library for arduino
  repositories.txt
Labels: topic: submission

#2044 Add library of CHS-MSS
  repositories.txt
Labels: topic: submission

#2045 Add library of CHS-UPS, CHS-UPR, CHS-UGS, CHS-UGR
  repositories.txt
Labels: topic: submission

#2049 Added I2CIP
  repositories.txt
Labels: topic: submission

#2052 [Library Manager] Add SAMD_PWM library
  repositories.txt
Labels: topic: submission

#2056 [Library Manager] Add SAMDUE_PWM library
  repositories.txt
Labels: topic: submission

#2058 Add FastShiftInOut
  repositories.txt
Labels: topic: submission

#2059 [Library Manager] Add nRF52_PWM library
  repositories.txt
Labels: topic: submission

#2060 Update repositories.txt
  repositories.txt
Labels: topic: submission

#2061 Added MPU6050_IND library to the list
  repositories.txt
Labels: topic: submission

#2062 [Library Manager] Add Teensy_PWM library
  repositories.txt
Labels: topic: submission

#2063 Update repositories.txt
  repositories.txt
Labels: topic: submission

#2073 Add library of TMP9A00-EP
  repositories.txt
Labels: topic: submission

#2074 Add library of LM50C, LM50-Q1
  repositories.txt
Labels: topic: submission

#2075 Add library of LM50B
  repositories.txt
Labels: topic: submission

#2076 Add library of LM45B, LM45C
  repositories.txt
Labels: topic: submission

#2077 Add library of LM35D
  repositories.txt
Labels: topic: submission

#2078 Add library of LM35C, LM35CA
  repositories.txt
Labels: topic: submission

#2079 [Library Manager] Add ATtiny_PWM library
  repositories.txt
Labels: topic: submission

#2080 Add library of LM35, LM35A
  repositories.txt
Labels: topic: submission

#2081 Add ESP32-compatible MagStripe Library
  repositories.txt
Labels: topic: submission

#2082 Update repositories.txt
  repositories.txt
Labels: topic: submission

#2016 Update URL of "RTC_RX8025T"
  registry.txt
Labels: topic: URL change, status: pending backend

#2014 Update repositories.txt
  repositories.txt
Labels: topic: modification

#2023 Update name of "XENSIV PAS CO2"
  registry.txt
Labels: topic: rename, status: pending backend

#2026 Update name and URL of "ERa"
  registry.txt
Labels: topic: URL change, topic: rename, status: pending backend

#2024 Update repositories.txt
  repositories.txt
Labels: topic: modification, topic: URL change, status: pending backend

#2055 Update URLs of An7orAhmed libraries
  registry.txt
Labels: topic: URL change, status: pending backend

#2054 Update name and URL of "OSS-EC_TDK_CHS-UPS_UPR_UGS_UGR_00000057"
  registry.txt
Labels: topic: URL change, topic: rename, status: pending backend

#2064 Update URL of "OSS-EC_TDK_CHS-UPS_UPR_UGS_UGR_00000057"
  repositories.txt
Labels: topic: modification, topic: URL change, status: pending backend

#2083 Update repositories.txt
  repositories.txt
Labels: topic: submission

#2084 Update repositories.txt
  repositories.txt
Labels: topic: submission

#2087 [LIbrary Manager] Add Dx_PWM library
  repositories.txt
Labels: topic: submission

#2086 Update Change
  repositories.txt
Labels: topic: submission

#2088 Update change repository
  repositories.txt
Labels: topic: submission

#2090 Update change
  repositories.txt
Labels: topic: submission

#2097 Update repositories.txt
  repositories.txt
Labels: topic: submission

#2098 Update repositories.txt
  repositories.txt
Labels: topic: submission

#2101 dht11esp8266new
  repositories.txt
Labels: topic: submission

#2105 Update repositories.txt
  repositories.txt
Labels: topic: submission

#2106 Update repositories.txt
  repositories.txt
Labels: topic: submission

#2107 Update repositories.txt
  repositories.txt
Labels: topic: submission

#2108 Update repositories.txt
  repositories.txt
Labels: topic: submission

#2110 Update repositories.txt
  repositories.txt
Labels: topic: submission

#2113 adding https://github.com/tobozo/WiFiManagerTz
  repositories.txt
Labels: topic: submission

#2114 Add MAX31850
  repositories.txt
Labels: topic: submission

#2095 Adds ENS160 Arduino LIbrary (Again)
  repositories.txt
Labels: topic: submission

#2115 [Library Manager] Add WiFi101_Generic library
  repositories.txt
Labels: topic: submission

#2116 adaptive mapping repo
  repositories.txt
Labels: topic: submission

#2117 Adds repository esp32-BG95
  repositories.txt
Labels: topic: submission

#2120 Add asukiaaa/arduino-XboxSeriesXHIDReportBuilder
  repositories.txt
Labels: topic: submission

#2124 Update repositories.txt
  repositories.txt
Labels: topic: submission

#2125 Update repositories.txt
  repositories.txt
Labels: topic: submission

#2126 Update repositories.txt
  repositories.txt
Labels: topic: submission

#2127 Add PCA9557 lib
  repositories.txt
Labels: topic: submission

#2130 Added ATC_MiThermometer
  repositories.txt
Labels: topic: submission

#2132 Update repositories.txt
  repositories.txt
Labels: topic: submission

#2133 Update repositories.txt
  repositories.txt
Labels: topic: submission

#2138 Update repositories.txt
  repositories.txt
Labels: topic: submission

#2139 Update repositories.txt
  repositories.txt
Labels: topic: submission

#2140 Update repositories.txt
  repositories.txt
Labels: topic: submission

#2141 Added library for paperd.ink devices
  repositories.txt
Labels: topic: submission

#2142 Please add Callmebot-ESP32 to Library Manager
  repositories.txt
Labels: topic: submission

#2143 Add library for TSL260R IR to voltage sensor
  repositories.txt
Labels: topic: submission

#2144 Update repositories.txt
  repositories.txt
Labels: topic: submission

#2137 Update repositories.txt
  repositories.txt
Labels: topic: submission

#2145 Update repositories.txt
  repositories.txt
Labels: topic: submission

#2146 Add AsyncWebServer_ESP32_ENC Library
  repositories.txt
Labels: topic: submission

#2147 Add WebServer_ESP32_ENC library
  repositories.txt
Labels: topic: submission

#2148 Update repositories.txt
  repositories.txt
Labels: topic: submission

#2149 Update repositories.txt
  repositories.txt
Labels: topic: submission

#2150 Add AsyncUdp_ESP32_ENC library
  repositories.txt
Labels: topic: submission

#2151 Add AsyncDNSServer_ESP32_ENC Library
  repositories.txt
Labels: topic: submission

#2152 Add AsyncDNSServer_WT32_ETH01 library
  repositories.txt
Labels: topic: submission

#2153 Update repositories.txt
  repositories.txt
Labels: topic: submission

#2155 Adding a library to Library Manager
  repositories.txt
Labels: topic: submission

#2158 Add WebServer_ESP32_W5500 Library
  repositories.txt
Labels: topic: submission

#2159 Add AsyncWebServer_ESP32_W5500 Library
  repositories.txt
Labels: topic: submission

#2160 Adding TinyConsole library
  repositories.txt
Labels: topic: submission

#2161 Update repositories.txt
  repositories.txt
Labels: topic: submission

#2162 Update repositories.txt
  repositories.txt
Labels: topic: submission

#2163 Add AsyncUDP_ESP32_W5500 library
  repositories.txt
Labels: topic: submission

#2165 Add AsyncDNSServer_ESP32_W5500 library
  repositories.txt
Labels: topic: submission

#2166 Update repositories.txt
  repositories.txt
Labels: topic: submission
