Repository arduino/library-registry, pull requests merged in 2023-12, with the labels that each got.

#3677 Add m95-eeprom-arduino
  repositories.txt
Labels: topic: submission

#3683 Update repositories.txt
  repositories.txt
Labels: topic: submission

#3688 Update repositories.txt
  repositories.txt
Labels: topic: submission

#3689 Update repositories.txt
  repositories.txt
Labels: topic: submission

#3690 Update repositories.txt
  repositories.txt
Labels: topic: submission

#3691 Update repositories.txt
  repositories.txt
Labels: topic: submission

#3693 Added roo_display.
  repositories.txt
Labels: topic: submission

#3694 Added roo_material_icons.
  repositories.txt
Labels: topic: submission

#3700 Update repositories.txt
  repositories.txt
Labels: topic: submission

#3702 Update repositories.txt
  repositories.txt
Labels: topic: submission

#3710 Update repositories.txt
  repositories.txt
Labels: topic: submission

#3711 Add DCCEXProtocol
  repositories.txt
Labels: topic: submission

#3671 Update name of "PDLS_EXT3_Basic_Global"
  registry.txt
Labels: topic: rename, status: pending backend

#3707 Update name and URL of "DirectCurrent_Motor_Module"
  registry.txt
Labels: topic: URL change, topic: rename, status: pending backend

#3706 Update URL of "DirectCurrent Motor Module"
  repositories.txt
Labels: topic: modification

#3692 Update repositories.txt
  repositories.txt
Labels: topic: URL change, status: pending backend

#3703 Update URL of "tdslite"
  registry.txt
Labels: topic: URL change, status: pending backend

#3699 Update URL of "tdslite"
  repositories.txt
Labels: topic: URL change, status: pending backend

#3687 Update URL of "IoT_Modules-Buttons"
  registry.txt
Labels: topic: URL change, status: pending backend

#3686 Update URL of "IoT_Modules-Buttons" in repository list
  repositories.txt
Labels: topic: URL change, status: pending backend

#3712 Add ATD3.5-S3 Library
  repositories.txt
Labels: topic: submission

#3716 Update repositories.txt
  repositories.txt
Labels: topic: submission

#3717 Update repositories.txt
  repositories.txt
Labels: topic: submission

#3718 Update repositories.txt
  repositories.txt
Labels: topic: submission

#3715 Update repositories.txt
  repositories.txt
Labels: topic: submission

#3719 Update repositories.txt
  repositories.txt
Labels: topic: submission

#3721 Update repositories.txt
  repositories.txt
Labels: topic: submission

#3722 Add MQTT_Looped Library
  repositories.txt
Labels: topic: submission

#3723 Update repositories.txt
  repositories.txt
Labels: topic: submission

#3726 Update repositories.txt
  repositories.txt
Labels: topic: submission

#3725 https://github.com/Sam4uk/CRSF
  repositories.txt
Labels: topic: submission

#3727 Added MultiFuncShield Library
  repositories.txt
Labels: topic: submission

#3728 Add Arduino_PF1550 to library index.
  repositories.txt
Labels: topic: submission

#3729 Update repositories.txt
  repositories.txt
Labels: topic: submission

#3734 add M5StickCPlus2 lib
  repositories.txt
Labels: topic: submission

#3736 MySQL Arduino Clients
  repositories.txt
Labels: topic: submission

#3737 Update repositories.txt
  repositories.txt
Labels: topic: submission

#3739 RTC_RX8025NB Library
  repositories.txt
Labels: topic: submission

#3740 Update repositories.txt
  repositories.txt
Labels: topic: submission

#3741 Update repositories.txt
  repositories.txt
Labels: topic: submission

#3742 Update repositories.txt
  repositories.txt
Labels: topic: submission

#3744 Add SparkFun AS7331 Arduino Library
  repositories.txt
Labels: topic: submission

#3745 Added FlexWire library
  repositories.txt
Labels: topic: submission

#3748 Add SparkFun UM980 library
  repositories.txt
Labels: topic: submission

#3752 Update repositories.txt
  repositories.txt
Labels: topic: submission

#3754 Update repositories.txt
  repositories.txt
Labels: topic: submission

#3755 Update repositories.txt
  repositories.txt
Labels: topic: submission

#3757 add Adafruit MCP3421
  repositories.txt
Labels: topic: submission

#3758 add Adafruit_xCA9554
  repositories.txt
Labels: topic: submission

#3759 Add I2C_LCD library
  repositories.txt
Labels: topic: submission

#3762 Added more roo libraries.
  repositories.txt
Labels: topic: submission

#3763 Update repositories.txt
  repositories.txt
Labels: topic: submission

#3764 Update repositories.txt
  repositories.txt
Labels: topic: submission

#3765 Adding Adafruit_PyCamera library
  repositories.txt
Labels: topic: submission

#3770 Update repositories.txt
  repositories.txt
Labels: topic: submission

#3772 Update repositories.txt
  repositories.txt
Labels: topic: submission

#3773 Update repositories.txt with ArduboyRaycast
  repositories.txt
Labels: topic: submission

#3776 Add LilyGo-AMOLED-Series lib
  repositories.txt
Labels: topic: submission

#3779 Update repositories.txt
  repositories.txt
Labels: topic: submission

#3781 add lib
  repositories.txt
Labels: topic: submission

#3782 Add SparkFun Qwiic Ultrasonic Library
  repositories.txt
Labels: topic: submission

#3785 Update repositories.txt
  repositories.txt
Labels: topic: submission

#3786 Update repositories.txt
  repositories.txt
Labels: topic: submission

#3787 add lib
  repositories.txt
Labels: topic: submission

#3789 Update repositories.txt
  repositories.txt
Labels: topic: submission

#3790 Add json2asw-arduino library
  repositories.txt
Labels: topic: submission

#3793 Update repositories.txt
  repositories.txt
Labels: topic: submission

#3794 Update repositories.txt
  repositories.txt
Labels: topic: submission

#3799 Adding NuS-NimBLE-Serial
  repositories.txt
Labels: topic: submission

#3795 Update repositories.txt
  repositories.txt
Labels: topic: submission

#3802 OtaHelper library
  repositories.txt
Labels: topic: submission

#3784 Update name of "LilyGo-AMOLED-Series"
  registry.txt
Labels: topic: rename, status: pending backend

#3760 Update name and URL of "nodepp"
  registry.txt
Labels: topic: URL change, topic: rename, status: pending backend

#3756 Update repositories.txt
  repositories.txt
Labels: topic: URL change, status: pending backend

#3804 Update repositories.txt
  repositories.txt
Labels: topic: submission

#3810 Update repositories.txt
  repositories.txt
Labels: topic: submission

#3811 Add KT0803 library
  repositories.txt
Labels: topic: submission

#3812 Add MT6701 library to repositories.txt
  repositories.txt
Labels: topic: submission

#3805 EloquentTensorFlowCortexM
  repositories.txt
Labels: topic: submission

#3814 Update repositories.txt
  repositories.txt
Labels: topic: submission

#3816 Update repositories.txt
  repositories.txt
Labels: topic: submission

#3815 add qlibs
  repositories.txt
Labels: topic: submission

#3817 Add SmallRTC library.
  repositories.txt
Labels: topic: submission

#3818 Update repositories.txt
  repositories.txt
Labels: topic: submission

#3819 Update repositories.txt
  repositories.txt
Labels: topic: submission

#3820 Add Bind UI library
  repositories.txt
Labels: topic: submission

#3824 Added PxServ IoT Library
  repositories.txt
Labels: topic: submission

#3825 Added roo_icons.
  repositories.txt
Labels: topic: submission

#3826 Update repositories.txt
  repositories.txt
Labels: topic: submission

#3827 Update repositories.txt
  repositories.txt
Labels: topic: submission

#3828 Update repositories.txt with karol-brejna-i/RemoteDebug
  repositories.txt
Labels: topic: submission
