Repository arduino/library-registry, pull requests merged in 2023-03, with the labels that each got.

#2523 Add `Arduino_AdvancedAnalog` library.
  repositories.txt
Labels: topic: submission

#2524 Adding X-NUCLEO-53L7A1 examples
  repositories.txt
Labels: topic: submission

#2525 Update repositories.txt
  repositories.txt
Labels: topic: submission

#2526 Add UM7.h
  repositories.txt
Labels: topic: submission

#2527 Update repositories.txt
  repositories.txt
Labels: topic: submission

#2528 Update repositories.txt with mqtt5nano
  repositories.txt
Labels: topic: submission

#2530 Add esp8266channel3lib
  repositories.txt
Labels: topic: submission

#2531 Add africastalking-esp8266 link to repositories.txt
  repositories.txt
Labels: topic: submission

#2532 Add ESP-WebOTA
  repositories.txt
Labels: topic: submission

#2533 Added afpineda/MeanAndVarOnTheFly-Arduino
  repositories.txt
Labels: topic: submission

#2534 Update repositories.txt
  repositories.txt
Labels: topic: submission

#2535 Added my HUSB238 library
  repositories.txt
Labels: topic: submission

#2536 Update repositories.txt
  repositories.txt
Labels: topic: submission

#2522 added Deneyap Arduino Projeleri library
  repositories.txt
Labels: topic: submission

#2538 Add USBHostMbed5 to library index.
  repositories.txt
Labels: topic: submission

#2540 Add PD243x-DotMatrixDisplay to library index
  repositories.txt
Labels: topic: submission

#2539 Update repositories.txt
  repositories.txt
Labels: topic: submission

#2541 added Flinders ENGR2781 library
  repositories.txt
Labels: topic: submission

#2542 Update respositories.txt with AcksenPump Library
  repositories.txt
Labels: topic: submission

#2543 Update repositories.txt
  repositories.txt
Labels: topic: submission

#2544 Add asynchronous DHT Sensor reading library.
  repositories.txt
Labels: topic: submission

#2546 Add Arduino AlPlc_Opta library
  repositories.txt
Labels: topic: submission

#2547 Add Arduino AlPlc_PMC library
  repositories.txt
Labels: topic: submission

#2551 Update with AcksenButton, AcksenIntEEPROM, AcksenUtils
  repositories.txt
Labels: topic: submission

#2553 Update repositories.txt
  repositories.txt
Labels: topic: submission

#2555 Add PicoDVI - Adafruit Fork
  repositories.txt
Labels: topic: submission

#2556 Update repositories.txt
  repositories.txt
Labels: topic: submission

#2557 Update repositories.txt
  repositories.txt
Labels: topic: submission

#2558 Update respoitories.txt with fANSI
  repositories.txt
Labels: topic: submission

#2559 Add HX711_MP library with multi point calibration
  repositories.txt
Labels: topic: submission

#2560 Update repositories.txt
  repositories.txt
Labels: topic: submission

#2562 Update repositories.txt
  repositories.txt
Labels: topic: submission

#2564 Add https://github.com/leftCoast/LC_slowServo
  repositories.txt
Labels: topic: submission

#2565 M5Unit-GLASS
  repositories.txt
Labels: topic: submission

#2566 Add `tdslite` MSSQL connector library
  repositories.txt
Labels: topic: submission

#2567 Request to include EgoSmartHeaterRS485 library
  repositories.txt
Labels: topic: submission

#2568 Add SimpleDCMotor library
  repositories.txt
Labels: topic: submission

#2569 Update repositories.txt
  repositories.txt
Labels: topic: submission

#2570 Update repositories.txt
  repositories.txt
Labels: topic: submission

#2550 Update name and URL of "Arduino_USBHostMbed5"
  registry.txt
Labels: topic: URL change, topic: rename, status: pending backend

#2549 Update URL of "Arduino_USBHostMbed5"
  repositories.txt
Labels: topic: modification

#2572 Add OrientalCommon_asukiaaa
  repositories.txt
Labels: topic: submission

#2575 Update repositories.txt
  repositories.txt
Labels: topic: submission

#2576 Add hsmcpp library to registry
  repositories.txt
Labels: topic: submission

#2578 Added library for MS5540C pressure sensor
  repositories.txt
Labels: topic: submission

#2579 Add joystick_5pin library
  repositories.txt
Labels: topic: submission

#2584 adding my first library a gps based lap timer
  repositories.txt
Labels: topic: submission

#2585 Add TcBUTTON
  repositories.txt
Labels: topic: submission

#2587 Add omnicrystal library
  repositories.txt
Labels: topic: submission

#2586 Add Deneyap Color Converter Arduino Library
  repositories.txt
Labels: topic: submission

#2589 Update repositories.txt
  repositories.txt
Labels: topic: submission

#2590 Update repositories.txt
  repositories.txt
Labels: topic: submission

#2591 Add "Mozzi"
  repositories.txt
Labels: topic: submission

#2595 Update repositories.txt
  repositories.txt
Labels: topic: submission

#2581 Update name of "RoomWeather"
  registry.txt
Labels: topic: rename, status: pending backend

#2582 Update URL of "HeliOS"
  registry.txt
Labels: topic: URL change, status: pending backend

#2580 Update repositories.txt
  repositories.txt
Labels: topic: modification, status: pending backend

#2599 Add 107-Arduino-24LCxx to the library index.
  repositories.txt
Labels: topic: submission

#2601 Adding 107-Arduino-littlefs to library index.
  repositories.txt
Labels: topic: submission

#2602 library for teknikio bluebird
  repositories.txt
Labels: topic: submission

#2606 Update repositories.txt
  repositories.txt
Labels: topic: submission

#2608 Add ESPMagicHome
  repositories.txt
Labels: topic: submission

#2600 "Nanit" Robot Education Kit
  repositories.txt
Labels: topic: submission

#2609 Add SHT31_SW
  repositories.txt
Labels: topic: submission

#2610 Add eccentricOrange/DDBot
  repositories.txt
Labels: topic: submission

#2611 add em4095 lib
  repositories.txt
Labels: topic: submission

#2607 Update repositories.txt
  repositories.txt
Labels: type: enhancement, topic: other

#2619 Update repositories.txt
  repositories.txt
Labels: topic: submission

#2624 Update repositories.txt
  repositories.txt
Labels: topic: submission

#2629 Update repositories.txt
  repositories.txt
Labels: topic: submission

#2632 Please add my 2 repo into the list
  repositories.txt
Labels: topic: submission

#2625 Update name and URL of "Firmetix"
  registry.txt
Labels: topic: URL change, topic: rename, status: pending backend

#2622 RENAMED Firmetix4Arduino to Firmetix-Library
  repositories.txt
Labels: topic: modification, status: pending backend

#2604 Remove "MyIoT library"
  registry.txt
Labels: topic: removal, status: pending backend

#2598 Update repositories.txt
  repositories.txt
Labels: topic: removal

#2637 Adding a port of the SCPI Parser library
  repositories.txt
Labels: topic: submission

#2638 Publishes Improv-WiFi-Library
  repositories.txt
Labels: topic: submission

#2640 Add Melopero_Cookie_RP2040_Arduino_Library
  repositories.txt
Labels: topic: submission
