Repository arduino/library-registry, pull requests merged in 2023-10, with the labels that each got.

#3409 Update repositories.txt
  repositories.txt
Labels: topic: submission

#3410 Update repositories.txt
  repositories.txt
Labels: topic: submission

#3413 Update repositories.txt
  repositories.txt
Labels: topic: submission

#3414 Update repositories.txt
  repositories.txt
Labels: topic: submission

#3415 My new library
  repositories.txt
Labels: topic: submission

#3416 Update repositories.txt
  repositories.txt
Labels: topic: submission

#3417 Adding MaffooClock/ESP32RotaryEncoder
  repositories.txt
Labels: topic: submission

#3418 Added PreferencesCLI
  repositories.txt
Labels: topic: submission

#3419 Update repositories.txt
  repositories.txt
Labels: topic: submission

#3420 Update repositories.txt
  repositories.txt
Labels: topic: submission

#3421 Update repositories.txt
  repositories.txt
Labels: topic: submission

#3423 Added zvonler/DebouncedButton
  repositories.txt
Labels: topic: submission

#3395 Update URL of "ThingsBoard"
  registry.txt
Labels: topic: URL change, status: pending backend

#3389 ThingsBoard client SDK repository name updated
  repositories.txt
Labels: topic: modification, topic: URL change, status: pending backend

#3412 Update URL of "Boho" and "RemoteSignal"
  registry.txt
Labels: topic: URL change, status: pending backend

#3411 Update repositories.txt
  repositories.txt
Labels: topic: modification, topic: URL change, status: pending backend

#3373 Update URL of "micro_ros_kaia"
  registry.txt
Labels: topic: URL change, status: pending backend

#3424 Update repositories.txt
  repositories.txt
Labels: topic: submission

#3426 [Library Manager] Please add library ESP32WebRemoteControl
  repositories.txt
Labels: topic: submission

#3427 Update repositories.txt
  repositories.txt
Labels: topic: submission

#3429 Add Arduino_GigaDisplay_TinyGL
  repositories.txt
Labels: topic: submission

#3430 Update repositories.txt
  repositories.txt
Labels: topic: submission

#3431 Update repositories.txt
  repositories.txt
Labels: topic: submission

#3432 Update repositories.txt
  repositories.txt
Labels: topic: submission

#3433 Update repositories.txt
  repositories.txt
Labels: topic: submission

#3435 Update repositories.txt
  repositories.txt
Labels: topic: submission

#3436 add M5Capsule lib
  repositories.txt
Labels: topic: submission

#3437 Update repositories.txt
  repositories.txt
Labels: topic: submission

#3440 Update repositories.txt
  repositories.txt
Labels: topic: submission

#3438 Add kikuchan/pngle
  repositories.txt
Labels: topic: submission

#3441 Update repositories.txt
  repositories.txt
Labels: topic: submission

#3442 Add AD5263
  repositories.txt
Labels: topic: submission

#3443 add M5Cardputer lib
  repositories.txt
Labels: topic: submission

#3444 Add `Arduino_ScienceKitCarrier`
  repositories.txt
Labels: topic: submission

#3445 adding Adafruit_VCNL4020
  repositories.txt
Labels: topic: submission

#3447 Update repositories.txt
  repositories.txt
Labels: topic: submission

#3448 Added zvonler/CircuitPlaygroundGestures
  repositories.txt
Labels: topic: submission

#3450 Update repositories.txt
  repositories.txt
Labels: topic: submission

#3451 Update repositories.txt
  repositories.txt
Labels: topic: submission

#3452 Update repositories.txt
  repositories.txt
Labels: topic: submission

#3453 Update repositories.txt
  repositories.txt
Labels: topic: submission

#3454 Update repositories.txt
  repositories.txt
Labels: topic: submission

#3457 Update repositories.txt
  repositories.txt
Labels: topic: submission

#3459 adding the AITINKR SHEILDS library
  repositories.txt
Labels: topic: submission

#3464 Update repositories.txt
  repositories.txt
Labels: topic: submission

#3465 Update repositories.txt
  repositories.txt
Labels: topic: submission

#3466 Update repositories.txt
  repositories.txt
Labels: topic: submission

#3469 Update repositories.txt
  repositories.txt
Labels: topic: submission

#3470 Update repositories.txt
  repositories.txt
Labels: topic: submission

#3471 Update repositories.txt
  repositories.txt
Labels: topic: submission

#3472 Update repositories.txt
  repositories.txt
Labels: topic: submission

#3462 Update name and URL of "AITINKR_SHIELDS"
  registry.txt
Labels: topic: URL change, topic: rename, status: pending backend

#3458 Update URL of "VernierLib"
  registry.txt
Labels: topic: URL change, status: pending backend

#3456 Update repositories.txt
  repositories.txt
Labels: topic: URL change, status: pending backend

#3477 Added AITINKR AIOT DEVBOARD library
  repositories.txt
Labels: topic: submission

#3478 add M5-LoRa-E220-JP lib
  repositories.txt
Labels: topic: submission

#3480 Update repositories.txt
  repositories.txt
Labels: topic: submission

#3481 Update repositories.txt
  repositories.txt
Labels: topic: submission

#3482 Add LEDuino to repositories.txt
  repositories.txt
Labels: topic: submission

#3484 Update repositories.txt
  repositories.txt
Labels: topic: submission

#3483 Update repositories.txt
  repositories.txt
Labels: topic: submission

#3485 Added CSE_ModbusRTU Library
  repositories.txt
Labels: topic: submission

#3488 Update repositories.txt
  repositories.txt
Labels: topic: submission

#3491 Update repositories.txt
  repositories.txt
Labels: topic: submission

#3492 Add RPulse
  repositories.txt
Labels: topic: submission

#3495 Update repositories.txt
  repositories.txt
Labels: topic: submission

#3496 Update repositories.txt
  repositories.txt
Labels: topic: submission

#3498 esp32-modem-freeRTOS
  repositories.txt
Labels: topic: submission

#3500 library submission: tmc5072
  repositories.txt
Labels: topic: submission

#3504 Update repositories.txt
  repositories.txt
Labels: topic: submission

#3506 Update repositories.txt
  repositories.txt
Labels: topic: submission

#3507 Update repositories.txt
  repositories.txt
Labels: topic: submission

#3510 Update repositories.txt
  repositories.txt
Labels: topic: submission

#3511 Update repositories.txt
  repositories.txt
Labels: topic: submission

#3512 Add Adafruit_INA228
  repositories.txt
Labels: topic: submission

#3475 Update name of "Cpp_Standard_Library"
  registry.txt
Labels: topic: rename, status: pending backend

#3494 Update name of "PTSolns_I2CBackpack"
  registry.txt
Labels: topic: rename, status: pending backend

#3490 Update name and URL of "SimpleControl"
  registry.txt
Labels: topic: URL change, topic: rename, status: pending backend

#3489 updated library url
  repositories.txt
Labels: topic: URL change, status: pending backend

#3514 Add porcupine-FA and picovoice-FA
  repositories.txt
Labels: topic: submission

#3517 Update repositories.txt
  repositories.txt
Labels: topic: submission

#3518 Update repositories.txt
  repositories.txt
Labels: topic: submission

#3519 Added FSM, CSOS
  repositories.txt
Labels: topic: submission

#3522 Update repositories.txt
  repositories.txt
Labels: topic: submission

#3524 Bosch bme280
  repositories.txt
Labels: topic: submission

#3525 Update repositories.txt
  repositories.txt
Labels: topic: submission

#3526 Update repositories.txt
  repositories.txt
Labels: topic: submission

#3523 Update repositories.txt
  repositories.txt
Labels: topic: submission

#3528 Update repositories.txt
  repositories.txt
Labels: topic: submission

#3530 nolven/ftp32 library added
  repositories.txt
Labels: topic: submission

#3531 Add Blues-Minimal-I2C
  repositories.txt
Labels: topic: submission

#3532 Update repositories.txt
  repositories.txt
Labels: topic: submission

#3533 add GyverOLEDMenu
  repositories.txt
Labels: topic: submission

#3534 add M5Module LAN 13.2 Lib
  repositories.txt
Labels: topic: submission

#3536 Update repositories.txt
  repositories.txt
Labels: topic: submission

#3538 Update repositories.txt
  repositories.txt
Labels: topic: submission

#3539 add mcp_canbus library
  repositories.txt
Labels: topic: submission
