Repository arduino/library-registry, pull requests merged in 2023-08, with the labels that each got.

#3148 Update repositories.txt
  repositories.txt
Labels: topic: submission

#3149 Update repositories.txt
  repositories.txt
Labels: topic: submission

#3150 Update repositories.txt
  repositories.txt
Labels: topic: submission

#3151 Update repositories.txt
  repositories.txt
Labels: topic: submission

#3154 Update repositories.txt
  repositories.txt
Labels: topic: submission

#3156 Add loopj/open-rts to library manager repositories list
  repositories.txt
Labels: topic: submission

#3152 Update repositories.txt
  repositories.txt
Labels: topic: submission

#3158 Add CosmosNV2 to repositories.txt
  repositories.txt
Labels: topic: submission

#3160 Update repositories.txt
  repositories.txt
Labels: topic: submission

#3161 Added sht3x-dis-arduino-lib to repositories.txt
  repositories.txt
Labels: topic: submission

#3168 Update repositories.txt
  repositories.txt
Labels: topic: submission

#3174 Update repositories.txt
  repositories.txt
Labels: topic: submission

#3177 Add epsilonrt/pimp library
  repositories.txt
Labels: topic: submission

#3181 Update repositories.txt
  repositories.txt
Labels: topic: submission

#3182 Update repositories.txt
  repositories.txt
Labels: topic: submission

#3183 Update repositories.txt
  repositories.txt
Labels: topic: submission

#3184 Update repositories.txt
  repositories.txt
Labels: topic: submission

#3188 Add Obsttube/CryptoAES_CBC to repositories.txt
  repositories.txt
Labels: topic: submission

#3191 Update repositories.txt
  repositories.txt
Labels: topic: submission

#3192 Update repositories.txt
  repositories.txt
Labels: topic: submission

#3193 Update repositories.txt
  repositories.txt
Labels: topic: submission

#3196 Update repositories.txt
  repositories.txt
Labels: topic: submission

#3197 Update repositories.txt
  repositories.txt
Labels: topic: submission

#3198 micro_ros_kaia lib submission
  repositories.txt
Labels: topic: submission

#3199 Update repositories.txt
  repositories.txt
Labels: topic: submission

#3203 Update repositories.txt
  repositories.txt
Labels: topic: submission

#3204 Added 1€ filter library
  repositories.txt
Labels: topic: submission

#3206 Update repositories.txt
  repositories.txt
Labels: topic: submission

#3211 Add WebConsole
  repositories.txt
Labels: topic: submission

#3213 Update repositories.txt
  repositories.txt
Labels: topic: submission

#3135 Update name of "ESP8266 Webhook"
  registry.txt
Labels: topic: rename, status: pending backend

#3143 Update URL of "PoE_CAM-Ethernet" on repository list
  repositories.txt
Labels: topic: modification, topic: URL change, status: pending backend

#3144 Update name and URL of "M5-Ethernet"
  registry.txt
Labels: topic: URL change, topic: rename, status: pending backend

#3173 Update name of "TCS3200-Sensor"
  registry.txt
Labels: topic: URL change, topic: rename, status: pending backend

#3176 Update name of "QUAD7SHIFT"
  registry.txt
Labels: topic: rename, status: pending backend

#3180 Update name of "Sensirion I2C SVM4x'
  registry.txt
Labels: topic: rename, status: pending backend

#3209 Remove "pimp" from repositories.txt
  repositories.txt
Labels: topic: removal, status: pending backend

#3210 Remove "pimp" from registry.txt
  registry.txt
Labels: topic: removal, status: pending backend

#3207 Update URL of "digiedge_frame_generator" in repositories.txt
  repositories.txt
Labels: topic: modification, status: pending backend

#3208 Update URL of "digiedge_frame_generator" in registry.txt
  registry.txt
Labels: topic: URL change, status: pending backend

#3134 Update URLs of libraries in "NuclearPhoenixx"-owned repos
  registry.txt
Labels: topic: URL change, status: pending backend

#3125 Change username URL
  repositories.txt
Labels: topic: modification, topic: URL change, status: pending backend

#3189 Update URL of "unit-system"
  registry.txt
Labels: topic: URL change, status: pending backend

#3186 updating library repository
  repositories.txt
Labels: topic: modification, topic: URL change, status: pending backend

#3190 Update name of "detaBaseESP8266"
  registry.txt
Labels: topic: rename, status: pending backend

#3221 Update repositories.txt
  repositories.txt
Labels: topic: submission

#3222 bibliotecas proyectil
  repositories.txt
Labels: topic: submission

#3223 add Sparkfun bno08x
  repositories.txt
Labels: topic: submission

#3224 Update repositories.txt
  repositories.txt
Labels: topic: submission

#3229 Update repositories.txt
  repositories.txt
Labels: topic: submission

#3231 Update repositories.txt
  repositories.txt
Labels: topic: submission

#3232 M5Module-Stepmotor &M5Module-GRBL-13.2
  repositories.txt
Labels: topic: submission

#3235 Update repositories.txt
  repositories.txt
Labels: topic: submission

#3237 Add PS4 Controller Library
  repositories.txt
Labels: topic: submission

#3238 Update repositories.txt
  repositories.txt
Labels: topic: submission

#3239 Geekble_note2freq Library Submission
  repositories.txt
Labels: topic: submission

#3241 Update repositories.txt
  repositories.txt
Labels: topic: submission

#3243 Update repositories.txt
  repositories.txt
Labels: topic: submission

#3244 Add Henhen1227's BluetoothSerial Library
  repositories.txt
Labels: topic: submission

#3242 Adjust submission procedure documentation to get correct PR base repo
  README.md
Labels: topic: documentation, topic: other, type: imperfection

#3245 Update repositories.txt
  repositories.txt
Labels: topic: submission

#3246 Add IOXESP32Audio library
  repositories.txt
Labels: topic: submission

#3247 Added TinyGPSMinus
  repositories.txt
Labels: topic: submission

#3249 Update repositories.txt
  repositories.txt
Labels: topic: submission

#3248 Update repositories.txt
  repositories.txt
Labels: topic: submission

#3251 Update repositories.txt
  repositories.txt
Labels: topic: submission

#3225 Update name of "ESP32_IO_Expander"
  registry.txt
Labels: topic: rename, status: pending backend

#3228 Update name of "Sensirion UART Svm4x"
  registry.txt
Labels: topic: rename, status: pending backend

#3236 Remove "MODULE_GRBL13.2"
  registry.txt
Labels: topic: removal, status: pending backend

#3233 Delete MODULE_GRBL13.2
  repositories.txt
Labels: topic: removal, status: pending backend

#3252 Update repositories.txt
  repositories.txt
Labels: topic: submission

#3257 https://github.com/holgerlembke/ESPFMfGK
  repositories.txt
Labels: topic: submission

#3258 Add Xylopyrographer/BooleanButton
  repositories.txt
Labels: topic: submission

#3259 Adding Lualtek wisblock-io-extension-mini
  repositories.txt
Labels: topic: submission

#3260 Update repositories.txt
  repositories.txt
Labels: topic: submission

#3261 Update repositories.txt
  repositories.txt
Labels: topic: submission

#3265 Update repositories.txt
  repositories.txt
Labels: topic: submission

#3266 Remove duplicate entry for "diwa"
  registry.txt
Labels: topic: code, type: imperfection

#3267 Add ENGR100-980
  repositories.txt
Labels: topic: submission

#3268 Update repositories.txt
  repositories.txt
Labels: topic: submission

#3269 Update repositories.txt
  repositories.txt
Labels: topic: submission

#3271 Update repositories.txt
  repositories.txt
Labels: topic: submission

#3274 Update repositories.txt
  repositories.txt
Labels: topic: submission

#3275 Update for Soict_IoT_Labs
  repositories.txt
Labels: topic: submission

#3263 Update repositories.txt
  repositories.txt
Labels: topic: removal, status: pending backend

#3276 Update repositories.txt
  repositories.txt
Labels: topic: submission

#3277 add SparkFun TMAG5273
  repositories.txt
Labels: topic: submission

#3278 MiniPLC_FX2N
  repositories.txt
Labels: topic: submission

#3279 Update repositories.txt
  repositories.txt
Labels: topic: submission

#3280 Update repositories.txt
  repositories.txt
Labels: topic: submission
