Repository arduino/library-registry, pull requests merged in 2023-05, with the labels that each got.

#2814 Update repositories.txt
  repositories.txt
Labels: topic: submission

#2815 Update repositories.txt
  repositories.txt
Labels: topic: submission

#2803 Add alkonosst/SSLClient
  repositories.txt
Labels: topic: submission

#2819 Add P1AM_Serial library
  repositories.txt
Labels: topic: submission

#2820 Update repositories.txt
  repositories.txt
Labels: topic: submission

#2821 Adding GoogleFormPost library
  repositories.txt
Labels: topic: submission

#2822 Update repositories.txt
  repositories.txt
Labels: topic: submission

#2823 Update repositories.txt
  repositories.txt
Labels: topic: submission

#2824 Update repositories.txt
  repositories.txt
Labels: topic: submission

#2825 Update repositories.txt
  repositories.txt
Labels: topic: submission

#2818 Add Deneyap Arduino Example Library
  repositories.txt
Labels: topic: submission

#2826 Update repositories.txt
  repositories.txt
Labels: topic: submission

#2828 Add Adafruit_MCP2515
  repositories.txt
Labels: topic: submission

#2830 Update repositories.txt
  repositories.txt
Labels: topic: submission

#2831 Update repositories.txt
  repositories.txt
Labels: topic: submission

#2805 Update URL of "RepeatButton"
  registry.txt
Labels: topic: URL change, status: pending backend

#2804 Update repositories.txt
  repositories.txt
Labels: topic: modification, topic: URL change, status: pending backend

#2817 Update URL of "CSWButtons" and "CSWBattery"
  registry.txt
Labels: topic: URL change, status: pending backend

#2813 Update repositories.txt
  repositories.txt
Labels: topic: modification, status: pending backend

#2833 Update repositories.txt
  repositories.txt
Labels: topic: submission

#2834 adding mDriver library
  repositories.txt
Labels: topic: submission

#2835 Update repositories.txt
  repositories.txt
Labels: topic: submission

#2836 Update repositories.txt
  repositories.txt
Labels: topic: submission

#2838 Update repositories.txt
  repositories.txt
Labels: topic: submission

#2837 BMI270_Sensor
  repositories.txt
Labels: topic: submission

#2842 Update repositories.txt
  repositories.txt
Labels: topic: submission

#2843 Update repositories.txt
  repositories.txt
Labels: topic: submission

#2844 Update repositories.txt
  repositories.txt
Labels: topic: submission

#2847 Update repositories.txt
  repositories.txt
Labels: topic: submission

#2848 Add mqtt_fuota_duino library
  repositories.txt
Labels: topic: submission

#2849 Add minbasecli library
  repositories.txt
Labels: topic: submission

#2850 add https://github.com/dojyorin/arduino_m0_tweak repo.
  repositories.txt
Labels: topic: submission

#2851 Update repositories.txt
  repositories.txt
Labels: topic: submission

#2852 Update repositories.txt
  repositories.txt
Labels: topic: submission

#2859 Update repositories.txt
  repositories.txt
Labels: topic: submission

#2839 Update name of "percent_encode"
  registry.txt
Labels: topic: rename, status: pending backend

#2862 Update repositories.txt
  repositories.txt
Labels: topic: submission

#2868 Update repositories.txt
  repositories.txt
Labels: topic: submission

#2869 Update repositories.txt
  repositories.txt
Labels: topic: submission

#2872 Update repositories.txt
  repositories.txt
Labels: topic: submission

#2873 Update repositories.txt
  repositories.txt
Labels: topic: submission

#2874 Include TinyMatrixMath library
  repositories.txt
Labels: topic: submission

#2875 Added A Library Arduino L298 Motor Driver.txt
  repositories.txt
Labels: topic: submission

#2876 Update repositories.txt
  repositories.txt
Labels: topic: submission

#2878 added a library to communicate with Cohere models through an API
  repositories.txt
Labels: topic: submission

#2882 Update repositories.txt
  repositories.txt
Labels: topic: submission

#2884 M5CoreS3
  repositories.txt
Labels: topic: submission

#2885 Add Deneyap Servo Library
  repositories.txt
Labels: topic: submission

#2886 Update repositories.txt
  repositories.txt
Labels: topic: submission

#2887 Update repositories.txt
  repositories.txt
Labels: topic: submission

#2891 Update repositories.txt
  repositories.txt
Labels: topic: submission

#2892 Update repositories.txt
  repositories.txt
Labels: topic: submission

#2893 Update repositories.txt
  repositories.txt
Labels: topic: submission

#2894 add bimac/EEPstore
  repositories.txt
Labels: topic: submission

#2895 dhtESP32-rmt
  repositories.txt
Labels: topic: submission

#2896 esp32-ds18b20-RMT
  repositories.txt
Labels: topic: submission

#2897 ButtonClickCheck : add
  repositories.txt
Labels: topic: submission

#2899 Added the Serial Packets library to the Arduino library list.
  repositories.txt
Labels: topic: submission

#2900 add https://github.com/flash62au/WiThrottleProtocol
  repositories.txt
Labels: topic: submission

#2902 Add ArtronShop_PCF85363
  repositories.txt
Labels: topic: submission

#2903 Update repositories.txt
  repositories.txt
Labels: topic: submission

#2904 Update repositories.txt
  repositories.txt
Labels: topic: submission

#2906 Adding DIYables_4Digit7Segment_74HC595 library to repositories.txt
  repositories.txt
Labels: topic: submission

#2907 Add TinyMenu To Library
  repositories.txt
Labels: topic: submission

#2866 Rename "ArtronShop_PCF85363A"
  registry.txt
Labels: topic: rename, status: pending backend

#2905 Remove "Serial_Packets"
  registry.txt
Labels: topic: removal, status: pending backend

#2901 Removing a new library I added earlier today.
  repositories.txt
Labels: topic: removal

#2908 Update repositories.txt
  repositories.txt
Labels: topic: submission
