Repository arduino/library-registry, pull requests merged in 2023-02, with the labels that each got.

#2427 Update name of "TR064"
  registry.txt
Labels: topic: rename, status: pending backend

#2436 Update name and URL of "SpeedControl"
  registry.txt
Labels: topic: URL change, topic: rename, status: pending backend

#2442 Add CrossMgrLapCounter
  repositories.txt
Labels: topic: submission

#2445 Update repositories.txt
  repositories.txt
Labels: topic: submission

#2447 Remove "DSpotterSDK_Maker_*" libraries
  repositories.txt
Labels: topic: removal, status: pending backend

#2443 Update URL of "ThingsBoard"
  registry.txt
Labels: topic: URL change, status: pending backend

#2441 Updated ThingsBoard Arduino SDK link
  repositories.txt
Labels: topic: modification, status: pending backend

#2449 Update repository.txt - added Lualtek TTN
  repositories.txt
Labels: topic: submission

#2450 Update repositories.txt
  repositories.txt
Labels: topic: submission

#2451 Update repositories.txt
  repositories.txt
Labels: topic: submission

#2453 Update repositories.txt
  repositories.txt
Labels: topic: submission

#2454 Add WisBlock-API-V2
  repositories.txt
Labels: topic: submission

#2458 Update repositories.txt
  repositories.txt
Labels: topic: submission

#2460 Update repositories.txt
  repositories.txt
Labels: topic: submission

#2462 Adding LINBus_stack 3.0
  repositories.txt
Labels: topic: submission

#2463 Add MultiWire package
  repositories.txt
Labels: topic: submission

#2464 Update repositories.txt
  repositories.txt
Labels: topic: submission

#2466 Update repositories.txt
  repositories.txt
Labels: topic: submission

#2468 Update repositories.txt
  repositories.txt
Labels: topic: submission

#2469 Add Telegraph
  repositories.txt
Labels: topic: submission

#2470 Update repositories.txt
  repositories.txt
Labels: topic: submission

#2471 Add library for LC709204F battery monitor.
  repositories.txt
Labels: topic: submission

#2472 Update repositories.txt
  repositories.txt
Labels: topic: submission

#2473 Update repositories.txt
  repositories.txt
Labels: topic: submission

#2474 Update repositories.txt
  repositories.txt
Labels: topic: submission

#2475 Add AM2315C library temperature and humidity - I2C
  repositories.txt
Labels: topic: submission

#2476 Update repositories.txt
  repositories.txt
Labels: topic: submission

#2477 Proposal of belgian Keyboard layout
  repositories.txt
Labels: topic: submission

#2478 Update repositories.txt
  repositories.txt
Labels: topic: submission

#2480 Adding BlueMicro_Examples Library for Keyboard examples
  repositories.txt
Labels: topic: submission

#2482 Update repositories.txt
  repositories.txt
Labels: topic: submission

#2483 Add DigiCombo
  repositories.txt
Labels: topic: submission

#2484 Adding BlueMicro_SAMD library
  repositories.txt
Labels: topic: submission

#2485 Update repositories.txt
  repositories.txt
Labels: topic: submission

#2488 Update repositories.txt
  repositories.txt
Labels: topic: submission

#2491 Library Add request
  repositories.txt
Labels: topic: submission

#2492 Update repositories.txt
  repositories.txt
Labels: topic: submission

#2493 Update repositories.txt
  repositories.txt
Labels: topic: submission

#2494 Add UniversalTransmitter.h
  repositories.txt
Labels: topic: submission

#2495 Added Arduino-LM96163 library
  repositories.txt
Labels: topic: submission

#2496 New library added
  repositories.txt
Labels: topic: submission

#2497 Add PCA9536D library
  repositories.txt
Labels: topic: submission

#2498 Update repositories.txt
  repositories.txt
Labels: topic: submission

#2499 Update repositories.txt
  repositories.txt
Labels: topic: submission

#2500 Adding RunningStats lib
  repositories.txt
Labels: topic: submission

#2502 Update repositories.txt
  repositories.txt
Labels: topic: submission

#2503 Update repositories.txt
  repositories.txt
Labels: topic: submission

#2505 Update repositories.txt
  repositories.txt
Labels: topic: submission

#2501 Request to remove matthias-bs/ESP32_ATC_MiThermometer_Library
  repositories.txt
Labels: topic: removal, status: pending backend

#2487 Remove "weatherLocation"
  registry.txt
Labels: topic: removal, status: pending backend

#2506 Update repositories.txt
  repositories.txt
Labels: topic: submission

#2507 Update repositories.txt
  repositories.txt
Labels: topic: submission

#2508 Update repositories.txt
  repositories.txt
Labels: topic: submission

#2509 Update repositories.txt
  repositories.txt
Labels: topic: submission

#2512 Update repositories.txt
  repositories.txt
Labels: topic: submission

#2513 Update repositories.txt
  repositories.txt
Labels: topic: submission

#2514 Add a new library for XGZP6897D I2C differential pressure
  repositories.txt
Labels: topic: submission

#2515 PicoStep
  repositories.txt
Labels: topic: submission

#2516 Add TCA9534-GPIO library
  repositories.txt
Labels: topic: submission

#2518 Update repositories.txt to add PID_v1_bc
  repositories.txt
Labels: topic: submission

#2519 Update repositories.txt
  repositories.txt
Labels: topic: submission

#2520 Add EspEasyUtils
  repositories.txt
Labels: topic: submission
