Repository arduino/library-registry, pull requests merged in 2023-09, with the labels that each got.

#3281 Update repositories.txt
  repositories.txt
Labels: topic: submission

#3282 Update repositories.txt
  repositories.txt
Labels: topic: submission

#3283 PGMTools
  repositories.txt
Labels: topic: submission

#3284 Update repositories.txt
  repositories.txt
Labels: topic: submission

#3285 Added Makeblock libraries.
  repositories.txt
Labels: topic: submission

#3286 Update repositories.txt
  repositories.txt
Labels: topic: submission

#3288 add M5Module-GNSS lib
  repositories.txt
Labels: topic: submission

#3289 Add Arduino_POSIXStorage to repositories.txt
  repositories.txt
Labels: topic: submission

#3290 Add Bas.Button
  repositories.txt
Labels: topic: submission

#3293 Update repositories.txt
  repositories.txt
Labels: topic: submission

#3294 Update repositories.txt
  repositories.txt
Labels: topic: submission

#3295 Update repositories.txt
  repositories.txt
Labels: topic: submission

#3297 Update repositories.txt - add AES_CMAC library
  repositories.txt
Labels: topic: submission

#3300 [AE-158] Add Arduino_UnifiedStorage to repositories.txt
  repositories.txt
Labels: topic: submission

#3301 Update repositories.txt - add MFRC522_NTAG424DNA library
  repositories.txt
Labels: topic: submission

#3302 Update repositories.txt
  repositories.txt
Labels: topic: submission

#3304 Update repositories.txt
  repositories.txt
Labels: topic: submission

#3305 Add rtnate/arduino-BasicTimer to repositories.txt
  repositories.txt
Labels: topic: submission

#3307 Update repositories.txt
  repositories.txt
Labels: topic: submission

#3310 Add Riscduino_MCUFRIEND_kbv library
  repositories.txt
Labels: topic: submission

#3314 Update repositories.txt
  repositories.txt
Labels: topic: submission

#3315 Update repositories.txt
  repositories.txt
Labels: topic: submission

#3316 Update repositories.txt
  repositories.txt
Labels: topic: submission

#3319 Update repositories.txt
  repositories.txt
Labels: topic: submission

#3320 Update repositories.txt
  repositories.txt
Labels: topic: submission

#3321 Library for KS0108 GLCD
  repositories.txt
Labels: topic: submission

#3324 Update repositories.txt
  repositories.txt
Labels: topic: submission

#3326 Update repositories.txt
  repositories.txt
Labels: topic: submission

#3327 Update repositories.txt
  repositories.txt
Labels: topic: submission

#3328 Update repositories.txt
  repositories.txt
Labels: topic: submission

#3331 Add ENS160 driver - Adafruit fork
  repositories.txt
Labels: topic: submission

#3330 Update repositories.txt
  repositories.txt
Labels: topic: submission

#3329 Update repositories.txt
  repositories.txt
Labels: topic: submission

#3332 Update repositories.txt
  repositories.txt
Labels: topic: submission

#3334 Update repositories.txt
  repositories.txt
Labels: topic: submission

#3336 Added ICRS-101-Devkit repository to repositories.txt
  repositories.txt
Labels: topic: submission

#3338 Update repositories.txt - Added Honeywell FMA sensor library
  repositories.txt
Labels: topic: submission

#3339 Update repositories.txt
  repositories.txt
Labels: topic: submission

#3340 Update repositories.txt to include NumberSpeaker library
  repositories.txt
Labels: topic: submission

#3343 add https://github.com/machinefi/w3bstream-client-arduino-ce
  repositories.txt
Labels: topic: submission

#3348 Update repositories.txt
  repositories.txt
Labels: topic: submission

#3349 Update repositories.txt
  repositories.txt
Labels: topic: submission

#3350 Added GFX4dESP32 Library
  repositories.txt
Labels: topic: submission

#3351 Update repositories.txt
  repositories.txt
Labels: topic: submission

#3353 Update repositories.txt
  repositories.txt
Labels: topic: submission

#3356 Added Flanco library (Spanish version).
  repositories.txt
Labels: topic: submission

#3359 Add UTF8ToGB2312 library
  repositories.txt
Labels: topic: submission

#3360 Adding Free-ESPatHome
  repositories.txt
Labels: topic: submission

#3361 Add ATS1.47-S3 Lib
  repositories.txt
Labels: topic: submission

#3362 Update repositories.txt
  repositories.txt
Labels: topic: submission

#3368 Update repositories.txt for readguy project
  repositories.txt
Labels: topic: submission

#3369 Add IS31FL3729_LED_Matrix to repositories.txt
  repositories.txt
Labels: topic: submission

#3370 Update repositories.txt
  repositories.txt
Labels: topic: submission

#3379 add M5Dial Library
  repositories.txt
Labels: topic: submission

#3381 Update repositories.txt
  repositories.txt
Labels: topic: submission

#3386 Update repositories.txt
  repositories.txt
Labels: topic: submission

#3387 Update repositories.txt
  repositories.txt
Labels: topic: submission

#3366 Update name of "MFRC522_NTAG424DNA"
  registry.txt
Labels: topic: rename, status: pending backend

#3365 Update name and URL of "ScioSense_ENS220"
  registry.txt
Labels: topic: URL change, topic: rename, status: pending backend

#3363 Update URL of "ScioSense_APC1"
  registry.txt
Labels: topic: URL change, status: pending backend

#3364 Update URL of "ScioSense_ENS21x"
  registry.txt
Labels: topic: URL change, status: pending backend

#3311 Update repositories.txt
  repositories.txt
Labels: topic: modification, status: pending backend

#3385 Remove "ESP32_Display_Panel"
  registry.txt
Labels: topic: removal, status: pending backend

#3367 Remove "esp-io-expander"
  registry.txt
Labels: topic: removal, status: pending backend

#3391 Update repositories.txt
  repositories.txt
Labels: topic: submission

#3390 Update repositories.txt
  repositories.txt
Labels: topic: submission

#3392 Eccel-C1 added to repositories.txt
  repositories.txt
Labels: topic: submission

#3394 Update repositories.txt
  repositories.txt
Labels: topic: submission

#3354 Update repositories.txt
  repositories.txt
Labels: topic: removal, status: pending backend

#3397 Update repositories.txt
  repositories.txt
Labels: topic: submission

#3398 Lion:Bit Library Added
  repositories.txt
Labels: topic: submission

#3400 Update repositories.txt
  repositories.txt
Labels: topic: submission

#3401 Update repositories.txt
  repositories.txt
Labels: topic: submission

#3402 Adds SparkFun OPT4048 Arduino Library
  repositories.txt
Labels: topic: submission

#3403 Update repositories.txt
  repositories.txt
Labels: topic: submission

#3404 Adding Adafruit-AD5693R library
  repositories.txt
Labels: topic: submission

#3405 Update repositories.txt
  repositories.txt
Labels: topic: submission

#3406 Update repositories.txt
  repositories.txt
Labels: topic: submission

#3407 Update repositories.txt
  repositories.txt
Labels: topic: submission
