Repository arduino/library-registry, pull requests merged in 2023-06, with the labels that each got.

#2913 adding Arduino_GroveI2C_Ultrasonic
  repositories.txt
Labels: topic: submission

#2914 Update repositories.txt
  repositories.txt
Labels: topic: submission

#2916 Update repositories.txt
  repositories.txt
Labels: topic: submission

#2917 Update repositories.txt
  repositories.txt
Labels: topic: submission

#2911 Add Blues Notecard Environment Variable Manager
  repositories.txt
Labels: topic: submission

#2921 Update repositories.txt
  repositories.txt
Labels: topic: submission

#2923 Update repositories.txt
  repositories.txt
Labels: topic: submission

#2922 Update repositories.txt
  repositories.txt
Labels: topic: submission

#2924 Update repositories.txt
  repositories.txt
Labels: topic: submission

#2925 Add LiteLED library
  repositories.txt
Labels: topic: submission

#2926 Update repositories.txt
  repositories.txt
Labels: topic: submission

#2928 Add liblcc
  repositories.txt
Labels: topic: submission

#2930 Added FutabaVfdM202MD10C library
  repositories.txt
Labels: topic: submission

#2932 Update repositories.txt
  repositories.txt
Labels: topic: submission

#2934 Update repositories.txt
  repositories.txt
Labels: topic: submission

#2937 Add Adafruit_GC9A01A
  repositories.txt
Labels: topic: submission

#2938 Update repositories.txt
  repositories.txt
Labels: topic: submission

#2939 add Arduino_StepperAsync5
  repositories.txt
Labels: topic: submission

#2940 add CompileTime
  repositories.txt
Labels: topic: submission

#2944 Update repositories.txt
  repositories.txt
Labels: topic: submission

#2945 Added Transform library
  repositories.txt
Labels: topic: submission

#2946 Update repositories.txt to add SiderealObjects library
  repositories.txt
Labels: topic: submission

#2947 Add: Add m5stack/PoE_CAM-Ethernet
  repositories.txt
Labels: topic: submission

#2948 Update repositories.txt
  repositories.txt
Labels: topic: submission

#2949 Add: Add m5stack/M5Unit-DigiClock
  repositories.txt
Labels: topic: submission

#2950 Adds RadioHead library
  repositories.txt
Labels: topic: submission

#2951 Add https://github.com/sakura-internet/sipf-arduino-client
  repositories.txt
Labels: topic: submission

#2953 Update repositories.txt
  repositories.txt
Labels: topic: submission

#2952 Update repositories.txt
  repositories.txt
Labels: topic: submission

#2954 Update repositories.txt
  repositories.txt
Labels: topic: submission

#2956 Update repositories.txt
  repositories.txt
Labels: topic: submission

#2960 Update repositories.txt
  repositories.txt
Labels: topic: submission

#2961 Add SunFounder_Ai_Camera
  repositories.txt
Labels: topic: submission

#2964 Update repositories.txt
  repositories.txt
Labels: topic: submission

#2963 Update repositories.txt
  repositories.txt
Labels: topic: submission

#2962 Added https://github.com/DIYables/DIYables_IRcontroller
  repositories.txt
Labels: topic: submission

#2965 Update repositories.txt
  repositories.txt
Labels: topic: submission

#2966 Adds LSM6DSV16X Arduino Library to Registery
  repositories.txt
Labels: topic: submission

#2970 Update repositories.txt
  repositories.txt
Labels: topic: submission

#2971 Added PDLS_EXT3_Basic_BWRY
  repositories.txt
Labels: topic: submission

#2972 Update repositories.txt to add RPlatform lib
  repositories.txt
Labels: topic: submission

#2975 add cyijun ESP32MQTTClient
  repositories.txt
Labels: topic: submission

#2976 Update repositories.txt
  repositories.txt
Labels: topic: submission

#2977 add cst816t capacitive touch ic
  repositories.txt
Labels: topic: submission

#2978 Add TLC5947
  repositories.txt
Labels: topic: submission

#2979 Update repositories.txt
  repositories.txt
Labels: topic: submission

#2980 added Smooth library
  repositories.txt
Labels: topic: submission

#2982 Update repositories.txt
  repositories.txt
Labels: topic: submission

#2983 Update repositories.txt
  repositories.txt
Labels: topic: submission

#2984 Update repositories.txt
  repositories.txt
Labels: topic: submission

#2985 Update repositories.txt
  repositories.txt
Labels: topic: submission

#2987 Update repositories.txt
  repositories.txt
Labels: topic: submission

#2989 Add LualtekRAK3172
  repositories.txt
Labels: topic: submission

#2990 Add SparkFun BMI270 library
  repositories.txt
Labels: topic: submission

#2991 Update repositories.txt
  repositories.txt
Labels: topic: submission

#2992 Add integer24 datatypes
  repositories.txt
Labels: topic: submission

#2996 Update repositories.txt
  repositories.txt
Labels: topic: submission

#2999 Update repositories.txt
  repositories.txt
Labels: topic: submission

#3000 Update repositories.txt
  repositories.txt
Labels: topic: submission

#3001 added rp2040 encoder library
  repositories.txt
Labels: topic: submission

#3002 Update repositories.txt
  repositories.txt
Labels: topic: submission

#3004 Update repositories.txt
  repositories.txt
Labels: topic: submission

#3007 AFE_NXP_Arduino added
  repositories.txt
Labels: topic: submission

#3008 Update repositories.txt to add EdgieD Library
  repositories.txt
Labels: topic: submission

#3010 Update repositories.txt
  repositories.txt
Labels: topic: submission

#3009 Update repositories.txt
  repositories.txt
Labels: topic: submission

#2993 Remove "Sensirion I2C SVM40" and "Sensirion UART SVM40"
  registry.txt
Labels: topic: removal, status: pending backend

#2994 Update URL of "Sensirion I2C SVM41" and "Sensirion UART Svm41"
  registry.txt
Labels: topic: URL change, status: pending backend

#2968 Update svm4x
  repositories.txt
Labels: topic: modification, topic: URL change, topic: removal, status: pending backend

#3011 Add SparkFun Weather Meter Kit Library
  repositories.txt
Labels: topic: submission

#3012 Update repositories.txt: New lib "avrCalibrate"
  repositories.txt
Labels: topic: submission

#3016 Added https://github.com/krishna-v/Pulser to list
  repositories.txt
Labels: topic: submission

#3017 Update repositories.txt
  repositories.txt
Labels: topic: submission

#3018 Added the EnviroDIY GroPoint Modbus library
  repositories.txt
Labels: topic: submission

#3019 Update repositories.txt
  repositories.txt
Labels: topic: submission

#3022 Update repositories.txt
  repositories.txt
Labels: topic: submission
