Repository arduino/library-registry, pull requests merged in 2023-11, with the labels that each got.

#3544 Update repositories.txt
  repositories.txt
Labels: topic: submission

#3545 Update repositories.txt
  repositories.txt
Labels: topic: submission

#3546 Update repositories.txt
  repositories.txt
Labels: topic: submission

#3547 add M5Unit-IMU-Pro-Mini lib
  repositories.txt
Labels: topic: submission

#3549 Update repositories.txt
  repositories.txt
Labels: topic: submission

#3550 Update repositories.txt
  repositories.txt
Labels: topic: submission

#3551 Update repositories.txt
  repositories.txt
Labels: topic: submission

#3552 Update repositories.txt
  repositories.txt
Labels: topic: submission

#3553 Update repositories.txt
  repositories.txt
Labels: topic: submission

#3554 Update repositories.txt to include DRV8251 library
  repositories.txt
Labels: topic: submission

#3555 Add Bergdahl_JBLogger
  repositories.txt
Labels: topic: submission

#3560 Update repositories.txt
  repositories.txt
Labels: topic: submission

#3565 add Adafruit_Faux86 library
  repositories.txt
Labels: topic: submission

#3568 Add enum_asukiaaa
  repositories.txt
Labels: topic: submission

#3566 added ILoveMemes SoftwareTimer library
  repositories.txt
Labels: topic: submission

#3569 Update repositories.txt
  repositories.txt
Labels: topic: submission

#3570 Update repositories.txt
  repositories.txt
Labels: topic: submission

#3571 Update repositories.txt
  repositories.txt
Labels: topic: submission

#3574 Update repositories.txt to add https://github.com/kevinlutzer/Arduino-PM1006K
  repositories.txt
Labels: topic: submission

#3575 Update repositories.txt
  repositories.txt
Labels: topic: submission

#3564 Update name and URL of "JBLogger"
  registry.txt
Labels: topic: URL change, topic: rename, status: pending backend

#3563 Update URL of "JBLogger"
  repositories.txt
Labels: topic: modification, status: pending backend

#3473 Remove "Waveshare_RP2040_BLE"
  registry.txt
Labels: topic: removal, status: pending backend

#3576 Adding MaffooClock/DFR_Radar
  repositories.txt
Labels: topic: submission

#3578 Update repositories.txt
  repositories.txt
Labels: topic: submission

#3583 Update repositories.txt
  repositories.txt
Labels: topic: submission

#3584 Update repositories.txt
  repositories.txt
Labels: topic: submission

#3586 Update repositories.txt
  repositories.txt
Labels: topic: submission

#3588 Update repositories.txt
  repositories.txt
Labels: topic: submission

#3589 Update repositories.txt
  repositories.txt
Labels: topic: submission

#3590 Update repositories.txt
  repositories.txt
Labels: topic: submission

#3591 Update repositories.txt
  repositories.txt
Labels: topic: submission

#3592 Update repositories.txt
  repositories.txt
Labels: topic: submission

#3593 Update repositories.txt
  repositories.txt
Labels: topic: submission

#3594 Update repositories.txt with MicroMidiEnc lib
  repositories.txt
Labels: topic: submission

#3595 Update repositories.txt
  repositories.txt
Labels: topic: submission

#3596 Update repositories.txt
  repositories.txt
Labels: topic: submission

#3597 Add new Library
  repositories.txt
Labels: topic: submission

#3599 Update repositories.txt
  repositories.txt
Labels: topic: submission

#3580 Remove "TaskQueue",
  registry.txt
Labels: conclusion: resolved, topic: removal, status: pending backend

#3573 Update repositories.txt
  repositories.txt
Labels: conclusion: resolved, topic: removal, status: pending backend

#3577 Update repositories.txt
  repositories.txt
Labels: conclusion: resolved, topic: URL change, status: pending backend

#3600 Add EasyBNO055_ESP
  repositories.txt
Labels: topic: submission

#3602 Update repositories.txt
  repositories.txt
Labels: topic: submission

#3604 Update repositories.txt
  repositories.txt
Labels: topic: submission

#3605 Update repositories.txt
  repositories.txt
Labels: topic: submission

#3606 Added Deneyap Telegram Library
  repositories.txt
Labels: topic: submission

#3608 add library
  repositories.txt
Labels: topic: submission

#3609 Update repositories.txt
  repositories.txt
Labels: topic: submission

#3610 Added zvonler/DebouncedLDR
  repositories.txt
Labels: topic: submission

#3612 Update repositories.txt
  repositories.txt
Labels: topic: submission

#3614 jm_crc-ccitt
  repositories.txt
Labels: topic: submission

#3615 VibrationMotor
  repositories.txt
Labels: topic: submission

#3613 Update repositories.txt
  repositories.txt
Labels: topic: submission

#3617 Update repositories.txt
  repositories.txt
Labels: topic: submission

#3616 Update repositories.txt
  repositories.txt
Labels: topic: submission

#3618 DCMotor
  repositories.txt
Labels: topic: submission

#3619 Added ESPNowJoystick library
  repositories.txt
Labels: topic: submission

#3620 Add https://github.com/koendv/FloatToString
  repositories.txt
Labels: topic: submission

#3623 Update repositories.txt
  repositories.txt
Labels: topic: submission

#3625 Update repositories.txt
  repositories.txt
Labels: topic: submission

#3627 Add library AM2302-Sensor
  repositories.txt
Labels: topic: submission

#3626 Update name of "Acrome-SMD"
  registry.txt
Labels: topic: rename, status: pending backend

#3628 add M5Unit-ToF4M lib
  repositories.txt
Labels: topic: submission

#3629 Update repositories.txt
  repositories.txt
Labels: topic: submission

#3630 Update repositories.txt
  repositories.txt
Labels: topic: submission

#3631 Remove duplicate entries
  repositories.txt
Labels: topic: modification, type: imperfection

#3634 Added PDLS_EXT3_Basic_Fast_152
  repositories.txt
Labels: topic: submission

#3635 Add senseBoxBLE to repositories.txt
  repositories.txt
Labels: topic: submission

#3636 Update repositories.txt
  repositories.txt
Labels: topic: submission

#3637 Update repositories.txt
  repositories.txt
Labels: topic: submission

#3638 Update repositories.txt - NetApiHelpers library
  repositories.txt
Labels: topic: submission

#3641 Added Deneyap Kart IDE Ornekler Library
  repositories.txt
Labels: topic: submission

#3642 update
  repositories.txt
Labels: topic: submission

#3643 Added https://github.com/AdamJHowell/ArrayManager
  repositories.txt
Labels: topic: submission

#3646 Add ArtronShop_LineNotify library
  repositories.txt
Labels: topic: submission

#3647 Add RLab
  repositories.txt
Labels: topic: submission

#3648 Update repositories.txt
  repositories.txt
Labels: topic: submission

#3650 Update repositories.txt
  repositories.txt
Labels: topic: submission

#3652 Update repositories.txt
  repositories.txt
Labels: topic: submission

#3654 Update repositories.txt
  repositories.txt
Labels: topic: submission

#3656 Added roo_collections.
  repositories.txt
Labels: topic: submission

#3657 Update repositories.txt
  repositories.txt
Labels: topic: submission

#3658 Added roo_scheduler.
  repositories.txt
Labels: topic: submission

#3651 Update repositories.txt
  repositories.txt
Labels: topic: submission

#3660 Update repositories.txt
  repositories.txt
Labels: topic: submission

#3663 Update repositories.txt
  repositories.txt
Labels: topic: submission

#3645 Update name and URL of "Mosiwi_Basic_Learning_Kit'
  registry.txt
Labels: topic: URL change, topic: rename, status: pending backend

#3644 Update URL for "Mosiwi_Basic_Learning_Kit" in repositories list
  repositories.txt
Labels: topic: URL change, status: pending backend

#3659 Update URL of "uNodepp"
  registry.txt
Labels: topic: URL change, status: pending backend

#3653 Update repositories.txt
  repositories.txt
Labels: topic: modification, status: pending backend

#3666 Remove "DC Motor Engine Control"
  registry.txt
Labels: topic: removal, status: pending backend

#3664 Update repositories.txt
  repositories.txt
Labels: topic: removal, status: pending backend

#3667 Update URL of "PDLS_EXT3_Basic"
  registry.txt
Labels: topic: URL change, status: pending backend

#3668 Remove "PDLS_EXT3_Basic_Fast_152"
  registry.txt
Labels: topic: removal, status: pending backend

#3665 Update repositories.txt - one URL changed and one URL removed
  repositories.txt
Labels: topic: modification, status: pending backend

#3669 Update repositories.txt
  repositories.txt
Labels: topic: submission
