Repository arduino/library-registry, pull requests merged in 2023-04, with the labels that each got.

#2641 Update repositories.txt
  repositories.txt
Labels: topic: submission

#2642 Added Nostr library
  repositories.txt
Labels: topic: submission

#2643 Update repositories.txt
  repositories.txt
Labels: topic: submission

#2644 added library for bee data logger
  repositories.txt
Labels: topic: submission

#2645 Update repositories.txt
  repositories.txt
Labels: topic: submission

#2646 Update repositories.txt
  repositories.txt
Labels: topic: submission

#2647 please add clickbutton library
  repositories.txt
Labels: topic: submission

#2649 Update repositories.txt
  repositories.txt
Labels: topic: submission

#2650 Add SparkFun_WebServer_ESP32_W5500
  repositories.txt
Labels: topic: submission

#2654 Update repositories.txt
  repositories.txt
Labels: topic: submission

#2657 Add xmodem library
  repositories.txt
Labels: topic: submission

#2658 Add Adafruit_CAN
  repositories.txt
Labels: topic: submission

#2660 Please add my new lib!
  repositories.txt
Labels: topic: submission

#2661 Update repositories.txt
  repositories.txt
Labels: topic: submission

#2662 Update repositories.txt
  repositories.txt
Labels: topic: submission

#2665 add esp32-supabase library
  repositories.txt
Labels: topic: submission

#2656 Update repositories.txt
  repositories.txt
Labels: topic: submission

#2664 Please add my new LCD driver lib!
  repositories.txt
Labels: topic: submission

#2667 Update repositories.txt
  repositories.txt
Labels: topic: submission

#2668 Added DWIN HMI Library
  repositories.txt
Labels: topic: submission

#2669 Update repositories.txt
  repositories.txt
Labels: topic: submission

#2673 Update repositories.txt
  repositories.txt
Labels: topic: submission

#2672 Update repositories.txt
  repositories.txt
Labels: topic: submission

#2634 Update name and URL of "artemis-cubesat"
  registry.txt
Labels: topic: URL change, topic: rename, status: pending backend

#2671 Remove "MLX90614_VEGA"
  registry.txt
Labels: topic: removal, status: pending backend

#2653 Update repositories.txt
  repositories.txt
Labels: topic: removal

#2678 Update repositories.txt to add new picovoice packages
  repositories.txt
Labels: topic: submission

#2679 Added CursedDoubleLinkedListInterface
  repositories.txt
Labels: topic: submission

#2680 Add 107-Arduino-Cyphal-Support.
  repositories.txt
Labels: topic: submission

#2681 Update repositories.txt
  repositories.txt
Labels: topic: submission

#2683 Update repositories.txt
  repositories.txt
Labels: topic: submission

#2684 Please add my new library: GPIO_NXP_Arduino
  repositories.txt
Labels: topic: submission

#2689 Add upt-core url
  repositories.txt
Labels: topic: submission

#2690 Update repositories.txt
  repositories.txt
Labels: topic: submission

#2692 Update repositories.txt
  repositories.txt
Labels: topic: submission

#2693 Add PicoMQTT library
  repositories.txt
Labels: topic: submission

#2695 Update repositories.txt
  repositories.txt
Labels: topic: submission

#2698 Add HX711_light
  repositories.txt
Labels: topic: submission

#2699 Update repositories.txt
  repositories.txt
Labels: topic: submission

#2700 Update repositories.txt
  repositories.txt
Labels: topic: submission

#2701 Update repositories.txt
  repositories.txt
Labels: topic: submission

#2705 Update repositories.txt
  repositories.txt
Labels: topic: submission

#2706 Update repositories.txt
  repositories.txt
Labels: topic: submission

#2708 Update repositories.txt
  repositories.txt
Labels: topic: submission

#2710 add Adafruit_IntelliKeys
  repositories.txt
Labels: topic: submission

#2712 Add Matrix Library
  repositories.txt
Labels: topic: submission

#2713 Update repositories.txt
  repositories.txt
Labels: topic: submission

#2714 Update repositories.txt
  repositories.txt
Labels: topic: submission

#2719 Update repositories.txt
  repositories.txt
Labels: topic: submission

#2720 Update repositories.txt
  repositories.txt
Labels: topic: submission

#2721 Update repositories.txt
  repositories.txt
Labels: topic: submission

#2723 Update repositories.txt
  repositories.txt
Labels: topic: submission

#2725 Update repositories.txt
  repositories.txt
Labels: topic: submission

#2726 Update repositories.txt
  repositories.txt
Labels: topic: submission

#2728 Update repositories.txt
  repositories.txt
Labels: topic: submission

#2730 Update repositories.txt
  repositories.txt
Labels: topic: submission

#2731 Update repositories.txt
  repositories.txt
Labels: topic: submission

#2687 Rename "ESP32 Supabase"
  registry.txt
Labels: topic: rename, status: pending backend

#2734 Update repositories.txt
  repositories.txt
Labels: topic: submission

#2735 Add yashi/Servo328
  repositories.txt
Labels: topic: submission

#2736 Update repositories.txt
  repositories.txt
Labels: topic: submission

#2740 Update repositories.txt
  repositories.txt
Labels: topic: submission

#2741 Update repositories.txt
  repositories.txt
Labels: topic: submission

#2742 Update repositories.txt
  repositories.txt
Labels: topic: submission

#2743 Update repositories.txt
  repositories.txt
Labels: topic: submission

#2744 Update repositories.txt
  repositories.txt
Labels: topic: submission

#2745 Update repositories.txt
  repositories.txt
Labels: topic: submission

#2746 Update repositories.txt
  repositories.txt
Labels: topic: submission

#2747 Update repositories.txt
  repositories.txt
Labels: topic: submission

#2748 Update repositories.txt
  repositories.txt
Labels: topic: submission

#2749 Update repositories.txt
  repositories.txt
Labels: topic: submission

#2750 add CirquePinnacle lib
  repositories.txt
Labels: topic: submission

#2751 Update repositories.txt
  repositories.txt
Labels: topic: submission

#2752 Update repositories.txt
  repositories.txt
Labels: topic: submission

#2753 repositories: add raisedevs/raise-dev-library.
  repositories.txt
Labels: topic: submission

#2755 Add WeatherFlow API Arduino library
  repositories.txt
Labels: topic: submission

#2756 Update repositories.txt
  repositories.txt
Labels: topic: submission

#2759 Update repositories.txt
  repositories.txt
Labels: topic: submission

#2761 Please add my new lib: I2C-MUX/SW
  repositories.txt
Labels: topic: submission

#2762 Update repositories.txt
  repositories.txt
Labels: topic: submission

#2763 add RESTuino to arduino library
  repositories.txt
Labels: topic: submission

#2766 Update repositories.txt
  repositories.txt
Labels: topic: submission

#2767 Update repositories.txt
  repositories.txt
Labels: topic: submission

#2768 Update repositories.txt
  repositories.txt
Labels: topic: submission

#2769 Add 107-Arduino-Servo-RP2040.
  repositories.txt
Labels: topic: submission

#2770 Update repositories.txt
  repositories.txt
Labels: topic: submission

#2771 Update repositories.txt
  repositories.txt
Labels: topic: submission

#2772 Add vdp-gl to library registry
  repositories.txt
Labels: topic: submission

#2775 Update repositories.txt
  repositories.txt
Labels: topic: submission

#2776 Update repositories.txt
  repositories.txt
Labels: topic: submission

#2780 Add library USBPowerDelivery
  repositories.txt
Labels: topic: submission

#2782 Update repositories.txt
  repositories.txt
Labels: topic: submission

#2786 Added HUB75(E) libraries for Arduino nano
  repositories.txt
Labels: topic: submission

#2790 Update repositories.txt
  repositories.txt
Labels: topic: submission

#2792 Update repositories.txt
  repositories.txt
Labels: topic: submission

#2793 add Seeed_Arduino_AHT20 library
  repositories.txt
Labels: topic: submission

#2794 Update repositories.txt
  repositories.txt
Labels: topic: submission

#2796 Update repositories.txt
  repositories.txt
Labels: topic: submission

#2797 Update repositories.txt
  repositories.txt
Labels: topic: submission

#2798 Update repositories.txt
  repositories.txt
Labels: topic: submission

#2799 Added DWIN Display Handler Library
  repositories.txt
Labels: topic: submission

#2800 Adding PI4IOE5V9554 library
  repositories.txt
Labels: topic: submission

#2801 Update repositories.txt
  repositories.txt
Labels: topic: submission

#2802 Update repositories.txt
  repositories.txt
Labels: topic: submission

#2806 Add new BH1750 lib
  repositories.txt
Labels: topic: submission

#2807 Add library of SHT30, SHT31, SHT35
  repositories.txt
Labels: topic: submission

#2808 Add library of SPL06-001
  repositories.txt
Labels: topic: submission

#2809 Add library of PCA85363A
  repositories.txt
Labels: topic: submission

#2810 Update repositories.txt
  repositories.txt
Labels: topic: submission

#2811 Update repositories.txt to include forcedBMX280-library
  repositories.txt
Labels: topic: submission
