Repository arduino/library-registry, pull requests merged in 2023-07, with the labels that each got.

#3023 Update repositories.txt
  repositories.txt
Labels: topic: submission

#3025 Update repositories.txt
  repositories.txt
Labels: topic: submission

#3027 Update repositories.txt
  repositories.txt
Labels: topic: submission

#3028 Update repositories.txt
  repositories.txt
Labels: topic: submission

#3030 Added TempReader v1.0.0
  repositories.txt
Labels: topic: submission

#3031 Add CowPi_stdio
  repositories.txt
Labels: topic: submission

#3035 Update repositories.txt
  repositories.txt
Labels: topic: submission

#3036 Remove "RaiseDev"
  registry.txt
Labels: topic: removal, status: pending backend

#3038 Added Arduino_CANOverSerial library
  repositories.txt
Labels: topic: submission

#3039 Add CowPi
  repositories.txt
Labels: topic: submission

#3042 Add Gauss Library
  repositories.txt
Labels: topic: submission

#3043 Add tedtoal/monitor_printf
  repositories.txt
Labels: topic: submission

#3045 Update repositories.txt
  repositories.txt
Labels: topic: submission

#3046 Add SparkFun_PCA9846_Mux_Arduino_Library
  repositories.txt
Labels: topic: submission

#3049 Update repositories.txt
  repositories.txt
Labels: topic: submission

#3050 Update repositories.txt
  repositories.txt
Labels: topic: submission

#3051 Update repositories.txt
  repositories.txt
Labels: topic: submission

#3052 Update repositories.txt
  repositories.txt
Labels: topic: submission

#3053 Add uNeurai Library
  repositories.txt
Labels: topic: submission

#3055 Update repositories.txt
  repositories.txt
Labels: topic: submission

#3056 Update repositories.txt
  repositories.txt
Labels: topic: submission

#3058 Update repositories.txt
  repositories.txt
Labels: topic: submission

#3059 Update repositories.txt
  repositories.txt
Labels: topic: submission

#3060 add ODriveArduino
  repositories.txt
Labels: topic: submission

#3061 Update repositories.txt
  repositories.txt
Labels: topic: submission

#3062 Update repositories.txt
  repositories.txt
Labels: topic: submission

#3068 Update repositories.txt
  repositories.txt
Labels: topic: submission

#3069 Update repositories.txt
  repositories.txt
Labels: topic: submission

#3074 Update repositories.txt
  repositories.txt
Labels: topic: submission

#3076 Update repositories.txt
  repositories.txt
Labels: topic: submission

#3077 Update repositories.txt
  repositories.txt
Labels: topic: submission

#3079 Update repositories.txt
  repositories.txt
Labels: topic: submission

#3081 Update repositories.txt
  repositories.txt
Labels: topic: submission

#3085 Update repositories.txt
  repositories.txt
Labels: topic: submission

#3086 Update repositories.txt
  repositories.txt
Labels: topic: submission

#3080 Update URL of "ViraLink-MQTT-Client"
  registry.txt
Labels: topic: URL change, status: pending backend

#3070 Update repositories.txt
  repositories.txt
Labels: topic: modification, topic: URL change, status: pending backend

#3091 Update repositories.txt
  repositories.txt
Labels: topic: submission

#3092 Update repositories.txt
  repositories.txt
Labels: topic: submission

#3095 Add https://github.com/machinefi/psa-crypto-arduino/
  repositories.txt
Labels: topic: submission

#3096 Update repositories.txt
  repositories.txt
Labels: topic: submission

#3099 Update repositories.txt
  repositories.txt
Labels: topic: submission

#3100 Update repositories.txt
  repositories.txt
Labels: topic: submission

#3101 Update repositories.txt
  repositories.txt
Labels: topic: submission

#3102 Update repositories.txt
  repositories.txt
Labels: topic: submission

#3103 Added https://github.com/AbdoullahBougataya/QCFA/ to repositories
  repositories.txt
Labels: topic: submission

#3105 Update repositories.txt
  repositories.txt
Labels: topic: submission

#3104 Update repositories.txt
  repositories.txt
Labels: topic: submission

#3107 Update repositories.txt
  repositories.txt
Labels: topic: submission

#3108 Update repositories.txt
  repositories.txt
Labels: topic: submission

#3110 Update repositories.txt
  repositories.txt
Labels: topic: submission

#3113 Update repositories.txt
  repositories.txt
Labels: topic: submission

#3114 Added MAX11643 ADC library
  repositories.txt
Labels: topic: submission

#3115 Update repositories.txt
  repositories.txt
Labels: topic: submission

#3116 Update repositories.txt
  repositories.txt
Labels: topic: submission

#3112 Update repositories.txt
  repositories.txt
Labels: topic: submission

#3118 Update repositories.txt
  repositories.txt
Labels: topic: submission

#3119 Update repositories.txt
  repositories.txt
Labels: topic: submission

#3117 Remove "FSSD"
  registry.txt
Labels: topic: removal, status: pending backend

#3106 Update repositories.txt
  repositories.txt
Labels: topic: removal, status: pending backend

#3120 Update repositories.txt
  repositories.txt
Labels: topic: submission

#3121 Update repositories.txt
  repositories.txt
Labels: topic: submission

#3122 Update repositories.txt
  repositories.txt
Labels: topic: submission

#3123 Update repositories.txt: Adafruit_TSC2046
  repositories.txt
Labels: topic: submission

#3126 Update repositories.txt
  repositories.txt
Labels: topic: submission

#3129 Update repositories.txt
  repositories.txt
Labels: topic: submission

#3130 Update repositories.txt
  repositories.txt
Labels: topic: submission

#3131 Add crc_asukiaaa
  repositories.txt
Labels: topic: submission

#3132 Update repositories.txt
  repositories.txt
Labels: topic: submission

#3133 Update repositories.txt
  repositories.txt
Labels: topic: submission

#3136 Update repositories.txt
  repositories.txt
Labels: topic: submission

#3138 Update repositories.txt
  repositories.txt
Labels: topic: submission

#3139 Update repositories.txt
  repositories.txt
Labels: topic: submission

#3145 Add ACDU support library to the registry
  repositories.txt
Labels: topic: submission

#3146 Update repositories.txt
  repositories.txt
Labels: topic: submission

#3147 Update repositories.txt
  repositories.txt
Labels: topic: submission
