Repository arduino/library-registry, pull requests merged in 2024-10, with the labels that each got.

#5184 Update repositories.txt
  repositories.txt
Labels: topic: submission

#5186 Update repositories.txt
  repositories.txt
Labels: topic: submission

#5143 Update name of "Soldered MCP4018 Arduino Library"
  registry.txt
Labels: topic: rename, status: pending backend

#5144 Update name of "Soldered LTR-507 Arduino Library"
  registry.txt
Labels: topic: rename, status: pending backend

#5145 Update name of "Soldered Hall Effect Arduino Library"
  registry.txt
Labels: topic: rename, status: pending backend

#5146 Update name of "Soldered Hall Effect Arduino Library"
  registry.txt
Labels: topic: rename, status: pending backend

#5147 Update name of "Soldered MCP23017 Arduino Library"
  registry.txt
Labels: topic: rename, status: pending backend

#5149 Update name of "Soldered nRF24 Arduino Library"
  registry.txt
Labels: topic: rename, status: pending backend

#5150 Update name of "Soldered Obstacle Sensor Arduino Library"
  registry.txt
Labels: topic: rename, status: pending backend

#5152 Update name of "Soldered PCF85063A RTC Arduino Library"
  registry.txt
Labels: topic: rename, status: pending backend

#5153 Update name of "Soldered SI114X Light Sensor Arduino Library"
  registry.txt
Labels: topic: rename, status: pending backend

#5156 Update name and URL of "esp-brookesia"
  registry.txt
Labels: topic: URL change, topic: rename, status: pending backend

#5157 Remove "esp-ui-phone_320_240_stylesheet"
  registry.txt
Labels: topic: removal, status: pending backend

#5158 Remove "esp-ui-phone_480_480_stylesheet"
  registry.txt
Labels: topic: removal, status: pending backend

#5159 Remove "esp-ui-phone_800_480_stylesheet"
  registry.txt
Labels: topic: removal, status: pending backend

#5160 Remove "esp-ui-phone_1024_600_stylesheet"
  registry.txt
Labels: topic: removal, status: pending backend

#5155 Remove some libraries
  repositories.txt
Labels: topic: URL change, topic: removal, status: pending backend

#5187 Add LSA08_Simplified v1.0.0
  repositories.txt
Labels: topic: submission

#5188 Update repositories.txt
  repositories.txt
Labels: topic: submission

#5192 AsyncTask Library
  repositories.txt
Labels: topic: submission

#5193 Add Seven Segment Display library
  repositories.txt
Labels: topic: submission

#5194 Update repositories.txt
  repositories.txt
Labels: topic: submission

#5195 Update repositories.txt
  repositories.txt
Labels: topic: submission

#5202 Please add bb_truetype
  repositories.txt
Labels: topic: submission

#5203 Update repositories.txt
  repositories.txt
Labels: topic: submission

#5204 Add ISRHandler library
  repositories.txt
Labels: topic: submission

#5205 EspFileManager library
  repositories.txt
Labels: topic: submission

#5206 Update repositories.txt
  repositories.txt
Labels: topic: submission

#5216 Update repositories.txt
  repositories.txt
Labels: topic: submission

#5217 Update repositories.txt
  repositories.txt
Labels: topic: submission

#5221 Adding Arduino_NiclaSenseEnv to library index.
  repositories.txt
Labels: topic: submission

#5222 Add ArtronShop_HDC302x lib
  repositories.txt
Labels: topic: submission

#5220 Update name of "WindQX"
  registry.txt
Labels: topic: rename, status: pending backend

#5197 Update URL of "OSP ResultCodes aoresult"
  registry.txt
Labels: topic: URL change, status: pending backend

#5198 Update URL of "OSP Telegrams aoosp"
  registry.txt
Labels: topic: URL change, status: pending backend

#5199 Update URL of "OSP CommandInterpreter aocmd"
  registry.txt
Labels: topic: URL change, status: pending backend

#5200 Update URL of "OSP Middleware aomw"
  registry.txt
Labels: topic: URL change, status: pending backend

#5201 Update URL of "OSP UIDriversOSP32 aoui32"
  registry.txt
Labels: topic: URL change, status: pending backend

#5171 Update repositories.txt for ams-OSRAM[-Group]
  repositories.txt
Labels: topic: modification, status: pending backend

#5223 Update repositories.txt
  repositories.txt
Labels: topic: submission

#5224 Update repositories.txt
  repositories.txt
Labels: topic: submission

#5226 Add mr76_radar
  repositories.txt
Labels: topic: submission

#5227 Add M5Unit-HEART
  repositories.txt
Labels: topic: submission

#5228 M5Unit-GESTURE
  repositories.txt
Labels: topic: submission

#5229 M5Unit-HUB
  repositories.txt
Labels: topic: submission

#5230 Update repositories.txt
  repositories.txt
Labels: topic: submission

#5231 Update repositories.txt
  repositories.txt
Labels: topic: submission

#5232 Update repositories.txt
  repositories.txt
Labels: topic: submission

#5233 MX8650 library for Arduino and ESP
  repositories.txt
Labels: topic: submission

#5238 jsonencoder
  repositories.txt
Labels: topic: submission

#5239 Update repositories.txt
  repositories.txt
Labels: topic: submission

#5240 Update repositories.txt
  repositories.txt
Labels: topic: submission

#5242 Add ATC_MiThermometer repository
  repositories.txt
Labels: topic: submission

#5241 Add RotEncoder library to repositories.txt
  repositories.txt
Labels: topic: submission

#5243 add codingABI/DFR0534
  repositories.txt
Labels: topic: submission

#5244 Update repositories.txt
  repositories.txt
Labels: topic: submission

#5245 Update repositories.txt
  repositories.txt
Labels: topic: submission

#5246 Update repositories.txt
  repositories.txt
Labels: topic: submission

#5247 Update repositories.txt
  repositories.txt
Labels: topic: submission

#5249 Update repositories.txt
  repositories.txt
Labels: topic: submission

#5250 Update repositories.txt
  repositories.txt
Labels: topic: submission

#5251 Please add MINDS-i-Utils repo
  repositories.txt
Labels: topic: submission

#5253 Please add my bb_epaper library
  repositories.txt
Labels: topic: submission

#5254 Develop
  repositories.txt
Labels: topic: submission

#5256 Adding Adafruit INA3221 library
  repositories.txt
Labels: topic: submission

#5257 Update repositories.txt
  repositories.txt
Labels: topic: submission

#5258 Add cliSerialMenu from Garfius
  repositories.txt
Labels: topic: submission

#5259 Update repositories.txt
  repositories.txt
Labels: topic: submission

#5260 Update repositories.txt
  repositories.txt
Labels: topic: submission

#5261 Update repositories.txt
  repositories.txt
Labels: topic: submission

#5262 Update repositories.txt
  repositories.txt
Labels: topic: submission

#5266 Update repositories.txt
  repositories.txt
Labels: topic: submission

#5267 Add QRCodeGenerator library
  repositories.txt
Labels: topic: submission

#5275 Update repositories.txt
  repositories.txt
Labels: topic: submission

#5276 Update repositories.txt
  repositories.txt
Labels: topic: submission

#5277 Update repositories.txt
  repositories.txt
Labels: topic: submission

#5278 Update repositories.txt
  repositories.txt
Labels: topic: submission

#5280 Update repositories.txt
  repositories.txt
Labels: topic: submission

#5293 add WS2812Capture
  repositories.txt
Labels: topic: submission

#5294 Update repositories.txt
  repositories.txt
Labels: topic: submission

#5295 Update repositories.txt
  repositories.txt
Labels: topic: submission

#5296 Update repositories.txt
  repositories.txt
Labels: topic: submission

#5297 Update repositories.txt
  repositories.txt
Labels: topic: submission

#5298 Update repositories.txt
  repositories.txt
Labels: topic: submission

#5299 Update repositories.txt
  repositories.txt
Labels: topic: submission

#5300 add M5Module-LLM lib
  repositories.txt
Labels: topic: submission

#5301 Update repositories.txt
  repositories.txt
Labels: topic: submission

#5304 Update repositories.txt
  repositories.txt
Labels: topic: submission

#5305 Update repositories.txt
  repositories.txt
Labels: topic: submission

#5306 Update repositories.txt
  repositories.txt
Labels: topic: submission

#5307 Added CCS811 lib to the lib list
  repositories.txt
Labels: topic: submission

#5308 Update repositories.txt
  repositories.txt
Labels: topic: submission

#5309 Update repositories.txt
  repositories.txt
Labels: topic: submission

#5310 Update repositories.txt
  repositories.txt
Labels: topic: submission

#5312 Update repositories.txt
  repositories.txt
Labels: topic: submission

#5313 Adding Adafruit VCNL4200 library
  repositories.txt
Labels: topic: submission

#5315 Update repositories.txt
  repositories.txt
Labels: topic: submission

#5317 Add dwiBus Library to Arduino Library Manager
  repositories.txt
Labels: topic: submission

#5318 add https://github.com/bdlow/IO22_IO_Board
  repositories.txt
Labels: topic: submission

#5319 Add ACD3100 library
  repositories.txt
Labels: topic: submission

#5320 Add Arduino_OPC_UA to Arduino library index.
  repositories.txt
Labels: topic: submission

#5322 Update repositories.txt
  repositories.txt
Labels: topic: submission

#5323 Update repositories.txt
  repositories.txt
Labels: topic: submission

#5324 Update repositories.txt
  repositories.txt
Labels: topic: submission

#5325 add FastTimer
  repositories.txt
Labels: topic: submission

#5329 Add library request
  repositories.txt
Labels: topic: submission

#5332 IP2366
  repositories.txt
Labels: topic: submission
