Repository arduino/library-registry, pull requests merged in 2024-06, with the labels that each got.

#4590 iarduino.ru libraries
  repositories.txt
Labels: topic: submission

#4606 add lib
  repositories.txt
Labels: topic: submission

#4607 Update repositories.txt
  repositories.txt
Labels: topic: submission

#4608 Add EthernetESP32
  repositories.txt
Labels: topic: submission

#4610 Update repositories.txt
  repositories.txt
Labels: topic: submission

#4614 Update repositories.txt
  repositories.txt
Labels: topic: submission

#4615 Update repositories.txt
  repositories.txt
Labels: topic: submission

#4616 Update repositories.txt
  repositories.txt
Labels: topic: submission

#4620 Update repositories.txt
  repositories.txt
Labels: topic: submission

#4622 Update repositories.txt
  repositories.txt
Labels: topic: submission

#4626 added cx devices
  repositories.txt
Labels: topic: submission

#4627 submission
  repositories.txt
Labels: topic: submission

#4628 added ESPAsyncHTTPUpdateServer to repositories.txt
  repositories.txt
Labels: topic: submission

#4629 add slight_PlainTime
  repositories.txt
Labels: topic: submission

#4631 submission
  repositories.txt
Labels: topic: submission

#4636 Update repositories.txt
  repositories.txt
Labels: topic: submission

#4641 OTAUpdateManager
  repositories.txt
Labels: topic: submission

#4642 Update repositories.txt
  repositories.txt
Labels: topic: submission

#4643 Update repositories.txt
  repositories.txt
Labels: topic: submission

#4653 add https://github.com/marcinbor85/clip to repositories.txt
  repositories.txt
Labels: topic: submission

#4654 Added EZButton Library to repository
  repositories.txt
Labels: topic: submission

#4655 Update repositories.txt
  repositories.txt
Labels: topic: submission

#4657 Update repositories.txt
  repositories.txt
Labels: topic: submission

#4658 Update repositories.txt
  repositories.txt
Labels: topic: submission

#4659 Adding Adafruit_DS248x
  repositories.txt
Labels: topic: submission

#4660 add maqui_library to repositories.txt
  repositories.txt
Labels: topic: submission

#4661 Adding library for amx8x5 compatible RTCs
  repositories.txt
Labels: topic: submission

#4662 Update repositories.txt
  repositories.txt
Labels: topic: submission

#4625 Update name of "Sensirion UART SFx6xxx"
  registry.txt
Labels: topic: rename, status: pending backend

#4600 Update name of "LCD_BacklightRGB"
  registry.txt
Labels: topic: rename, status: pending backend

#4647 Update name and URL of "EiMOS"
  registry.txt
Labels: topic: URL change, topic: rename, status: pending backend

#4649 Update name and URL of "EiMOS_U8X8"
  registry.txt
Labels: topic: URL change, topic: rename, status: pending backend

#4603 Update name and URL of "GDXLib"
  registry.txt
Labels: topic: URL change, topic: rename, status: pending backend

#4601 Update repositories.txt
  repositories.txt
Labels: topic: modification, status: pending backend

#4609 Update repositories.txt
  repositories.txt
Labels: topic: removal, status: pending backend

#4650 Update repositories.txt
  repositories.txt
Labels: topic: URL change, status: pending backend

#4651 Update URL of "SNP_Sensor"
  registry.txt
Labels: conclusion: resolved, topic: URL change, status: pending backend

#4665 Don't limit number of open Dependabot pull requests
  .github/dependabot.yml
Labels: topic: other

#4666 Update repositories.txt
  repositories.txt
Labels: topic: submission

#4670 Update repositories.txt
  repositories.txt
Labels: topic: submission

#4671 Update repositories.txt
  repositories.txt
Labels: topic: submission

#4672 DisCard Library Added
  repositories.txt
Labels: topic: submission

#4674 Update repositories.txt
  repositories.txt
Labels: topic: submission

#4675 add esp32-rmt-ir
  repositories.txt
Labels: topic: submission

#4676 Update repositories.txt
  repositories.txt
Labels: topic: submission

#4681 Update repositories.txt
  repositories.txt
Labels: topic: submission

#4677 Update repositories.txt
  repositories.txt
Labels: topic: submission

#4685 Update repositories.txt
  repositories.txt
Labels: topic: submission

#4688 Update repositories.txt
  repositories.txt
Labels: topic: submission

#4689 add library Pantalla12x8
  repositories.txt
Labels: topic: submission

#4690 Update repositories.txt
  repositories.txt
Labels: topic: submission

#4691 Add M5NanoC6
  repositories.txt
Labels: topic: submission

#4668 Update name of "MQSensor"
  registry.txt
Labels: topic: rename, status: pending backend

#4692 Remove "ATCommands"
  registry.txt
Labels: topic: removal, status: pending backend

#4686 Remove Library
  repositories.txt
Labels: topic: removal, status: pending backend

#4693 Update repositories.txt
  repositories.txt
Labels: topic: submission

#4694 Update repositories.txt
  repositories.txt
Labels: topic: submission

#4695 Update repositories.txt
  repositories.txt
Labels: topic: submission

#4696 add KobaProduction/BDSP
  repositories.txt
Labels: topic: submission

#4697 Feat/MKPin and Arduino-MK_HC595 lib
  repositories.txt
Labels: topic: submission

#4698 Update repositories.txt
  repositories.txt
Labels: topic: submission

#4700 Update repositories.txt
  repositories.txt
Labels: topic: submission

#4702 Update repositories.txt
  repositories.txt
Labels: topic: submission

#4704 Update repositories.txt
  repositories.txt
Labels: topic: submission

#4706 Update repositories.txt
  repositories.txt
Labels: topic: submission

#4708 Update repositories.txt
  repositories.txt
Labels: topic: submission

#4709 Update repositories.txt
  repositories.txt
Labels: topic: submission

#4711 Update repositories.txt
  repositories.txt
Labels: topic: submission

#4712 Update repositories.txt
  repositories.txt
Labels: topic: submission

#4713 Update repositories.txt
  repositories.txt
Labels: topic: submission

#4714 Update repositories.txt
  repositories.txt
Labels: topic: submission

#4715 Update repositories.txt
  repositories.txt
Labels: topic: submission

#4716 Infrared receiver library
  repositories.txt
Labels: topic: submission

#4717 Update repositories.txt
  repositories.txt
Labels: topic: submission

#4718 Update repositories.txt
  repositories.txt
Labels: topic: submission

#4724 Update repositories.txt
  repositories.txt
Labels: topic: submission

#4725 Update repositories.txt
  repositories.txt
Labels: topic: submission
