Repository arduino/library-registry, pull requests merged in 2024-03, with the labels that each got.

#4144 Update repositories.txt
  repositories.txt
Labels: topic: submission

#4146 New library
  repositories.txt
Labels: topic: submission

#4148 Update repositories.txt
  repositories.txt
Labels: topic: submission

#4149 Update repositories.txt
  repositories.txt
Labels: topic: submission

#4150 Add Sensirion UPT I2C Auto Detection Registry
  repositories.txt
Labels: topic: submission

#4152 Add PowerFeather-SDK library
  repositories.txt
Labels: topic: submission

#4153 Update repositories.txt
  repositories.txt
Labels: topic: submission

#4154 Update repositories.txt
  repositories.txt
Labels: topic: submission

#4155 Update repositories.txt
  repositories.txt
Labels: topic: submission

#4158 Update repositories.txt
  repositories.txt
Labels: topic: submission

#4159 Added ESP32_RTC_EEPROM and heltec_esp32_lora_v3
  repositories.txt
Labels: topic: submission

#4160 Update repositories.txt
  repositories.txt
Labels: topic: submission

#4162 Update repositories.txt
  repositories.txt
Labels: topic: submission

#4164 Update repositories.txt
  repositories.txt
Labels: topic: submission

#4165 Update repositories.txt
  repositories.txt
Labels: topic: submission

#4166 Add "Supabase-ESP32" Library
  repositories.txt
Labels: topic: submission

#4168 Update repositories.txt
  repositories.txt
Labels: topic: submission

#4174 Update repositories.txt
  repositories.txt
Labels: topic: submission

#4175 Add MAX520 library
  repositories.txt
Labels: topic: submission

#4176 Update repositories.txt
  repositories.txt
Labels: topic: submission

#4177 add M5DinMeter, Unit CAN, Unit I2C Weight, Unit PbHub Lib
  repositories.txt
Labels: topic: submission

#4178 Added ACANFD_GIGA_R1
  repositories.txt
Labels: topic: submission

#4179 Update repositories.txt
  repositories.txt
Labels: topic: submission

#4173 Update name of "Bluepad32 for NINA-W10 boards"
  registry.txt
Labels: topic: rename, status: pending backend

#4151 Remove "YA_FSM"
  registry.txt
Labels: topic: removal, status: pending backend

#4147 remove old library
  repositories.txt
Labels: topic: removal, status: pending backend

#4183 General Tool API
  repositories.txt
Labels: topic: submission

#4187 Update repositories.txt
  repositories.txt
Labels: topic: submission

#4184 Update repositories.txt
  repositories.txt
Labels: topic: submission

#4191 Update repositories.txt
  repositories.txt
Labels: topic: submission

#4193 Update repositories.txt
  repositories.txt
Labels: topic: submission

#4200 Wrote HotButton, a button library
  repositories.txt
Labels: topic: submission

#4201 Update repositories.txt
  repositories.txt
Labels: topic: submission

#4202 Update repositories.txt
  repositories.txt
Labels: topic: submission

#4204 devkit for blite v0.1.0
  repositories.txt
Labels: topic: submission

#4206 Update repositories.txt
  repositories.txt
Labels: topic: submission

#4207 Update repositories.txt
  repositories.txt
Labels: topic: submission

#4208 Update repositories.txt
  repositories.txt
Labels: topic: submission

#4209 Update repositories.txt
  repositories.txt
Labels: topic: submission

#4190 Update name of "PubSubClient_iiot"
  registry.txt
Labels: topic: rename, status: pending backend

#4199 Update name of "SpotifyEsp32"
  registry.txt
Labels: topic: rename, status: pending backend

#4181 Update url of "Supabase-ESP32"
  registry.txt
Labels: topic: URL change, status: pending backend

#4180 Update Repository Name Supabase-ESP32 to Supabase-Arduino
  repositories.txt
Labels: topic: modification

#4188 Update URL of "Gizmo"
  registry.txt
Labels: topic: URL change, status: pending backend

#4214 Update repositories.txt
  repositories.txt
Labels: topic: submission

#4215 Add FlixPeriph library
  repositories.txt
Labels: topic: submission

#4216 Update repositories.txt
  repositories.txt
Labels: topic: submission

#4217 Added ha-mqtt-entities library
  repositories.txt
Labels: topic: submission

#4219 Update repositories.txt
  repositories.txt
Labels: topic: submission

#4221 Update repositories.txt
  repositories.txt
Labels: topic: submission

#4223 Update repositories.txt
  repositories.txt
Labels: topic: submission

#4224 Update repositories.txt
  repositories.txt
Labels: topic: submission

#4227 Update repositories.txt
  repositories.txt
Labels: topic: submission

#4228 Update repositories.txt
  repositories.txt
Labels: topic: submission

#4232 add SparkFun XM125
  repositories.txt
Labels: topic: submission

#4236 Added NHBot arduino libraries
  repositories.txt
Labels: topic: submission

#4229 Added vovagorodok arduino libraries
  repositories.txt
Labels: topic: submission

#4241 Update repositories.txt
  repositories.txt
Labels: topic: submission

#4242 Update repositories.txt
  repositories.txt
Labels: topic: submission

#4243 Update repositories.txt
  repositories.txt
Labels: topic: submission

#4244 add LCT200 Library
  repositories.txt
Labels: topic: submission

#4247 Rename "LiquidCrystal_I2C_UTF8"
  registry.txt
Labels: topic: rename, status: pending backend

#4248 Rename "Connect Arduino-Supabase"
  registry.txt
Labels: topic: rename, status: pending backend

#4246 Remove "AISwitch"
  registry.txt
Labels: topic: removal, status: pending backend

#4245 Update repositories.txt
  repositories.txt
Labels: topic: removal, status: pending backend

#4249 Update repositories.txt
  repositories.txt
Labels: topic: submission

#4250 Update repositories.txt
  repositories.txt
Labels: topic: submission

#4252 Update repositories.txt
  repositories.txt
Labels: topic: submission

#4254 Update repositories.txt
  repositories.txt
Labels: topic: submission

#4257 Update repositories.txt
  repositories.txt
Labels: topic: submission

#4258 Add TLC5917 library
  repositories.txt
Labels: topic: submission

#4259 added UPT BLE auto detection
  repositories.txt
Labels: topic: submission

#4260 Update repositories.txt
  repositories.txt
Labels: topic: submission

#4261 Update repositories.txt
  repositories.txt
Labels: topic: submission

#4262 Update repositories.txt
  repositories.txt
Labels: topic: submission

#4263 Update repositories.txt
  repositories.txt
Labels: topic: submission

#4265 Update repositories.txt
  repositories.txt
Labels: topic: submission

#4269 Update repositories.txt
  repositories.txt
Labels: topic: submission

#4267 Add Arduino_SerialUpdater
  repositories.txt
Labels: topic: submission

#4268 Add Arduino_Opta_Blueprint
  repositories.txt
Labels: topic: submission

#4270 Update repositories.txt
  repositories.txt
Labels: topic: submission

#4273 Update repositories.txt
  repositories.txt
Labels: topic: submission

#4274 Update repositories.txt
  repositories.txt
Labels: topic: submission

#4275 Update repositories.txt
  repositories.txt
Labels: topic: submission

#4276 Update repositories.txt
  repositories.txt
Labels: topic: submission

#4278 Update repositories.txt
  repositories.txt
Labels: topic: submission

#4280 Update 1 repositories.txt
  repositories.txt
Labels: topic: submission

#4256 Rename "Pokerobo_RCB"
  registry.txt
Labels: topic: rename, status: pending backend

#4284 Update repositories.txt
  repositories.txt
Labels: topic: submission

#4285 Update repositories.txt
  repositories.txt
Labels: topic: submission

#4287 Update repositories.txt
  repositories.txt
Labels: topic: submission

#4289 Update repositories.txt
  repositories.txt
Labels: topic: submission
