Repository arduino/library-registry, pull requests merged in 2024-12, with the labels that each got.

#5500 add LineMessagingAPI
  repositories.txt
Labels: topic: submission

#5502 Added UM RGB Touch Mini helper library.
  repositories.txt
Labels: topic: submission

#5503 add Telnet lib
  repositories.txt
Labels: topic: submission

#5504 Add Mux7SegsDisplay library.
  repositories.txt
Labels: topic: submission

#5505 Added ConsentiumNow library
  repositories.txt
Labels: topic: submission

#5507 Update repositories.txt
  repositories.txt
Labels: topic: submission

#5508 Update repositories.txt
  repositories.txt
Labels: topic: submission

#5511 Update repositories.txt
  repositories.txt
Labels: topic: submission

#5518 Update repositories.txt
  repositories.txt
Labels: topic: submission

#5519 Update repositories.txt
  repositories.txt
Labels: topic: submission

#5521 Add RX8130CE Lib (RTC)
  repositories.txt
Labels: topic: submission

#5522 Update repositories.txt
  repositories.txt
Labels: topic: submission

#5523 Update repositories.txt
  repositories.txt
Labels: topic: submission

#5525 Update repositories.txt
  repositories.txt
Labels: topic: submission

#5530 Update repositories.txt
  repositories.txt
Labels: topic: submission

#5532 Update repositories.txt
  repositories.txt
Labels: topic: submission

#5534 Update repositories.txt
  repositories.txt
Labels: topic: submission

#5540 Update repositories.txt
  repositories.txt
Labels: topic: submission

#5541 Update repositories.txt
  repositories.txt
Labels: topic: submission

#5542 Update repositories.txt
  repositories.txt
Labels: topic: submission

#5545 Update repositories.txt
  repositories.txt
Labels: topic: submission

#5548 Update repositories.txt
  repositories.txt
Labels: topic: submission

#5550 Update repositories.txt
  repositories.txt
Labels: topic: submission

#5552 Updated repositories.txt
  repositories.txt
Labels: topic: submission

#5553 Update repositories.txt
  repositories.txt
Labels: topic: submission

#5554 Update repositories.txt
  repositories.txt
Labels: topic: submission

#5555 Update requirements.txt
  repositories.txt
Labels: topic: submission

#5556 Update requirements.txt
  repositories.txt
Labels: topic: submission

#5559 Detector ir
  repositories.txt
Labels: topic: submission

#5560 Update repositories.txt
  repositories.txt
Labels: topic: submission

#5562 Update repositories.txt
  repositories.txt
Labels: topic: submission

#5563 Update repositories.txt
  repositories.txt
Labels: topic: submission

#5564 Update repositories.txt
  repositories.txt
Labels: topic: submission

#5565 Update repositories.txt
  repositories.txt
Labels: topic: submission

#5566 Update repositories.txt
  repositories.txt
Labels: topic: submission

#5567 Update repositories.txt
  repositories.txt
Labels: topic: submission

#5568 Update repositories.txt
  repositories.txt
Labels: topic: submission

#5569 Update repositories.txt
  repositories.txt
Labels: topic: submission

#5570 Update repositories.txt
  repositories.txt
Labels: topic: submission

#5571 Update repositories.txt
  repositories.txt
Labels: topic: submission

#5572 Update repositories.txt
  repositories.txt
Labels: topic: submission

#5573 Update repositories.txt
  repositories.txt
Labels: topic: submission

#5574 Update repositories.txt
  repositories.txt
Labels: topic: submission

#5575 Update repositories.txt
  repositories.txt
Labels: topic: submission

#5576 Update repositories.txt
  repositories.txt
Labels: topic: submission

#5577 Updated repositories.txt
  repositories.txt
Labels: topic: submission

#5579 Update repositories.txt
  repositories.txt
Labels: topic: submission

#5533 Update URL of "Geekble_LieDetector"
  registry.txt
Labels: topic: URL change, status: pending backend

#5535 Remove "EventLinkInterrupt"
  registry.txt
Labels: topic: removal, status: pending backend

#5536 Remove "GPT_Stepper"
  registry.txt
Labels: topic: removal, status: pending backend

#5537 Remove "LoveButton"
  registry.txt
Labels: topic: removal, status: pending backend

#5538 Remove "PID_DG"
  registry.txt
Labels: topic: removal, status: pending backend

#5529 Removing redundant libraries
  repositories.txt
Labels: topic: removal, status: pending backend

#5549 Update URL of "Geekble_Note2Freq"
  registry.txt
Labels: topic: URL change, status: pending backend

#5546 Update repositories.txt
  repositories.txt
Labels: topic: modification

#5581 Update repositories.txt
  repositories.txt
Labels: topic: submission

#5582 Update repositories.txt
  repositories.txt
Labels: topic: submission

#5583 Update repositories.txt
  repositories.txt
Labels: topic: submission

#5587 Update repositories.txt
  repositories.txt
Labels: topic: submission

#5588 Adding LVGL_CYD
  repositories.txt
Labels: topic: submission

#5589 Update repositories.txt
  repositories.txt
Labels: topic: submission

#5594 feat: Add ADS1115
  repositories.txt
Labels: topic: submission

#5599 Update repositories.txt
  repositories.txt
Labels: topic: submission

#5601 New Arduino Library gfxDraw
  repositories.txt
Labels: topic: submission

#5602 Add beegee-tokyo/RAK-OneWireSerial
  repositories.txt
Labels: topic: submission

#5604 fvs-bib-esp32
  repositories.txt
Labels: topic: submission

#5606 Add tom-dudman/DS1804
  repositories.txt
Labels: topic: submission

#5607 Update repositories.txt
  repositories.txt
Labels: topic: submission

#5608 Update repositories.txt
  repositories.txt
Labels: topic: submission

#5609 Add the private LoRa library
  repositories.txt
Labels: topic: submission

#5612 Update repositories.txt
  repositories.txt
Labels: topic: submission

#5617 new library
  repositories.txt
Labels: topic: submission

#5618 Add BackgroundAudio library
  repositories.txt
Labels: topic: submission

#5619 Update repositories.txt
  repositories.txt
Labels: topic: submission

#5622 Update repositories.txt
  repositories.txt
Labels: topic: submission

#5626 Update repositories.txt
  repositories.txt
Labels: topic: submission

#5628 add new library https://github.com/botnroll/BnrOneAPlus
  repositories.txt
Labels: topic: submission

#5629 Adding CppComponentsLibrary
  repositories.txt
Labels: topic: submission

#5630 Library add request
  repositories.txt
Labels: topic: submission

#5631 Update repositories.txt
  repositories.txt
Labels: topic: submission

#5640 Update repositories.txt
  repositories.txt
Labels: topic: submission

#5643 Update repositories.txt
  repositories.txt
Labels: topic: submission

#5644 Update repositories.txt
  repositories.txt
Labels: topic: submission

#5645 Add spi_lcd_read
  repositories.txt
Labels: topic: submission

#5646 Update repositories.txt
  repositories.txt
Labels: topic: submission

#5647 Update Url of "iotNetESP32"
  repositories.txt
Labels: topic: submission

#5650 Added CSE_ZH06
  repositories.txt
Labels: topic: submission

#5651 Add MCP23017_MR
  repositories.txt
Labels: topic: submission

#5652 Update repositories.txt
  repositories.txt
Labels: topic: submission

#5653 Update repositories.txt
  repositories.txt
Labels: topic: submission

#5654 chore: update url of "MP3 Player"
  repositories.txt
Labels: topic: submission

#5656 Update repositories.txt
  repositories.txt
Labels: topic: submission

#5657 Update repositories.txt
  repositories.txt
Labels: topic: submission

#5658 Update repositories.txt
  repositories.txt
Labels: topic: submission

#5665 add M5Atomic-EchoBase lib
  repositories.txt
Labels: topic: submission

#5666 Update repositories.txt
  repositories.txt
Labels: topic: submission

#5667 add LED-Warrior 09 Lib
  repositories.txt
Labels: topic: submission

#5668 Add 7SemiSHT4x_Library to Arduino Library Manager
  repositories.txt
Labels: topic: submission

#5670 Update repositories.txt
  repositories.txt
Labels: topic: submission

#5671 Update repositories.txt
  repositories.txt
Labels: topic: submission

#5673 Adding tinyServo85 library to repositories.txt.
  repositories.txt
Labels: topic: submission

#5674 ADS1119 Arduino Library
  repositories.txt
Labels: topic: submission

#5675 Update repositories.txt
  repositories.txt
Labels: topic: submission

#5678 Update repositories.txt
  repositories.txt
Labels: topic: submission

#5679 Update repositories.txt
  repositories.txt
Labels: topic: submission

#5680 Update repositories.txt
  repositories.txt
Labels: topic: submission

#5681 Update repositories.txt
  repositories.txt
Labels: topic: submission

#5682 Update repositories.txt
  repositories.txt
Labels: topic: submission

#5684 Update repositories.txt
  repositories.txt
Labels: topic: submission

#5686 Update repositories.txt
  repositories.txt
Labels: topic: submission

#5689 Update repositories.txt
  repositories.txt
Labels: topic: submission

#5691 Update repositories.txt
  repositories.txt
Labels: topic: submission

#5692 Update repositories.txt
  repositories.txt
Labels: topic: submission

#5693 add Library MCP23008-I2C
  repositories.txt
Labels: topic: submission

#5694 Update repositories.txt
  repositories.txt
Labels: topic: submission

#5669 A library for interfacing with the MOTY-mini temperature sensor.
  repositories.txt
Labels: topic: submission

#5701 Update repositories.txt
  repositories.txt
Labels: topic: submission

#5704 Update repositories.txt
  repositories.txt
Labels: topic: submission

#5705 Update repositories.txt
  repositories.txt
Labels: topic: submission
