Repository arduino/library-registry, pull requests merged in 2024-02, with the labels that each got.

#3977 Update repositories.txt
  repositories.txt
Labels: topic: submission

#3978 add M5Unit Synth,QRCode,M5Atomic Motion Lib
  repositories.txt
Labels: topic: submission

#3979 Update repositories.txt
  repositories.txt
Labels: topic: submission

#3980 Update repositories.txt
  repositories.txt
Labels: topic: submission

#3983 Update repositories.txt
  repositories.txt
Labels: topic: submission

#3985 Update repositories.txt
  repositories.txt
Labels: topic: submission

#3992 Update repositories.txt
  repositories.txt
Labels: topic: submission

#3993 Update repositories.txt
  repositories.txt
Labels: topic: submission

#3994 Update repositories.txt
  repositories.txt
Labels: topic: submission

#3995 Update repositories.txt
  repositories.txt
Labels: topic: submission

#3999 Update repositories.txt
  repositories.txt
Labels: topic: submission

#4002 Update repositories.txt
  repositories.txt
Labels: topic: submission

#4004 Update repositories.txt
  repositories.txt
Labels: topic: submission

#4005 Update repositories.txt
  repositories.txt
Labels: topic: submission

#4010 Update repositories.txt
  repositories.txt
Labels: topic: submission

#4013 Update repositories.txt
  repositories.txt
Labels: topic: submission

#4017 Add mathieucarbou/MycilaTrial
  repositories.txt
Labels: topic: submission

#4020 Update repositories.txt
  repositories.txt
Labels: topic: submission

#4021 IO7F32 Registration
  repositories.txt
Labels: topic: submission

#4022 Update repositories.txt add M5StackToio
  repositories.txt
Labels: topic: submission

#4023 Update repositories.txt
  repositories.txt
Labels: topic: submission

#4000 Update name of "ardwloop"
  registry.txt
Labels: topic: rename, status: pending backend

#4009 Update name of "MovingPlatform"
  registry.txt
Labels: topic: rename, status: pending backend

#4024 Adding Lualtek buttino-handler
  repositories.txt
Labels: topic: submission

#3956 Update repositories.txt
  repositories.txt
Labels: topic: modification

#4015 Updated the lib URL of Sensirion UPT core
  repositories.txt
Labels: topic: URL change, status: pending backend

#4025 repositories.txt
  repositories.txt
Labels: topic: submission

#4031 Update repositories.txt
  repositories.txt
Labels: topic: submission

#4034 Added sitronlabs/SitronLabs_Weikai_WK2132_Arduino_Library
  repositories.txt
Labels: topic: submission

#4037 Update repositories.txt
  repositories.txt
Labels: topic: submission

#4038 Add SparkFun_ADS1219_Arduino_Library
  repositories.txt
Labels: topic: submission

#4043 Add Arduino_SecureElement library
  repositories.txt
Labels: topic: submission

#4044 Addded sitronlabs/SitronLabs_Enedis_TIC_Arduino_Library
  repositories.txt
Labels: topic: submission

#4047 Update repositories.txt
  repositories.txt
Labels: topic: submission

#4049 repositories.txt: Add BEST Gizmo support library
  repositories.txt
Labels: topic: submission

#4050 Add Lualtek lualtek-rakrui
  repositories.txt
Labels: topic: submission

#4051 Added OOKwiz: on/off keying for ESP32
  repositories.txt
Labels: topic: submission

#4052 Add SparkFun GNSS message parser
  repositories.txt
Labels: topic: submission

#4053 sparkfun qwiic buzzer arduino library
  repositories.txt
Labels: topic: submission

#4054 Update repositories.txt
  repositories.txt
Labels: topic: submission

#4055 Added sitronlabs/SitronLabs_SinoWealth_SH1106_Arduino_Library
  repositories.txt
Labels: topic: submission

#4029 Update name of "st7567sfGK 128x64 i2c LCD driver for Generation Klick"
  registry.txt
Labels: topic: rename, status: pending backend

#4028 Update name of "JJYReceiver"
  registry.txt
Labels: topic: rename, status: pending backend

#4032 Update name of "Sensirion UPT Core"
  registry.txt
Labels: topic: rename, status: pending backend

#4035 Update URL of "EByte RF E70 library" in `repositories.txt`
  repositories.txt
Labels: topic: URL change, status: pending backend

#4036 Update name and URL of "EByte RF E70 library"
  registry.txt
Labels: topic: URL change, topic: rename, status: pending backend

#4057 Update repositories.txt
  repositories.txt
Labels: topic: submission

#4060 Update repositories.txt
  repositories.txt
Labels: topic: submission

#4063 Update repositories.txt
  repositories.txt
Labels: topic: submission

#4064 Update repositories.txt
  repositories.txt
Labels: topic: submission

#4067 https://github.com/Sam4uk/Password
  repositories.txt
Labels: topic: submission

#4068 Update repositories.txt
  repositories.txt
Labels: topic: submission

#4069 Add mathieucarbou/MycilaTaskManager
  repositories.txt
Labels: topic: submission

#4070 Update repositories.txt
  repositories.txt
Labels: topic: submission

#4071 Update repositories.txt
  repositories.txt
Labels: topic: submission

#4073 Update repositories.txt
  repositories.txt
Labels: topic: submission

#4078 Update repositories.txt to add XY6020L lib
  repositories.txt
Labels: topic: submission

#4079 Add New Libraries from code Author braydenanderson2014
  repositories.txt
Labels: topic: submission

#4082 Update repositories.txt to include 2 new Libraries
  repositories.txt
Labels: topic: submission

#4086 Update repositories.txt
  repositories.txt
Labels: topic: submission

#4087 Add madflight library
  repositories.txt
Labels: topic: submission

#4088 Update repositories.txt to include 3 new Libraries
  repositories.txt
Labels: topic: submission

#4090 Update repositories.txt
  repositories.txt
Labels: topic: submission

#4091 Update repositories.txt
  repositories.txt
Labels: topic: submission

#4092 Update repositories.txt
  repositories.txt
Labels: topic: submission

#4094 Update repositories.txt
  repositories.txt
Labels: topic: submission

#4096 Update repositories.txt
  repositories.txt
Labels: topic: submission

#4097 Update repositories.txt
  repositories.txt
Labels: topic: submission

#4098 ESP-Wifi-Config library
  repositories.txt
Labels: topic: submission

#4059 Update URL of "wolfssl"
  registry.txt
Labels: topic: URL change, status: pending backend

#4056 Initial Official wolfSSL Arduino Library
  repositories.txt
Labels: topic: URL change, status: pending backend

#4083 Remove "SharkJ1939"
  registry.txt
Labels: topic: removal, status: pending backend

#4074 Update repositories.txt
  repositories.txt
Labels: topic: removal, status: pending backend

#4085 Remove "FloatToString"
  registry.txt
Labels: topic: removal, status: pending backend

#4084 remove koendv/FloatToString
  repositories.txt
Labels: topic: removal, status: pending backend

#4100 Update repositories.txt
  repositories.txt
Labels: topic: modification

#4102 Add mathieucarbou/MycilaPZEM004Tv3
  repositories.txt
Labels: topic: submission

#4103 add FloatToAscii
  repositories.txt
Labels: topic: submission

#4104 Update repositories.txt
  repositories.txt
Labels: topic: submission

#4105 Add Lualtek buttino-rak
  repositories.txt
Labels: topic: submission

#4108 Update repositories.txt
  repositories.txt
Labels: topic: submission

#4109 Update repositories.txt
  repositories.txt
Labels: topic: submission

#4111 Update repositories.txt
  repositories.txt
Labels: topic: submission

#4112 Update repositories.txt
  repositories.txt
Labels: topic: submission

#4113 Update repositories.txt
  repositories.txt
Labels: topic: submission

#4114 Update repositories.txt
  repositories.txt
Labels: topic: submission

#4121 Added My library in repositories.txt
  repositories.txt
Labels: topic: submission

#4122 Update repositories.txt
  repositories.txt
Labels: topic: submission

#4124 Update repositories.txt
  repositories.txt
Labels: topic: submission

#4125 Update repositories.txt
  repositories.txt
Labels: topic: submission

#4123 Update repositories.txt
  repositories.txt
Labels: topic: submission

#4131 Update repositories.txt
  repositories.txt
Labels: topic: submission

#4137 Update repositories.txt
  repositories.txt
Labels: topic: submission

#4130 Update name of "Ardwloop"
  registry.txt
Labels: topic: rename, status: pending backend

#4115 Remove "LualtekRAK3172"
  registry.txt
Labels: topic: removal, status: pending backend

#4116 Remove "LualtekButtinoHandler"
  registry.txt
Labels: topic: removal, status: pending backend

#4106 Remove Lualtek deprecated libs
  repositories.txt
Labels: topic: removal, status: pending backend

#4138 Retire Arduino_MachineControl lib
  registry.txt
Labels: topic: type change, status: pending backend
