Repository arduino/library-registry, pull requests merged in 2024-07, with the labels that each got.

#4728 add lib
  repositories.txt
Labels: topic: submission

#4731 Update repositories.txt
  repositories.txt
Labels: topic: submission

#4733 Update repositories.txt
  repositories.txt
Labels: topic: submission

#4735 Update repositories.txt
  repositories.txt
Labels: topic: submission

#4736 Feat/UnoCar lib
  repositories.txt
Labels: topic: submission

#4737 Add NetWizard Library to Registry
  repositories.txt
Labels: topic: submission

#4738 Update repositories.txt
  repositories.txt
Labels: topic: submission

#4739 Update repositories.txt
  repositories.txt
Labels: topic: submission

#4742 Update repositories.txt
  repositories.txt
Labels: topic: submission

#4745 Update repositories.txt
  repositories.txt
Labels: topic: submission

#4746 WS2812_Lib_for_Air001
  repositories.txt
Labels: topic: submission

#4751 Update repositories.txt
  repositories.txt
Labels: topic: submission

#4752 add lib
  repositories.txt
Labels: topic: submission

#4743 Update name of "EiMOS_U8X8"
  registry.txt
Labels: topic: rename, status: pending backend

#4755 Update repositories.txt
  repositories.txt
Labels: topic: submission

#4757 Update repositories.txt
  repositories.txt
Labels: topic: submission

#4758 Update repositories.txt
  repositories.txt
Labels: topic: submission

#4759 Update repositories.txt
  repositories.txt
Labels: topic: submission

#4761 Update repositories.txt
  repositories.txt
Labels: topic: submission

#4762 Update repositories.txt
  repositories.txt
Labels: topic: submission

#4763 Update repositories.txt
  repositories.txt
Labels: topic: submission

#4764 add lib
  repositories.txt
Labels: topic: submission

#4765 Update repositories.txt
  repositories.txt
Labels: topic: submission

#4766 Add Wio Cellular library
  repositories.txt
Labels: topic: submission

#4767 Update repositories.txt
  repositories.txt
Labels: topic: submission

#4769 Update repositories.txt
  repositories.txt
Labels: topic: submission

#4770 Added repo for the HLK-LD2450 radar sensor
  repositories.txt
Labels: topic: submission

#4771 Please add zlib_turbo
  repositories.txt
Labels: topic: submission

#4774 Update repositories.txt
  repositories.txt
Labels: topic: submission

#4775 QN8066 Arduino Library
  repositories.txt
Labels: topic: submission

#4776 Update repositories.txt
  repositories.txt
Labels: topic: submission

#4777 Add AwsIotWiFiClient repository
  repositories.txt
Labels: topic: submission

#4781 IRRemoteESP32
  repositories.txt
Labels: topic: submission

#4782 add MKL_RTC
  repositories.txt
Labels: topic: submission

#4783 Update repositories.txt
  repositories.txt
Labels: topic: submission

#4784 Update repositories.txt
  repositories.txt
Labels: topic: submission

#4785 Update repositories.txt
  repositories.txt
Labels: topic: submission

#4786 Add ez-arduino library
  repositories.txt
Labels: topic: submission

#4787 Update repositories.txt
  repositories.txt
Labels: topic: submission

#4788 Update repositories.txt to include my library Yeelight
  repositories.txt
Labels: topic: submission

#4789 Update repositories.txt
  repositories.txt
Labels: topic: submission

#4793 added ConsentiumThings firmware
  repositories.txt
Labels: topic: submission

#4795 Add DataLogger.h lib
  repositories.txt
Labels: topic: submission

#4796 Update repositories.txt
  repositories.txt
Labels: topic: submission

#4799 add lib
  repositories.txt
Labels: topic: submission

#4802 Update repositories.txt
  repositories.txt
Labels: topic: submission

#4803 Update repositories.txt
  repositories.txt
Labels: topic: submission

#4753 Update name and URL of "MentorBit-Library"
  registry.txt
Labels: topic: URL change, topic: rename, status: pending backend

#4750 Change library name
  repositories.txt
Labels: topic: URL change, status: pending backend

#4780 Remove "EasyUI"
  registry.txt
Labels: topic: removal, status: pending backend

#4778 Remove "ICM45688P"
  registry.txt
Labels: topic: removal, status: pending backend

#4768 Remove icm45688p support
  repositories.txt
Labels: topic: removal, status: pending backend

#4811 Add IOXESP32 4-20mA Receiver shield library
  repositories.txt
Labels: topic: submission

#4813 Add MPXHZ6116A to libraries
  repositories.txt
Labels: topic: submission

#4814 Update repositories.txt
  repositories.txt
Labels: topic: submission

#4817 Adding libraries esp32_idf5_https_server and esp32_idf5_https_server_compat
  repositories.txt
Labels: topic: submission

#4818 Update repositories.txt
  repositories.txt
Labels: topic: submission

#4821 Add M5Unit-BLDC & M5NanoC6
  repositories.txt
Labels: topic: submission

#4824 Update repositories.txt
  repositories.txt
Labels: topic: submission

#4826 Update repositories.txt
  repositories.txt
Labels: topic: submission

#4827 Update repositories.txt
  repositories.txt
Labels: topic: submission

#4828 Update repositories.txt
  repositories.txt
Labels: topic: submission

#4829 Update repositories.txt
  repositories.txt
Labels: topic: submission

#4830 Add Husarnet ESP32 library
  repositories.txt
Labels: topic: submission

#4831 Update repositories.txt
  repositories.txt
Labels: topic: submission

#4832 Update repositories.txt
  repositories.txt
Labels: topic: submission

#4833 Add senseshift/arduino-ble-serial
  repositories.txt
Labels: topic: submission

#4834 Update repositories.txt
  repositories.txt
Labels: topic: submission

#4838 Update repositories.txt
  repositories.txt
Labels: topic: submission

#4839 Update repositories.txt
  repositories.txt
Labels: topic: submission

#4842 Update repositories.txt
  repositories.txt
Labels: topic: submission

#4843 Add M5-STHS34PF80
  repositories.txt
Labels: topic: submission

#4844 Update repositories.txt
  repositories.txt
Labels: topic: submission

#4847 Add SimpleIMU library repo to repositories.txt
  repositories.txt
Labels: topic: submission

#4848 add lib
  repositories.txt
Labels: topic: submission

#4849 Add https://github.com/mathieucarbou/MycilaDS18
  repositories.txt
Labels: topic: submission

#4850 Add https://github.com/mathieucarbou/MycilaWebSerial
  repositories.txt
Labels: topic: submission

#4851 Add https://github.com/mathieucarbou/MycilaUtilities
  repositories.txt
Labels: topic: submission

#4852 Add https://github.com/mathieucarbou/MycilaSystem
  repositories.txt
Labels: topic: submission

#4853 Added Bosch Sensortec's BSEC2 library
  repositories.txt
Labels: topic: submission

#4846 Use standard repository list URL format for "ESP Async Web Server"
  repositories.txt
Labels: topic: modification

#4869 Add EVN-arduino Library
  repositories.txt
Labels: topic: submission

#4870 Update repositories.txt
  repositories.txt
Labels: topic: submission

#4871 Please add NMEA_Parser.h and Units.h libraries
  repositories.txt
Labels: topic: submission

#4872 Update repositories.txt
  repositories.txt
Labels: topic: submission

#4794 Remove ConsentiumThingsDalton Library
  repositories.txt
Labels: topic: removal, status: pending backend

#4874 add lib
  repositories.txt
Labels: topic: submission

#4804 Update URL for jhagas/ESPSupabase
  repositories.txt
Labels: topic: modification, status: pending backend

#4857 Remove "ConsentiumThingsDalton"
  registry.txt
Labels: conclusion: resolved, topic: removal, status: pending backend

#4812 Update name of "WioCellular"
  registry.txt
Labels: topic: rename, status: pending backend

#4864 Update URL of "LiquidCrystalIO"
  registry.txt
Labels: conclusion: resolved, topic: URL change, status: pending backend

#4865 Update URL of "SimpleCollections"
  registry.txt
Labels: conclusion: resolved, topic: URL change, status: pending backend

#4866 Update URL of "TaskManagerIO"
  registry.txt
Labels: conclusion: resolved, topic: URL change, status: pending backend

#4867 Update URL of "tcMenu"
  registry.txt
Labels: conclusion: resolved, topic: URL change, status: pending backend

#4868 Update URL of "tcUnicodeHelper"
  registry.txt
Labels: conclusion: resolved, topic: URL change, status: pending backend

#4854 Move all davetcc repositories under TcMenu org
  repositories.txt
Labels: topic: modification, status: pending backend

#4855 Update name of "OSP ResultCodes aoresult"
  registry.txt
Labels: conclusion: resolved, topic: rename, status: pending backend

#4856 Update name of "OSP 2wireSPI aospi"
  registry.txt
Labels: conclusion: resolved, topic: rename, status: pending backend

#4876 add lib
  repositories.txt
Labels: topic: submission

#4877 add lib
  repositories.txt
Labels: topic: submission

#4882 Update repositories.txt
  repositories.txt
Labels: topic: submission

#4889 Update repositories.txt
  repositories.txt
Labels: topic: submission

#4897 Update repositories.txt
  repositories.txt
Labels: topic: submission

#4887 Update repositories.txt
  repositories.txt
Labels: topic: submission

#4903 Update repositories.txt
  repositories.txt
Labels: topic: submission

#4905 Update repositories.txt
  repositories.txt
Labels: topic: submission

#4906 Add https://github.com/mathieucarbou/MycilaPulseAnalyzer
  repositories.txt
Labels: topic: submission
