Repository arduino/library-registry, pull requests merged in 2024-04, with the labels that each got.

#4293 Update repositories.txt
  repositories.txt
Labels: topic: submission

#4294 Update repositories.txt
  repositories.txt
Labels: topic: submission

#4295 Update repositories.txt
  repositories.txt
Labels: topic: submission

#4296 Update repositories.txt
  repositories.txt
Labels: topic: submission

#4297 Update repositories.txt
  repositories.txt
Labels: topic: submission

#4299 Update repositories.txt
  repositories.txt
Labels: topic: submission

#4301 Asyncbtn
  repositories.txt
Labels: topic: submission

#4302 Update repositories.txt
  repositories.txt
Labels: topic: submission

#4303 Update repositories.txt
  repositories.txt
Labels: topic: submission

#4282 Remove "Blynk For Chinese"
  registry.txt
Labels: topic: removal, status: pending backend

#4281 remove https://github.com/hznupeter/blynk-library-for-chinese
  repositories.txt
Labels: topic: removal, status: pending backend

#4292 Remove "GLCD"
  registry.txt
Labels: topic: removal, status: pending backend

#4290 Update repositories.txt
  repositories.txt
Labels: topic: modification, status: pending backend

#4305 Update name of "SNP_Sensor"
  registry.txt
Labels: topic: rename, status: pending backend

#4306 Update repositories.txt
  repositories.txt
Labels: topic: submission

#4308 Update repositories.txt
  repositories.txt
Labels: topic: submission

#4314 Add MessagingLib
  repositories.txt
Labels: topic: submission

#4318 Update repositories.txt
  repositories.txt
Labels: topic: submission

#4320 Update repositories.txt
  repositories.txt
Labels: topic: submission

#4321 Update repositories.txt
  repositories.txt
Labels: topic: submission

#4323 Update repositories.txt
  repositories.txt
Labels: topic: submission

#4324 Added LilyGo-EPD47 library
  repositories.txt
Labels: topic: submission

#4330 Update repositories.txt
  repositories.txt
Labels: topic: submission

#4334 Add CWH Lantern Library
  repositories.txt
Labels: topic: submission

#4331 Update repositories.txt to add Arduino_Cellular
  repositories.txt
Labels: topic: submission

#4335 Update repositories.txt
  repositories.txt
Labels: topic: submission

#4336 Adding bosejis_Types library
  repositories.txt
Labels: topic: submission

#4337 Update repositories.txt
  repositories.txt
Labels: topic: submission

#4338 Update repositories.txt
  repositories.txt
Labels: topic: submission

#4332 Update name and URL of "M5PoECAM"
  registry.txt
Labels: topic: URL change, topic: rename, status: pending backend

#4325 Rename Lib PoECAM
  repositories.txt
Labels: topic: URL change, status: pending backend

#4315 Update URL of "dhtESP32-rmt"
  registry.txt
Labels: topic: URL change, status: pending backend

#4316 Update URL of "esp32-ds18b20"
  registry.txt
Labels: topic: URL change, status: pending backend

#4307 updated new url
  repositories.txt
Labels: topic: URL change, status: pending backend

#4333 Update URL of "BasicColorLedControl"
  registry.txt
Labels: topic: URL change, status: pending backend

#4319 Update repositories.txt
  repositories.txt
Labels: topic: URL change, status: pending backend

#4343 Adding bosejis_AMV Library
  repositories.txt
Labels: topic: submission

#4344 Update repositories.txt
  repositories.txt
Labels: topic: submission

#4346 Add https://github.com/board707/DMD_STM32
  repositories.txt
Labels: topic: submission

#4347 Add Modulino library
  repositories.txt
Labels: topic: submission

#4348 Update repositories.txt
  repositories.txt
Labels: topic: submission

#4352 Update repositories.txt
  repositories.txt
Labels: topic: submission

#4353 Update repositories.txt
  repositories.txt
Labels: topic: submission

#4354 Add library for IP2368 QC/PD charging control IC
  repositories.txt
Labels: topic: submission

#4356 Add AX-Mini library
  repositories.txt
Labels: topic: submission

#4357 chore: add new unified repo to library manager
  repositories.txt
Labels: topic: submission

#4358 Update repositories.txt
  repositories.txt
Labels: topic: submission

#4364 Add Hanuman library
  repositories.txt
Labels: topic: submission

#4369 add SunFounder Power Control
  repositories.txt
Labels: topic: submission

#4372 Update repositories.txt
  repositories.txt
Labels: topic: submission

#4374 Update repositories.txt
  repositories.txt
Labels: topic: submission

#4376 Update repositories.txt
  repositories.txt
Labels: topic: submission

#4378 Update repositories.txt
  repositories.txt
Labels: topic: submission

#4361 Update URL of "FastLEDHub"
  registry.txt
Labels: topic: URL change, status: pending backend

#4359 Update library urls for ESPEssentials and FastLEDHub
  repositories.txt
Labels: topic: URL change, status: pending backend

#4384 Update repositories.txt
  repositories.txt
Labels: topic: submission

#4386 Update repositories.txt
  repositories.txt
Labels: topic: submission

#4387 Add Arduino_LowPowerPortentaH7 library
  repositories.txt
Labels: topic: submission

#4388 Added LoRaWAN_ESP32
  repositories.txt
Labels: topic: submission

#4389 Add mathieucarbou/AsyncTCP
  repositories.txt
Labels: topic: submission

#4391 Rupertobot library
  repositories.txt
Labels: topic: submission

#4396 Update repositories.txt
  repositories.txt
Labels: topic: submission

#4397 Add my lib
  repositories.txt
Labels: topic: submission

#4401 Update repositories.txt
  repositories.txt
Labels: topic: submission

#4404 Filter Easy
  repositories.txt
Labels: topic: submission

#4405 Update repositories.txt
  repositories.txt
Labels: topic: submission

#4406 Update repositories.txt
  repositories.txt
Labels: topic: submission

#4407 Update repositories.txt
  repositories.txt
Labels: topic: submission

#4408 Adding Boseji's TWI Library
  repositories.txt
Labels: topic: submission

#4409 Update repositories.txt
  repositories.txt
Labels: topic: submission

#4411 Update repositories.txt
  repositories.txt
Labels: topic: submission

#4418 Add SparkFun u-blox PointPerfect library
  repositories.txt
Labels: topic: submission

#4419 Add IM19 IMU Library
  repositories.txt
Labels: topic: submission

#4421 Added Mc74hc595a library
  repositories.txt
Labels: topic: submission

#4423 Add Seeed Arduino SSCMA
  repositories.txt
Labels: topic: submission

#4424 Update repositories.txt
  repositories.txt
Labels: topic: submission

#4427 Update repositories.txt
  repositories.txt
Labels: topic: submission

#4383 Update name of "Sensirion I2C STS3x"
  registry.txt
Labels: topic: rename, status: pending backend

#4429 Update repositories.txt
  repositories.txt
Labels: topic: submission

#4430 Add new library Link to Update repositories.txt
  repositories.txt
Labels: topic: submission

#4434 Update repositories.txt
  repositories.txt
Labels: topic: submission

#4435 Update repositories.txt
  repositories.txt
Labels: topic: submission

#4436 add lib
  repositories.txt
Labels: topic: submission

#4437 Add Pictiva_OS288048
  repositories.txt
Labels: topic: submission

#4445 Add library RUI3-Arduino-Library
  repositories.txt
Labels: topic: submission

#4451 Update repositories.txt
  repositories.txt
Labels: topic: submission

#4382 Update name of "Sensirion I2C SHT3x"
  registry.txt
Labels: topic: rename, status: pending backend

#4417 Update URL of "AISwitch"
  registry.txt
Labels: topic: URL change, status: pending backend

#4410 Revert "Update repositories.txt"
  repositories.txt
Labels: topic: removal

#4400 Update name of "PI3EQX12908A2"
  registry.txt
Labels: topic: rename, status: pending backend

#4444 Update name of "BlynkGate"
  registry.txt
Labels: topic: rename, status: pending backend

#4432 Update URL of "PID_v2"
  registry.txt
Labels: topic: URL change, status: pending backend

#4431 Username change
  repositories.txt
Labels: topic: URL change, status: pending backend

#4461 Added Heltec_LoRa_OLED_Examples
  repositories.txt
Labels: topic: submission

#4464 Added mcu-renderer library
  repositories.txt
Labels: topic: submission

#4465 Added mcu-max library
  repositories.txt
Labels: topic: submission

#4466 add https://github.com/RCMgames/BSCD
  repositories.txt
Labels: topic: submission
