Repository arduino/library-registry, pull requests merged in 2024-01, with the labels that each got.

#3830 Update repositories.txt
  repositories.txt
Labels: topic: submission

#3831 Add TCXWriter library
  repositories.txt
Labels: topic: submission

#3832 Update repositories.txt
  repositories.txt
Labels: topic: submission

#3833 Added Trill library
  repositories.txt
Labels: topic: submission

#3835 Add PanelLan library
  repositories.txt
Labels: topic: submission

#3836 +tflm_esp32
  repositories.txt
Labels: topic: submission

#3837 +tflm_cortexm
  repositories.txt
Labels: topic: submission

#3838 Update repositories.txt
  repositories.txt
Labels: topic: submission

#3844 Update repositories.txt
  repositories.txt
Labels: topic: submission

#3846 Update repositories.txt
  repositories.txt
Labels: topic: submission

#3848 Update repositories.txt
  repositories.txt
Labels: topic: submission

#3850 Add Animation library
  repositories.txt
Labels: topic: submission

#3851 Add EZ_USB_MIDI_HOST Library
  repositories.txt
Labels: topic: submission

#3853 add lib
  repositories.txt
Labels: topic: submission

#3854 Update repositories.txt
  repositories.txt
Labels: topic: submission

#3855 Update repositories.txt
  repositories.txt
Labels: topic: submission

#3856 Update repositories.txt
  repositories.txt
Labels: topic: submission

#3857 Update repositories.txt
  repositories.txt
Labels: topic: submission

#3858 Update repositories.txt
  repositories.txt
Labels: topic: submission

#3861 Update repositories.txt
  repositories.txt
Labels: topic: submission

#3864 Adding my library TCS230_ESP32 in repositories.txt
  repositories.txt
Labels: topic: submission

#3865 Update repositories.txt
  repositories.txt
Labels: topic: submission

#3866 add https://github.com/teamprof/arduprof
  repositories.txt
Labels: topic: submission

#3870 Update repositories.txt
  repositories.txt
Labels: topic: submission

#3873 let's see if this is the last time
  repositories.txt
Labels: topic: submission

#3874 Update repositories.txt
  repositories.txt
Labels: topic: submission

#3875 Add ENGR100-950
  repositories.txt
Labels: topic: submission

#3876 Add ESPAsyncWebServer
  repositories.txt
Labels: topic: submission

#3877 Update repositories.txt
  repositories.txt
Labels: topic: submission

#3862 Update name of "MicroAnimation"
  registry.txt
Labels: topic: rename, status: pending backend

#3840 Remove "Kojay"
  registry.txt
Labels: topic: removal, status: pending backend

#3803 Removal of YH-Choi-001/Kojay library
  repositories.txt
Labels: topic: removal, status: pending backend

#3841 Remove "OtaHelper"
  registry.txt
Labels: topic: removal, status: pending backend

#3808 Delete my library
  repositories.txt
Labels: topic: removal, status: pending backend

#3863 Remove "diwa"
  registry.txt
Labels: topic: removal, status: pending backend

#3860 Update repositories.txt
  repositories.txt
Labels: topic: removal, status: pending backend

#3878 Update repositories.txt
  repositories.txt
Labels: topic: submission

#3879 Update repositories.txt
  repositories.txt
Labels: topic: submission

#3880 Adding a library for 2.4GHz Lora Functionaliy
  repositories.txt
Labels: topic: submission

#3882 Update repositories.txt
  repositories.txt
Labels: topic: submission

#3881 Update repositories.txt
  repositories.txt
Labels: topic: submission

#3883 Update repositories.txt
  repositories.txt
Labels: topic: submission

#3885 Update repositories.txt
  repositories.txt
Labels: topic: submission

#3886 Update repositories.txt
  repositories.txt
Labels: topic: submission

#3887 Update repositories.txt
  repositories.txt
Labels: topic: submission

#3888 Update repositories.txt
  repositories.txt
Labels: topic: submission

#3893 Update repositories.txt
  repositories.txt
Labels: topic: submission

#3901 Update repositories.txt
  repositories.txt
Labels: topic: submission

#3902 Update repositories.txt
  repositories.txt
Labels: topic: submission

#3903 Add https://github.com/simonlmn/gpiobj
  repositories.txt
Labels: topic: submission

#3904 Add https://github.com/simonlmn/esp-iot-core
  repositories.txt
Labels: topic: submission

#3906 ConfigPortal8266
  repositories.txt
Labels: topic: submission

#3907 ConfigPortal8266 retry
  repositories.txt
Labels: topic: submission

#3909 Add https://github.com/simonlmn/serial-transport
  repositories.txt
Labels: topic: submission

#3910 Update repositories.txt
  repositories.txt
Labels: topic: submission

#3911 Update repositories: add Arduino_PortentaMachineControl lib
  repositories.txt
Labels: topic: submission

#3912 Update repositories.txt
  repositories.txt
Labels: topic: submission

#3914 very small changes
  repositories.txt
Labels: topic: submission

#3916 Update repositories.txt
  repositories.txt
Labels: topic: submission

#3919 Update repositories.txt
  repositories.txt
Labels: topic: submission

#3920 Update repositories.txt
  repositories.txt
Labels: topic: submission

#3921 Update repositories.txt - Add SimplifiedTimer
  repositories.txt
Labels: topic: submission

#3922 Update repositories.txt
  repositories.txt
Labels: topic: submission

#3925 Update repositories.txt
  repositories.txt
Labels: topic: submission

#3926 RTC3231
  repositories.txt
Labels: topic: submission

#3930 Update repositories.txt
  repositories.txt
Labels: topic: submission

#3931 Update repositories.txt
  repositories.txt
Labels: topic: submission

#3929 Update repositories.txt
  repositories.txt
Labels: topic: submission

#3934 Added https://github.com/kaiaai/LDS
  repositories.txt
Labels: topic: submission

#3936 Add mathieucarbou/MycilaLogger
  repositories.txt
Labels: topic: submission

#3937 Add mathieucarbou/MycilaConfig
  repositories.txt
Labels: topic: submission

#3939 Update repositories.txt
  repositories.txt
Labels: topic: submission

#3940 Add mathieucarbou/MycilaJSY
  repositories.txt
Labels: topic: submission

#3942 Add mathieucarbou/MycilaESPConnect
  repositories.txt
Labels: topic: submission

#3943 Add mathieucarbou/MycilaRelay
  repositories.txt
Labels: topic: submission

#3944 Update repositories.txt
  repositories.txt
Labels: topic: submission

#3945 Add mjbots/moteus-arduino
  repositories.txt
Labels: topic: submission

#3947 Update repositories.txt
  repositories.txt
Labels: topic: submission

#3948 Added LilyGo T-RGB library
  repositories.txt
Labels: topic: submission

#3949 Update repositories.txt
  repositories.txt
Labels: topic: submission

#3950 Update repositories.txt
  repositories.txt
Labels: topic: submission

#3951 Add mathieucarbou/MycilaTaskMonitor
  repositories.txt
Labels: topic: submission

#3933 Update name of "gpiobj"
  registry.txt
Labels: topic: rename, status: pending backend

#3932 Update name of "esp-iot-core"
  registry.txt
Labels: topic: rename, status: pending backend

#3953 Add WMS7202DigitalPotentiometer to repositories.txt
  repositories.txt
Labels: topic: submission

#3954 Add mathieucarbou/MycilaNTP
  repositories.txt
Labels: topic: submission

#3955 Update repositories.txt
  repositories.txt
Labels: topic: submission

#3957 Update repositories.txt
  repositories.txt
Labels: topic: submission

#3958 Add mathieucarbou/MycilaHADiscovery
  repositories.txt
Labels: topic: submission

#3961 Update repositories.txt
  repositories.txt
Labels: topic: submission

#3962 Update repositories.txt
  repositories.txt
Labels: topic: submission

#3963 Adding PID_DG library
  repositories.txt
Labels: topic: submission

#3964 Add mathieucarbou/MycilaMQTT
  repositories.txt
Labels: topic: submission

#3968 added EspNowCam library
  repositories.txt
Labels: topic: submission

#3969 Update repositories.txt
  repositories.txt
Labels: topic: submission

#3970 Add DEIS CLAIRE-mgmt library
  repositories.txt
Labels: topic: submission

#3971 Add WindSensorHWD_asukiaaa
  repositories.txt
Labels: topic: submission

#3972 Update repositories.txt
  repositories.txt
Labels: topic: submission

#3974 Update repositories.txt
  repositories.txt
Labels: topic: submission

#3952 sorting repos
  repositories.txt
Labels: type: enhancement, topic: other

#3975 Add RAKwireless_RAK14000_EPD_2_13
  repositories.txt
Labels: topic: submission

#3976 Add https://github.com/simonlmn/jsons and https://github.com/simonlmn/toolbox
  repositories.txt
Labels: topic: submission
