Repository arduino/library-registry, pull requests merged in 2024-11, with the labels that each got.

#5333 Update repositories.txt
  repositories.txt
Labels: topic: submission

#5334 Update repositories.txt
  repositories.txt
Labels: topic: submission

#5335 Adding SerialLogger
  repositories.txt
Labels: topic: submission

#5336 Adding ultiblox libraries
  repositories.txt
Labels: topic: submission

#5338 Add GoogleSchedular
  repositories.txt
Labels: topic: submission

#5339 Adding libraries
  repositories.txt
Labels: topic: submission

#5342 chore: add a library about SGP30
  repositories.txt
Labels: topic: submission

#5343 Update repositories.txt
  repositories.txt
Labels: topic: submission

#5346 Update repositories.txt
  repositories.txt
Labels: topic: submission

#5352 Add Sequent Microsystems Sixteen relays card library
  repositories.txt
Labels: topic: submission

#5353 Update repositories.txt
  repositories.txt
Labels: topic: submission

#5356 added GrayCode library
  repositories.txt
Labels: topic: submission

#5358 Adding library
  repositories.txt
Labels: topic: submission

#5360 Update repositories.txt
  repositories.txt
Labels: topic: submission

#5370 Update repositories.txt
  repositories.txt
Labels: topic: submission

#5373 Add MINDS-i-Trailer Repo
  repositories.txt
Labels: topic: submission

#5374 Update repositories.txt
  repositories.txt
Labels: topic: submission

#5376 added solarfunctions lib
  repositories.txt
Labels: topic: submission

#5377 Update repositories.txt
  repositories.txt
Labels: topic: submission

#5375 Update repositories.txt
  repositories.txt
Labels: topic: submission

#5379 Update repositories.txt
  repositories.txt
Labels: topic: submission

#5380 Update repositories.txt
  repositories.txt
Labels: topic: submission

#5390 Update repositories.txt
  repositories.txt
Labels: topic: submission

#5394 Update repositories.txt
  repositories.txt
Labels: topic: submission

#5397 Update repositories.txt
  repositories.txt
Labels: topic: submission

#5399 Add MINDS-i Foundations
  repositories.txt
Labels: topic: submission

#5404 Update repositories.txt
  repositories.txt
Labels: topic: submission

#5405 Update repositories.txt
  repositories.txt
Labels: topic: submission

#5381 Update name of "UltiBlox-SerialLogger"
  registry.txt
Labels: topic: rename, status: pending backend

#5383 Update name of "UltiBlox-Examples"
  registry.txt
Labels: topic: rename, status: pending backend

#5382 Update name of "UltiBlox-LCDI2C"
  registry.txt
Labels: topic: rename, status: pending backend

#5384 Update name of "UltiBlox-DisplayValueOLED"
  registry.txt
Labels: conclusion: resolved, topic: rename, status: pending backend

#5386 Update name of "UltiBlox-DisplayValueLCD"
  registry.txt
Labels: topic: rename, status: pending backend

#5387 Update name of "UltiBlox-SensorAnalog"
  registry.txt
Labels: topic: rename, status: pending backend

#5349 Update URL of "Cpp_Standard_Library"
  registry.txt
Labels: topic: URL change, status: pending backend

#5351 Update URL of "TimersOneForAll"
  registry.txt
Labels: topic: URL change, status: pending backend

#5396 Update URL of "LightMDNS"
  registry.txt
Labels: topic: URL change, status: pending backend

#5395 rename ArduinoLightMDNS to LightMDNS
  repositories.txt
Labels: topic: URL change, status: pending backend

#5401 Remove "MINDSi"
  registry.txt
Labels: topic: removal, status: pending backend

#5402 Remove "MINDS-i-Trailer"
  registry.txt
Labels: topic: removal, status: pending backend

#5403 Remove "MINDS-i-Utils"
  registry.txt
Labels: topic: removal, status: pending backend

#5400 Remove Obsolete MINDS-i Repos
  repositories.txt
Labels: topic: removal, status: pending backend

#5369 Update URL of "PxServ"
  registry.txt
Labels: topic: URL change, status: pending backend

#5368 Update repositories.txt
  repositories.txt
Labels: topic: URL change, status: pending backend

#5372 Update URL of "IRMP"
  registry.txt
Labels: topic: URL change, status: pending backend

#5371 Changed "ukw100/IRMP" to "IRMP-org/IRMP", because it is permanently moved anyway
  repositories.txt
Labels: topic: URL change, status: pending backend

#5406 Add arduino-yl800n library
  repositories.txt
Labels: topic: submission

#5415 Update repositories.txt
  repositories.txt
Labels: topic: submission

#5418 Add SparkFun LG290P library
  repositories.txt
Labels: topic: submission

#5420 Update repositories.txt
  repositories.txt
Labels: topic: submission

#5424 Update repositories.txt
  repositories.txt
Labels: topic: submission

#5426 Update repositories.txt to add lautisilber/SmartComm library
  repositories.txt
Labels: topic: submission

#5427 Update repositories.txt
  repositories.txt
Labels: topic: submission

#5429 Update repositories.txt
  repositories.txt
Labels: topic: submission

#5433 GBALib_UltrasonicSensor
  repositories.txt
Labels: topic: submission

#5436 Add XY2-100
  repositories.txt
Labels: topic: submission

#5438 Added https://github.com/pschatzmann/TalkiePCM
  repositories.txt
Labels: topic: submission

#5439 https://github.com/blasilli/GBALib_ShiftRegister
  repositories.txt
Labels: topic: submission

#5441 Update repositories.txt
  repositories.txt
Labels: topic: submission

#5442 Update repositories.txt
  repositories.txt
Labels: topic: submission

#5443 Update repositories.txt
  repositories.txt
Labels: topic: submission

#5446 Update repositories.txt
  repositories.txt
Labels: topic: submission

#5448 Update repositories.txt
  repositories.txt
Labels: topic: submission

#5451 Add SparkFun I2C Expander library
  repositories.txt
Labels: topic: submission

#5454 Update repositories.txt
  repositories.txt
Labels: topic: submission

#5455 Add WsprEncoded to repositories.txt
  repositories.txt
Labels: topic: submission

#5456 Update repositories.txt
  repositories.txt
Labels: topic: submission

#5457 Update repositories.txt
  repositories.txt
Labels: topic: submission

#5458 Update repositories.txt
  repositories.txt
Labels: topic: submission

#5460 Update repositories.txt
  repositories.txt
Labels: topic: submission

#5461 Update repositories.txt
  repositories.txt
Labels: topic: submission

#5462 Add galvo-controller
  repositories.txt
Labels: topic: submission

#5463 Update repositories.txt
  repositories.txt
Labels: topic: submission

#5464 Add asukiaaa/arduino-OrientalBLVR
  repositories.txt
Labels: topic: submission

#5465 Add asukiaaa/arduino-OrientalAZ
  repositories.txt
Labels: topic: submission

#5466 Update repositories.txt
  repositories.txt
Labels: topic: submission

#5469 Update repositories.txt
  repositories.txt
Labels: topic: submission

#5472 Update repositories.txt
  repositories.txt
Labels: topic: submission

#5473 Update repositories.txt
  repositories.txt
Labels: topic: submission

#5475 Added ConsentiumIoT starter kit code
  repositories.txt
Labels: topic: submission

#5476 Update repositories.txt
  repositories.txt
Labels: topic: submission

#5477 Add ESP8266 SMTPClient Library
  repositories.txt
Labels: topic: submission

#5474 Update repositories.txt
  repositories.txt
Labels: topic: submission

#5413 Update name of "UltiBlox-DisplayValueNull"
  registry.txt
Labels: topic: rename, status: pending backend

#5412 Update URL of "Proyectil digitalIO"
  registry.txt
Labels: topic: URL change, status: pending backend

#5409 v1.0.1 ProyectilMx digitalIO
  repositories.txt
Labels: topic: modification

#5414 Remove "UltiBlox DisplayValueCommon"
  registry.txt
Labels: topic: removal, status: pending backend

#5411 Removing deprecated library
  repositories.txt
Labels: topic: removal, status: pending backend

#5431 Remove "IP2366"
  registry.txt
Labels: topic: removal, status: pending backend

#5452 remove IP2366 library
  repositories.txt
Labels: topic: removal, status: pending backend

#5478 Update repositories.txt
  repositories.txt
Labels: topic: submission

#5479 Adding UltiBlox-SerialCommands library
  repositories.txt
Labels: topic: submission

#5483 Added SmartSW libary to the repositories
  repositories.txt
Labels: topic: submission

#5484 Add Sensirion arduino-i2c-sen66 lib
  repositories.txt
Labels: topic: submission

#5487 Update repositories.txt
  repositories.txt
Labels: topic: submission

#5488 Add my library link
  repositories.txt
Labels: topic: submission

#5489 Add AsyncWebSerial
  repositories.txt
Labels: topic: submission

#5490 Add AsyncOTA
  repositories.txt
Labels: topic: submission

#5492 Update repositories.txt
  repositories.txt
Labels: topic: submission

#5493 EmotiBit KTD2026
  repositories.txt
Labels: topic: submission
