Repository arduino/library-registry, pull requests merged in 2024-05, with the labels that each got.

#4485 Update repositories.txt
  repositories.txt
Labels: topic: submission

#4486 Added https://github.com/ripred/SmartPin
  repositories.txt
Labels: topic: submission

#4484 Update repositories.txt
  repositories.txt
Labels: topic: submission

#4488 Add Epson_PNL_CE02 library
  repositories.txt
Labels: topic: submission

#4494 add lib
  repositories.txt
Labels: topic: submission

#4495 Added Pixel Spork Library
  repositories.txt
Labels: topic: submission

#4496 Adding bosejis_PString Library
  repositories.txt
Labels: topic: submission

#4497 Update repositories.txt
  repositories.txt
Labels: topic: submission

#4498 Update repositories.txt
  repositories.txt
Labels: topic: submission

#4499 Added Arduino Alvik related repos
  repositories.txt
Labels: topic: submission

#4500 Update repositories.txt
  repositories.txt
Labels: topic: submission

#4502 Add OptaUSBUpdate library
  repositories.txt
Labels: topic: submission

#4504 Adding Adafruit S-35710
  repositories.txt
Labels: topic: submission

#4505 Update repositories.txt
  repositories.txt
Labels: topic: submission

#4506 Update repositories.txt
  repositories.txt
Labels: topic: submission

#4507 Add PicoWebsocket library
  repositories.txt
Labels: topic: submission

#4508 add PicoEncoder to repositories.txt
  repositories.txt
Labels: topic: submission

#4510 Added LilyGO-T-Wristband-and-T-Glass library
  repositories.txt
Labels: topic: submission

#4511 PID-Autotune library
  repositories.txt
Labels: topic: submission

#4513 Update repositories.txt
  repositories.txt
Labels: topic: submission

#4491 Update name of "Mechasolution R finder10D"
  registry.txt
Labels: topic: rename, status: pending backend

#4492 Remove "TTN_M5Stack"
  registry.txt
Labels: topic: removal, status: pending backend

#4493 Remove "LoRaWan_esp32"
  registry.txt
Labels: topic: removal, status: pending backend

#4439 Update repositories.txt
  repositories.txt
Labels: topic: removal, status: pending backend

#4480 Update URL of "LiquidCrystal I2C"
  registry.txt
Labels: topic: URL change, status: pending backend

#4479 fix LiquidCrystal_I2C url
  repositories.txt
Labels: topic: modification, status: pending backend

#4503 Update URL of "byte-sized-encoder-decoder"
  registry.txt
Labels: topic: URL change, status: pending backend

#4501 change url of library request
  repositories.txt
Labels: topic: modification, status: pending backend

#4463 Remove "fa3el_khar"
  registry.txt
Labels: topic: removal, status: pending backend

#4462 Remove "fa3el_khar"
  repositories.txt
Labels: topic: removal, status: pending backend

#4341 [AE-319] Replace `Partner` and `Recommened` in `registry.txt`
  registry.txt
Labels: topic: type change, status: pending backend

#4516 Add Arduino_CloudConnectionFeedback
  repositories.txt
Labels: topic: submission

#4517 Update repositories.txt
  repositories.txt
Labels: topic: submission

#4518 Request to add library to official library list
  repositories.txt
Labels: topic: submission

#4519 Update repositories.txt
  repositories.txt
Labels: topic: submission

#4520 Update repositories.txt
  repositories.txt
Labels: topic: submission

#4522 Adding Boseji's Bin Library
  repositories.txt
Labels: topic: submission

#4523 Adding M5-SX127x Library
  repositories.txt
Labels: topic: submission

#4533 Update repositories.txt
  repositories.txt
Labels: topic: submission

#4534 Added CSE_MillisTimer
  repositories.txt
Labels: topic: submission

#4536 Added independent libraries
  repositories.txt
Labels: topic: submission

#4537 Added callables independent
  repositories.txt
Labels: topic: submission

#4539 Update repositories.txt
  repositories.txt
Labels: topic: submission

#4540 Add hideakitai/ADS1220
  repositories.txt
Labels: topic: submission

#4543 Update repositories.txt
  repositories.txt
Labels: topic: submission

#4545 Added CSE_CircularBuffer
  repositories.txt
Labels: topic: submission

#4546 Update repositories.txt with Boodskap IoT Digital Twin Library
  repositories.txt
Labels: topic: submission

#4544 Update repositories.txt
  repositories.txt
Labels: topic: submission

#4547 Added dependent libraries
  repositories.txt
Labels: topic: submission

#4548 Update repositories.txt
  repositories.txt
Labels: topic: submission

#4552 https://github.com/Sam4uk/WD.Easy
  repositories.txt
Labels: topic: submission

#4553 Update repositories.txt
  repositories.txt
Labels: topic: submission

#4557 Update repositories.txt
  repositories.txt
Labels: topic: submission

#4558 Update repositories.txt
  repositories.txt
Labels: topic: submission

#4559 feat: add hideakitai/LTC230x
  repositories.txt
Labels: topic: submission

#4560 Add MotorGo Mini Driver
  repositories.txt
Labels: topic: submission

#4561 Update repositories.txt
  repositories.txt
Labels: topic: submission

#4562 Update repositories.txt
  repositories.txt
Labels: topic: submission

#4564 Update repositories.txt
  repositories.txt
Labels: topic: submission

#4567 Add Bas.SinglePinDevice
  repositories.txt
Labels: topic: submission

#4556 Retire "GSM"
  registry.txt
Labels: topic: type change, status: pending backend

#4526 Update URL of "EthernetENC"
  registry.txt
Labels: topic: URL change, status: pending backend

#4527 Update URL of "NetApiHelpers"
  registry.txt
Labels: topic: URL change, status: pending backend

#4542 Update lib url of library "led"
  repositories.txt
Labels: topic: URL change, status: pending backend

#4568 Update repositories.txt
  repositories.txt
Labels: topic: submission

#4569 Update repositories.txt
  repositories.txt
Labels: topic: submission

#4570 Added EasyPreferences library
  repositories.txt
Labels: topic: submission

#4571 Update repositories.txt
  repositories.txt
Labels: topic: submission

#4572 Add asukiaaa/arduino-MCP4661
  repositories.txt
Labels: topic: submission

#4573 Added Franzininho Wifi Lab DIY lib
  repositories.txt
Labels: topic: submission

#4574 Update repositories.txt
  repositories.txt
Labels: topic: submission

#4575 Update repositories.txt
  repositories.txt
Labels: topic: submission

#4578 Update repositories.txt
  repositories.txt
Labels: topic: submission

#4579 Update repositories.txt
  repositories.txt
Labels: topic: submission

#4580 Update repositories.txt
  repositories.txt
Labels: topic: submission

#4581 Update repositories.txt
  repositories.txt
Labels: topic: submission

#4583 Update repositories.txt
  repositories.txt
Labels: topic: submission

#4587 Update repositories.txt
  repositories.txt
Labels: topic: submission

#4588 Update repositories.txt
  repositories.txt
Labels: topic: submission

#4589 Update repositories.txt
  repositories.txt
Labels: topic: submission

#4592 Update repositories.txt
  repositories.txt
Labels: topic: submission

#4593 add libs
  repositories.txt
Labels: topic: submission

#4594 Add SparkFun Qwiic OTOS Library
  repositories.txt
Labels: topic: submission

#4595 Update repositories.txt
  repositories.txt
Labels: topic: submission

#4596 Update repositories.txt
  repositories.txt
Labels: topic: submission

#4597 Update repositories.txt
  repositories.txt
Labels: topic: submission

#4598 Update repositories.txt
  repositories.txt
Labels: topic: submission

#4602 Update repositories.txt
  repositories.txt
Labels: topic: submission
