Repository arduino/library-registry, pull requests merged in 2024-08, with the labels that each got.

#4904 Update repositories.txt
  repositories.txt
Labels: topic: submission

#4909 Update repositories.txt
  repositories.txt
Labels: topic: submission

#4858 Remove "ArdUAV"
  registry.txt
Labels: topic: removal, status: pending backend

#4859 Remove "Autopilot"
  registry.txt
Labels: topic: removal, status: pending backend

#4860 Remove "navduino"
  registry.txt
Labels: topic: removal, status: pending backend

#4861 Remove "NEO-6M_GPS"
  registry.txt
Labels: topic: removal, status: pending backend

#4862 Remove "UM7"
  registry.txt
Labels: topic: removal, status: pending backend

#4878 Remove ArdUAV, navduino, and other libs
  repositories.txt
Labels: topic: removal, status: pending backend

#4916 Update repositories.txt
  repositories.txt
Labels: topic: submission

#4917 Add friends of audio-tools
  repositories.txt
Labels: topic: submission

#4918 Update repositories.txt to add OnlyTimer library
  repositories.txt
Labels: topic: submission

#4919 Update repositories.txt to add sinricpro-arduino-renesas-sdk library
  repositories.txt
Labels: topic: submission

#4923 TimerOne_V2
  repositories.txt
Labels: topic: submission

#4924 Update repositories.txt
  repositories.txt
Labels: topic: submission

#4945 Update repositories.txt for new library
  repositories.txt
Labels: topic: submission

#4946 Update repositories.txt
  repositories.txt
Labels: topic: submission

#4947 Adding roo_prefs to repositories.txt
  repositories.txt
Labels: topic: submission

#4948 Added roo_control to the repositories.txt
  repositories.txt
Labels: topic: submission

#4949 Added roo_wifi to repositories.txt.
  repositories.txt
Labels: topic: submission

#4950 Adding roo_windows to repositories.txt.
  repositories.txt
Labels: topic: submission

#4952 Adding roo_temperature to repositories.txt.
  repositories.txt
Labels: topic: submission

#4953 Adds https://github.com/workloads/scservo
  repositories.txt
Labels: topic: submission

#4951 Update repositories.txt
  repositories.txt
Labels: topic: submission

#4925 Remove "audio-driver"
  registry.txt
Labels: topic: removal, status: pending backend

#4926 Remove "audio-tools"
  registry.txt
Labels: topic: removal, status: pending backend

#4929 Remove "libhelix"
  registry.txt
Labels: topic: removal, status: pending backend

#4934 Remove "libopus"
  registry.txt
Labels: topic: removal, status: pending backend

#4932 Remove "libLAME"
  registry.txt
Labels: topic: removal, status: pending backend

#4928 Remove "fdk-aac"
  registry.txt
Labels: topic: removal, status: pending backend

#4933 Remove "libMAD"
  registry.txt
Labels: conclusion: resolved, topic: removal, status: pending backend

#4935 Remove "libsbc"
  registry.txt
Labels: conclusion: resolved, topic: removal, status: pending backend

#4937 Update URL of "Matrix Mini Library"
  registry.txt
Labels: topic: URL change, status: pending backend

#4930 Update URL of MatrixMini
  repositories.txt
Labels: topic: URL change, status: pending backend

#4955 Update URL of "Alfredo-NoU3"
  registry.txt
Labels: topic: URL change, status: pending backend

#4954 Update repositories.txt - Library name change for Alfredo_NoU3
  repositories.txt
Labels: topic: URL change, status: pending backend

#4956 Update repositories.txt
  repositories.txt
Labels: topic: submission

#4957 Added TeeGrid to repositories.txt
  repositories.txt
Labels: topic: submission

#4958 Update repositories.txt
  repositories.txt
Labels: topic: submission

#4959 Update repositories.txt
  repositories.txt
Labels: topic: submission

#4960 Update repositories.txt
  repositories.txt
Labels: topic: submission

#4962 Update repositories.txt
  repositories.txt
Labels: topic: submission

#4961 Update repositories.txt
  repositories.txt
Labels: topic: submission

#4963 Update repositories.txt
  repositories.txt
Labels: topic: submission

#4964 Update repositories.txt
  repositories.txt
Labels: topic: submission

#4965 Add FM25060 library to library-registry
  repositories.txt
Labels: topic: submission

#4966 Update repositories.txt
  repositories.txt
Labels: topic: submission

#4967 add AvrFHT library
  repositories.txt
Labels: topic: submission

#4968 Add thirstyice/TinyDMXSerial
  repositories.txt
Labels: topic: submission

#4969 add lib
  repositories.txt
Labels: topic: submission

#4970 Update repositories.txt
  repositories.txt
Labels: topic: submission

#4971 Update repositories.txt
  repositories.txt
Labels: topic: submission

#4972 Update repositories.txt
  repositories.txt
Labels: topic: submission

#4973 Update repositories.txt
  repositories.txt
Labels: topic: submission

#4974 Update repositories.txt
  repositories.txt
Labels: topic: submission

#4979 Update Library Manager reference links in FAQ
  FAQ.md
Labels: topic: other

#4976 Remove "EspNowNetwork"
  registry.txt
Labels: topic: removal, status: pending backend

#4975 Remove EspNowNetwork
  repositories.txt
Labels: topic: removal, status: pending backend

#4980 add lib
  repositories.txt
Labels: topic: submission

#4981 Add Spartan Edge Accelerator ESP32 boot library
  repositories.txt
Labels: topic: submission

#4982 Update repositories.txt
  repositories.txt
Labels: topic: submission

#4983 Update repositories.txt
  repositories.txt
Labels: topic: submission

#4985 Add AD7747
  repositories.txt
Labels: topic: submission

#4986 Adding avandalen/avdweb_CodeDebugScope
  repositories.txt
Labels: topic: submission

#4990 R4A_ESP32: Add Robots-For-All ESP32 support library
  repositories.txt
Labels: topic: submission

#4992 Update repositories.txt
  repositories.txt
Labels: topic: submission

#4993 Update repositories.txt
  repositories.txt
Labels: topic: submission

#4994 Add BluetoothTerminal library
  repositories.txt
Labels: topic: submission

#4996 Add Arduino_LowPowerPortentaC33 library
  repositories.txt
Labels: topic: submission

#4997 Update repositories.txt
  repositories.txt
Labels: topic: submission

#4999 Add Filters Lib
  repositories.txt
Labels: topic: submission

#5003 Update repositories.txt
  repositories.txt
Labels: topic: submission

#5006 Update repositories.txt
  repositories.txt
Labels: topic: submission

#5010 Update repositories.txt
  repositories.txt
Labels: topic: submission

#5011 Update repositories.txt
  repositories.txt
Labels: topic: submission

#5016 Update repositories.txt
  repositories.txt
Labels: topic: submission

#5021 Added DCS-Skunkworks/dcs-bios-arduino-library
  repositories.txt
Labels: topic: submission

#5024 Request to add a library for IMU
  repositories.txt
Labels: topic: submission

#5028 Update repositories.txt
  repositories.txt
Labels: topic: submission

#5031 Update repositories.txt
  repositories.txt
Labels: topic: submission

#5033 Update repositories.txt
  repositories.txt
Labels: topic: submission

#5034 Update repositories.txt
  repositories.txt
Labels: topic: submission

#5038 Update repositories.txt
  repositories.txt
Labels: topic: submission

#5040 Update repositories.txt for AMY
  repositories.txt
Labels: topic: submission

#5041 Update repositories.txt
  repositories.txt
Labels: topic: submission

#5043 Update repositories.txt
  repositories.txt
Labels: topic: submission

#5044 Added libs for ST7789 and GC9A01A
  repositories.txt
Labels: topic: submission

#5045 Update repositories.txt
  repositories.txt
Labels: topic: submission
