Repository arduino/library-registry, pull requests merged in 2024-09, with the labels that each got.

#5046 Update repositories.txt
  repositories.txt
Labels: topic: submission

#5050 Update repositories.txt
  repositories.txt
Labels: topic: submission

#5053 Add avr-fast-div
  repositories.txt
Labels: topic: submission

#5054 Add avr-fast-shift
  repositories.txt
Labels: topic: submission

#5055 R4A_I2C: Add Robots-For-All I2C support library
  repositories.txt
Labels: topic: submission

#5056 R4A_Robot: Add Robots-For-All Robot support library
  repositories.txt
Labels: topic: submission

#5057 Configure actions/upload-artifact action to upload required hidden files
  .github/workflows/check-go-dependencies-task.yml
Labels: topic: infrastructure, type: imperfection

#5058 add lib
  repositories.txt
Labels: topic: submission

#5062 Update repositories.txt
  repositories.txt
Labels: topic: submission

#5064 Add new library
  repositories.txt
Labels: topic: submission

#5061 [skip-changelog] Configure actions/upload-artifact action to upload required hidden files
  .github/workflows/manage-prs.yml
Labels: topic: infrastructure, type: imperfection

#5065 Update repositories.txt
  repositories.txt
Labels: topic: submission

#5066 Update repositories.txt
  repositories.txt
Labels: topic: submission

#5068 Update repositories.txt
  repositories.txt
Labels: topic: submission

#5070 Update repositories.txt
  repositories.txt
Labels: topic: submission

#5071 Add Arduino_PowerManagement library
  repositories.txt
Labels: topic: submission

#5072 Update repositories.txt
  repositories.txt
Labels: topic: submission

#5073 Update repositories.txt
  repositories.txt
Labels: topic: submission

#5074 Added DigiFont
  repositories.txt
Labels: topic: submission

#5076 Update repositories.txt
  repositories.txt
Labels: topic: submission

#5077 XRA1405 library
  repositories.txt
Labels: topic: submission

#5080 Add thirstyice/Olimex16x2
  repositories.txt
Labels: topic: submission

#5081 feat: add deploii-library to repositories.txt
  repositories.txt
Labels: topic: submission

#5083 Update repositories.txt
  repositories.txt
Labels: topic: submission

#5084 Add thirstyice/RedEye
  repositories.txt
Labels: topic: submission

#5085 Add ENS22 library
  repositories.txt
Labels: topic: submission

#5086 Add EEPROMReader lib
  repositories.txt
Labels: topic: submission

#5087 Update repositories.txt
  repositories.txt
Labels: topic: submission

#5088 Add 9704 Launch Pad library to repositories.txt
  repositories.txt
Labels: topic: submission

#5027 Update name of "DCS-BIOS"
  registry.txt
Labels: topic: rename, status: pending backend

#5018 Remove "ESP32CAR"
  registry.txt
Labels: topic: removal, status: pending backend

#5017 Update repositories.txt
  repositories.txt
Labels: topic: removal, status: pending backend

#5092 Update name of "Iridium9704LaunchPad"
  registry.txt
Labels: topic: rename, status: pending backend

#5002 Remove "INSARIANNE"
  registry.txt
Labels: topic: removal, status: pending backend

#5000 Update repositories.txt
  repositories.txt
Labels: topic: removal, status: pending backend

#5008 Remove "ESP32 Firebase"
  registry.txt
Labels: topic: removal, status: pending backend

#5009 Remove "ESP8266 Firebase"
  registry.txt
Labels: topic: removal, status: pending backend

#5022 Remove "ESP32 Webhook"
  registry.txt
Labels: topic: removal, status: pending backend

#5023 Remove "ESP8266 Webhook"
  registry.txt
Labels: topic: removal, status: pending backend

#5005 Update repositories.txt
  repositories.txt
Labels: topic: removal, status: pending backend

#5020 Update URL of "CodeDebugScope"
  registry.txt
Labels: topic: URL change, status: pending backend

#5019 Update repositories.txt for new URL of CodeDebugScope Library
  repositories.txt
Labels: topic: URL change, status: pending backend

#5051 Update repositories.txt
  repositories.txt
Labels: topic: URL change, status: pending backend

#5096 Update repositories.txt
  repositories.txt
Labels: topic: submission

#5069 Update name and URL of "24s02ya__M24SR02-Y"
  registry.txt
Labels: conclusion: resolved, topic: URL change, topic: rename, status: pending backend

#5067 Update repositories.txt
  repositories.txt
Labels: topic: modification

#5097 add SCL3400 lib
  repositories.txt
Labels: topic: submission

#5098 Update repositories.txt
  repositories.txt
Labels: topic: submission

#5099 Update repositories.txt
  repositories.txt
Labels: topic: submission

#5100 add new lib: TLE9879-BLDC-Shield
  repositories.txt
Labels: topic: submission

#5101 The Elio board is a UART communication interface board for Arduino.
  repositories.txt
Labels: topic: submission

#5102 Added my Posit library
  repositories.txt
Labels: topic: submission

#5103 Update repositories.txt
  repositories.txt
Labels: topic: submission

#5104 Update repositories.txt
  repositories.txt
Labels: topic: submission

#5105 Add thirstyice/JVC-Stereo
  repositories.txt
Labels: topic: submission

#5107 Add new library DS1307
  repositories.txt
Labels: topic: submission

#5110 Update repositories.txt
  repositories.txt
Labels: topic: submission

#5111 added SeeedNrf52480Battery and GaussianFilter1D
  repositories.txt
Labels: topic: submission

#5112 Update repositories.txt
  repositories.txt
Labels: topic: submission

#5113 Update repositories.txt
  repositories.txt
Labels: topic: submission

#5115 Develop　Update repositories.txt (#5114)
  repositories.txt
Labels: topic: submission

#5116 Update repositories.txt
  repositories.txt
Labels: topic: submission

#5117 Update repositories.txt
  repositories.txt
Labels: topic: submission

#5109 Update URL of "EdgeNeuron"
  registry.txt
Labels: topic: URL change, status: pending backend

#5108 Update URL of "ConsentiumThings"
  registry.txt
Labels: topic: URL change, status: pending backend

#5106 Changed ConsentiumInc to ConsentiumIoT
  repositories.txt
Labels: topic: modification

#5119 Update name of "Soldered Ultrasonic Distance Sensor Arduino library"
  registry.txt
Labels: topic: rename, status: pending backend

#5120 Update URL of "Switch"
  registry.txt
Labels: topic: URL change, status: pending backend

#5114 Update repositories.txt for new URL of avdweb_Switch Library
  repositories.txt
Labels: topic: modification

#5121 Added the new libraries to support the AIOT boards
  repositories.txt
Labels: topic: submission

#5122 Update repositories.txt
  repositories.txt
Labels: topic: submission

#5123 Update repositories.txt
  repositories.txt
Labels: topic: submission

#5124 add TinyScheduler library
  repositories.txt
Labels: topic: submission

#5126 Update repositories.txt
  repositories.txt
Labels: topic: submission

#5127 New Library Publishing Request: RustyKeypad
  repositories.txt
Labels: topic: submission

#5128 Update repositories.txt to include GItHub TcMenu/TcMenuLog library
  repositories.txt
Labels: topic: submission

#5142 Upload Freenove_RFID_Lib_for_Pico Library
  repositories.txt
Labels: topic: submission

#5154 added parameter and esp-now-midi libraries
  repositories.txt
Labels: topic: submission

#5161 add TinyIO library
  repositories.txt
Labels: topic: submission

#5162 Add avr-fast-map
  repositories.txt
Labels: topic: submission

#5163 Add Labvee Library
  repositories.txt
Labels: topic: submission

#5168 Update repositories.txt
  repositories.txt
Labels: topic: submission

#5170 Update repositories.txt
  repositories.txt
Labels: topic: submission

#5172 Update repositories.txt
  repositories.txt
Labels: topic: submission

#5174 Update repositories.txt
  repositories.txt
Labels: topic: submission

#5178 New Library Request: RustyVoltmeter
  repositories.txt
Labels: topic: submission

#5179 Update repositories.txt
  repositories.txt
Labels: topic: submission

#5180 Update repositories.txt
  repositories.txt
Labels: topic: submission

#5181 Update repositories.txt
  repositories.txt
Labels: topic: submission

#5183 Add library - RoboCore BRIICK Keypad
  repositories.txt
Labels: topic: submission
