Repository arduino/library-registry, pull requests merged in 2025-01, with the labels that each got.

#5707 Update repositories.txt
  repositories.txt
Labels: topic: submission

#5709 Stackmq Library Submission
  repositories.txt
Labels: topic: submission

#5715 Update repositories.txt
  repositories.txt
Labels: topic: submission

#5716 Update repositories.txt
  repositories.txt
Labels: topic: submission

#5718 Add CHT832X
  repositories.txt
Labels: topic: submission

#5721 Added My Library
  repositories.txt
Labels: topic: submission

#5725 Add AirNgin ESP32 MQTT Client library
  repositories.txt
Labels: topic: submission

#5728 APDS9900 sensor
  repositories.txt
Labels: topic: submission

#5729 Update repositories.txt for edge-ai-arduino-library
  repositories.txt
Labels: topic: submission

#5731 Update repositories.txt
  repositories.txt
Labels: topic: submission

#5733 Update repositories.txt
  repositories.txt
Labels: topic: submission

#5735 Update repositories.txt
  repositories.txt
Labels: topic: submission

#5737 Update repositories.txt
  repositories.txt
Labels: topic: submission

#5738 Add EnviroDIY GeoluxHydroCam
  repositories.txt
Labels: topic: submission

#5739 Update repositories.txt
  repositories.txt
Labels: topic: submission

#5742 Please add FastEPD to the library manager
  repositories.txt
Labels: topic: submission

#5743 Update repositories.txt
  repositories.txt
Labels: topic: submission

#5744 Update repositories.txt
  repositories.txt
Labels: topic: submission

#5748 Update repositories.txt
  repositories.txt
Labels: topic: submission

#5752 Update repositories.txt
  repositories.txt
Labels: topic: submission

#5754 Add Library Registry access control system
  .github/CONTRIBUTING.md
  .github/workflows/assets/accesslist.yml
  .github/workflows/manage-prs.yml
  FAQ.md
  README.md
Labels: type: enhancement, topic: code

#5775 update repository.txt
  repositories.txt
Labels: topic: submission

#5613 Update repositories.txt
  repositories.txt
Labels: topic: URL change, status: pending backend

#5633 Update repositories.txt
  repositories.txt
Labels: topic: URL change, status: pending backend

#5659 Remove "Grove Serial MP3 Player V2.0"
  registry.txt
Labels: topic: removal, status: pending backend

#5655 chore: delete the url of old "MP3 Player"
  repositories.txt
Labels: topic: removal, status: pending backend

#5697 Remove "inIo" registration
  registry.txt
Labels: topic: removal, status: pending backend

#5696 Remove "inIo" from repository list
  repositories.txt
Labels: topic: removal, status: pending backend

#5711 Remove duplicate "FoonteDuino" registration
  registry.txt
Labels: topic: removal, status: pending backend

#5710 Remove duplicate "FoonteDuino" from repositories list
  repositories.txt
Labels: topic: removal, status: pending backend

#5713 Remove "7SemiSHT4x_Library"
  registry.txt
Labels: topic: removal, status: pending backend

#5756 Remove "FonnteArduino"
  registry.txt
Labels: topic: removal, status: pending backend

#5719 Update repositories.txt
  repositories.txt
Labels: topic: removal

#5724 Update URL of "IO22_IO_Board"
  registry.txt
Labels: topic: URL change, status: pending backend

#5723 update IO22_IO_Board url
  repositories.txt
Labels: topic: URL change, status: pending backend

#5755 Remove "7SemiSHT4x_Lib"
  registry.txt
Labels: topic: removal, status: pending backend

#5757 Remove "KelasRobotTime" from repository list
  repositories.txt
Labels: topic: removal, status: pending backend

#5761 Remove "KelasRobotIO" from repository list
  repositories.txt
Labels: topic: removal, status: pending backend

#5760 Remove "MQTTESP"
  registry.txt
Labels: topic: removal, status: pending backend

#5759 Remove "MQTTESP" from repository list
  repositories.txt
Labels: topic: removal

#5766 Remove "BTRobocontrol"
  registry.txt
Labels: topic: removal, status: pending backend

#5764 Remove "I2CR-CPP"
  registry.txt
Labels: topic: removal, status: pending backend

#5763 Remove "I2CR-CPP" from repository list
  repositories.txt
Labels: topic: removal, status: pending backend

#5768 Remove "ERLtechRobotcontrol"
  registry.txt
Labels: topic: removal, status: pending backend

#5770 Remove "ERLtech-RobotControl"
  registry.txt
Labels: topic: removal, status: pending backend

#5769 Remove "ERLtech-RobotControl" from repository list
  repositories.txt
Labels: topic: removal

#5772 Remove "RobotControl"
  registry.txt
Labels: topic: removal, status: pending backend

#5771 Remove "RobotControl" from repositories list
  repositories.txt
Labels: topic: removal, status: pending backend

#5782 Arduino library for CC1101 transceiver.
  repositories.txt
Labels: topic: submission

#5786 Update repositories.txt
  repositories.txt
Labels: topic: submission

#5787 add LCDI2C_Multilingual_MCD
  repositories.txt
Labels: topic: submission

#5789 Add EnviroDIY LoRa_AT
  repositories.txt
Labels: topic: submission

#5788 Update repositories.txt
  repositories.txt
Labels: topic: submission

#5791 Update repositories.txt
  repositories.txt
Labels: topic: submission

#5794 Update repositories.txt
  repositories.txt
Labels: topic: submission

#5795 Update repositories.txt
  repositories.txt
Labels: topic: submission

#5796 Update repositories.txt
  repositories.txt
Labels: topic: submission

#5797 Update repositories.txt
  repositories.txt
Labels: topic: submission

#5798 Add lib
  repositories.txt
Labels: topic: submission

#5799 Added Pervasive_Wide_Small
  repositories.txt
Labels: topic: submission

#5800 Update repositories.txt
  repositories.txt
Labels: topic: submission

#5801 Update repositories.txt
  repositories.txt
Labels: topic: submission

#5802 Add https://github.com/ESP32Async/ESPAsyncTCP
  repositories.txt
Labels: topic: submission

#5806 Update repositories.txt
  repositories.txt
Labels: topic: submission

#5809 Update repositories.txt
  repositories.txt
Labels: topic: submission

#5810 Added https://github.com/PervasiveDisplays/Pervasive_BWRY_Small
  repositories.txt
Labels: topic: submission

#5811 Update repositories.txt
  repositories.txt
Labels: topic: submission

#5813 Update repositories.txt
  repositories.txt
Labels: topic: submission

#5814 Added Inkplate MOTION library
  repositories.txt
Labels: topic: submission

#5816 Update repositories.txt
  repositories.txt
Labels: topic: submission

#5817 Update repositories.txt
  repositories.txt
Labels: topic: submission

#5818 Update repositories.txt
  repositories.txt
Labels: topic: submission

#5819 add https://github.com/jakiki6/SH1106
  repositories.txt
Labels: topic: submission

#5820 Update repositories.txt
  repositories.txt
Labels: topic: submission

#5822 Added libdivide
  repositories.txt
Labels: topic: submission

#5830 Update repositories.txt
  repositories.txt
Labels: topic: submission

#5831 Update repositories.txt
  repositories.txt
Labels: topic: submission

#5833 Update repositories.txt
  repositories.txt
Labels: topic: submission

#5835 Update repositories.txt
  repositories.txt
Labels: topic: submission

#5836 SCConfig added
  repositories.txt
Labels: topic: submission

#5837 Add RTC_DS1307_Library to repositories.txt
  repositories.txt
Labels: topic: submission

#5838 Update repositories.txt
  repositories.txt
Labels: topic: submission

#5839 Update repositories.txt
  repositories.txt
Labels: topic: submission

#5840 Update repositories.txt
  repositories.txt
Labels: topic: submission

#5841 Update repositories.txt
  repositories.txt
Labels: topic: submission

#5843 Update repositories.txt
  repositories.txt
Labels: topic: submission

#5844 Update repositories.txt
  repositories.txt
Labels: topic: submission

#5850 fixed fork of https://github.com/closedcube/ClosedCube_SHT31D_Arduino
  repositories.txt
Labels: topic: submission

#5852 Update repositories.txt
  repositories.txt
Labels: topic: submission

#5853 Update repositories.txt
  repositories.txt
Labels: topic: submission

#5854 Update repositories.txt
  repositories.txt
Labels: topic: submission

#5858 Update repositories.txt
  repositories.txt
Labels: topic: submission
