Repository arduino/library-registry, pull requests merged in 2025-04, with the labels that each got.

#6134 Add my Arduino library to the library manager
  repositories.txt
Labels: topic: submission

#6135 Update repositories.txt
  repositories.txt
Labels: topic: submission

#6137 Update repositories.txt
  repositories.txt
Labels: topic: submission

#6156 Update repositories.txt
  repositories.txt
Labels: topic: submission

#6157 Update repositories.txt
  repositories.txt
Labels: topic: submission

#6158 Update repositories.txt
  repositories.txt
Labels: topic: submission

#6160 Added IsraEB/esp32cam repo
  repositories.txt
Labels: topic: submission

#6161 Update repositories.txt
  repositories.txt
Labels: topic: submission

#6164 Update repositories.txt
  repositories.txt
Labels: topic: submission

#6166 Update repositories.txt
  repositories.txt
Labels: topic: submission

#6168 Update repositories.txt
  repositories.txt
Labels: topic: submission

#6169 Update repositories.txt
  repositories.txt
Labels: topic: submission

#6170 Update repositories.txt
  repositories.txt
Labels: topic: submission

#6171 Update repositories.txt
  repositories.txt
Labels: topic: submission

#6173 Update repositories.txt
  repositories.txt
Labels: topic: submission

#6174 add M5Unit-KMeterISO
  repositories.txt
Labels: topic: submission

#6128 Update name of "DCF77RX"
  registry.txt
Labels: topic: rename, status: pending backend

#6080 Remove "Yfrobot Fingerprint Identification Sensor Library"
  registry.txt
Labels: topic: removal, status: pending backend

#6139 Add "Retired" type to "Arduino Uno WiFi Dev Ed Library"
  registry.txt
Labels: topic: type change, status: pending backend

#6140 Add "Retired" type to "Arduino_AVRSTL"
  registry.txt
Labels: topic: type change, status: pending backend

#6141 Add "Retired" type to "Arduino_CRC32"
  registry.txt
Labels: topic: type change, status: pending backend

#6143 Add "Retired" type to "Arduino_KNN"
  registry.txt
Labels: topic: type change, status: pending backend

#6144 Add "Retired" type to "ArduinoCloudThing"
  registry.txt
Labels: topic: type change, status: pending backend

#6145 Add "Retired" type to "ArduinoIoTCloudBearSSL"
  registry.txt
Labels: topic: type change, status: pending backend

#6146 Add "Retired" type to "Bridge"
  registry.txt
Labels: topic: type change, status: pending backend

#6147 Add "Retired" type to "Ciao"
  registry.txt
Labels: topic: type change, status: pending backend

#6148 Add "Retired" type to "Esplora"
  registry.txt
Labels: topic: type change, status: pending backend

#6150 Add "Retired" type to "MKRMotorCarrier"
  registry.txt
Labels: topic: type change, status: pending backend

#6151 Add "Retired" type to "PhysicsLabFirmware"
  registry.txt
Labels: conclusion: resolved, topic: type change, status: pending backend

#6153 Add "Retired" type to "Robot Motor"
  registry.txt
Labels: topic: type change, status: pending backend

#6154 Add "Retired" type to "SpacebrewYun"
  registry.txt
Labels: conclusion: resolved, topic: type change, status: pending backend

#6175 Update repositories.txt
  repositories.txt
Labels: topic: submission

#6155 Add "Retired" type to "WiFi Link"
  registry.txt
Labels: topic: type change, status: pending backend

#6178 Update repositories.txt
  repositories.txt
Labels: topic: submission

#6180 Update repositories.txt
  repositories.txt
Labels: topic: submission

#6182 Update repositories.txt
  repositories.txt
Labels: topic: submission

#6186 Add PicoBricks Library
  repositories.txt
Labels: topic: submission

#6187 Update repositories.txt
  repositories.txt
Labels: topic: submission

#6190 Add Am Alert Lib
  repositories.txt
Labels: topic: submission

#6192 Update repositories.txt
  repositories.txt
Labels: topic: submission

#6196 Update repositories.txt
  repositories.txt
Labels: topic: submission

#6200 Add KVStore library
  repositories.txt
Labels: topic: submission

#6202 Update repositories.txt
  repositories.txt
Labels: topic: submission

#6204 Add kywy library
  repositories.txt
Labels: topic: submission

#6205 Add SmallButton library
  repositories.txt
Labels: topic: submission

#6206 Update repositories.txt
  repositories.txt
Labels: topic: submission

#6207 Added BMP180 Library
  repositories.txt
Labels: topic: submission

#6208 Update repositories.txt
  repositories.txt
Labels: topic: submission

#6211 Update repositories.txt
  repositories.txt
Labels: topic: submission

#6213 Update repositories.txt
  repositories.txt
Labels: topic: submission

#6210 Add Arducam_Qwiic_CAM_Arduino library
  repositories.txt
Labels: topic: submission

#6185 Update URL of "tinyml4all"
  registry.txt
Labels: topic: URL change, status: pending backend

#6177 Update repositories.txt
  repositories.txt
Labels: topic: modification, status: pending backend

#6216 Update repositories.txt
  repositories.txt
Labels: topic: submission

#6218 Update repositories.txt
  repositories.txt
Labels: topic: submission

#6219 Update repositories.txt New library MultiFTP
  repositories.txt
Labels: topic: submission

#6220 Update repositories.txt
  repositories.txt
Labels: topic: submission

#6221 Update repositories.txt
  repositories.txt
Labels: topic: submission

#6215 Add KeypadSim
  repositories.txt
Labels: topic: submission

#6226 Update repositories.txt add miniiot
  repositories.txt
Labels: topic: submission

#6227 Update repositories.txt
  repositories.txt
Labels: topic: submission

#6230 add DFRobot_C4001 lib
  repositories.txt
Labels: topic: submission

#6231 Update repositories.txt
  repositories.txt
Labels: topic: submission

#6232 Update repositories.txt
  repositories.txt
Labels: topic: submission

#6233 Update repositories.txt
  repositories.txt
Labels: topic: submission

#6234 Add M5Unit-EXTIO
  repositories.txt
Labels: topic: submission

#6236 add M5Module-Audio Lib
  repositories.txt
Labels: topic: submission

#6237 Update repositories.txt
  repositories.txt
Labels: topic: submission

#6240 Update repositories.txt
  repositories.txt
Labels: topic: submission

#6241 Update repositories.txt
  repositories.txt
Labels: topic: submission

#6242 feat: add minimal Task scheduler
  repositories.txt
Labels: topic: submission

#6247 Update repositories.txt
  repositories.txt
Labels: topic: submission

#6248 Update repositories.txt
  repositories.txt
Labels: topic: submission

#6249 Add LP5562 library
  repositories.txt
Labels: topic: submission

#6251 Update repositories.txt
  repositories.txt
Labels: topic: submission

#6253 Add TI BQ25798 library
  repositories.txt
Labels: topic: submission
