Repository arduino/library-registry, pull requests merged in 2025-02, with the labels that each got.

#5859 Update repositories.txt
  repositories.txt
Labels: topic: submission

#5860 Request to add QwiicUART Library to Registry
  repositories.txt
Labels: topic: submission

#5861 Update repositories.txt
  repositories.txt
Labels: topic: submission

#5862 Add library for TLC59116
  repositories.txt
Labels: topic: submission

#5863 Add SerialServo lib to the list
  repositories.txt
Labels: topic: submission

#5864 Update repositories.txt
  repositories.txt
Labels: topic: submission

#5865 Update repositories.txt
  repositories.txt
Labels: topic: submission

#5866 Update repositories.txt
  repositories.txt
Labels: topic: submission

#5867 Add libraries - RoboCore BRIICK Encoder & TRIAC
  repositories.txt
Labels: topic: submission

#5868 Add TotemRoboboard
  repositories.txt
Labels: topic: submission

#5869 Update repositories.txt
  repositories.txt
Labels: topic: submission

#5871 Update repositories.txt
  repositories.txt
Labels: topic: submission

#5807 Update URL of "Async TCP"
  registry.txt
Labels: topic: URL change, status: pending backend

#5808 Update URL of "ESP Async WebServer"
  registry.txt
Labels: topic: URL change, status: pending backend

#5804 Switch repository URL for official ESPAsyncWebServer library to https://github.com/ESP32Async/ESPAsyncWebServer
  repositories.txt
Labels: topic: modification

#5856 Update URL of "MorseEncoder"
  registry.txt
Labels: topic: URL change, status: pending backend

#5855 change repo url of `MorseEncoder`
  repositories.txt
Labels: conclusion: resolved, topic: URL change, status: pending backend

#5857 Add library for RG15 rain sensor
  repositories.txt
Labels: topic: submission

#5876 Update repositories.txt
  repositories.txt
Labels: topic: submission

#5877 Update repositories.txt
  repositories.txt
Labels: topic: submission

#5878 Update repositories.txt
  repositories.txt
Labels: topic: submission

#5879 New Library
  repositories.txt
Labels: topic: submission

#5886 Update repositories.txt
  repositories.txt
Labels: topic: submission

#5887 Update repositories.txt
  repositories.txt
Labels: topic: submission

#5888 Update repositories.txt
  repositories.txt
Labels: topic: submission

#5891 Request to add PrayerTimes to Arduino Library Manager
  repositories.txt
Labels: topic: submission

#5892 To add: EventEmitter v1.0.0
  repositories.txt
Labels: topic: submission

#5893 Add MicroConfig
  repositories.txt
Labels: topic: submission

#5894 Add Libraries for Modbus TCP Communication
  repositories.txt
Labels: topic: submission

#5895 Update repositories.txt
  repositories.txt
Labels: topic: submission

#5896 Add BitFlash_Client Library
  repositories.txt
Labels: topic: submission

#5898 Add ESP32_Host_MIDI to repositories.txt
  repositories.txt
Labels: topic: submission

#5899 Update repositories.txt
  repositories.txt
Labels: topic: submission

#5904 Update repositories.txt
  repositories.txt
Labels: topic: submission

#5905 Update repositories.txt
  repositories.txt
Labels: topic: submission

#5909 Update repositories.txt
  repositories.txt
Labels: topic: submission

#5910 M5Unit-THERMO
  repositories.txt
Labels: topic: submission

#5911 M5Unit-COLOR
  repositories.txt
Labels: topic: submission

#5913 M5Unit-ANADIG
  repositories.txt
Labels: topic: submission

#5914 AMS AS5040 magnetic rotary encoder driver inclusion to repositories.txt
  repositories.txt
Labels: topic: submission

#5915 Add Rotary_encoder library
  repositories.txt
Labels: topic: submission

#5917 GrafikSerial library to log and plot data to your GrafikStudio dashboard
  repositories.txt
Labels: topic: submission

#5918 Update repositories.txt
  repositories.txt
Labels: topic: submission

#5919 Update repositories.txt
  repositories.txt
Labels: topic: submission

#5920 Add asukiaaa/arduino-MotorDMKB4
  repositories.txt
Labels: topic: submission

#5923 Update repositories.txt
  repositories.txt
Labels: topic: submission

#5924 Add VoltLora Library – Simplified LoRa Communication for Arduino
  repositories.txt
Labels: topic: submission

#5925 Update repositories.txt
  repositories.txt
Labels: topic: submission

#5926 Update repositories.txt
  repositories.txt
Labels: topic: submission

#5928 Update repositories.txt
  repositories.txt
Labels: topic: submission

#5929 M5Unit-ASR
  repositories.txt
Labels: topic: submission

#5931 Update repositories.txt
  repositories.txt
Labels: topic: submission

#5936 add Adafruit_DACX578
  repositories.txt
Labels: topic: submission

#5937 Add EventBasedFramework (EBF)
  repositories.txt
Labels: topic: submission

#5938 Update repositories.txt
  repositories.txt
Labels: topic: submission

#5939 Update repositories.txt
  repositories.txt
Labels: topic: submission

#5940 Update repositories.txt
  repositories.txt
Labels: topic: submission

#5941 Add ArtronShop_LineMessaging Lib
  repositories.txt
Labels: topic: submission

#5942 Update repositories.txt
  repositories.txt
Labels: topic: submission

#5943 Add ArduinoMessageBus Library
  repositories.txt
Labels: topic: submission

#5946 Update repositories.txt
  repositories.txt
Labels: topic: submission

#5947 Update repositories.txt
  repositories.txt
Labels: topic: submission

#5948 Update repositories.txt
  repositories.txt
Labels: topic: submission

#5949 added hmueller01/pubsubclient3
  repositories.txt
Labels: topic: submission

#5950 Added https://github.com/dac1e/RtcDueRcf
  repositories.txt
Labels: topic: submission

#5951 Added CSE_CST328
  repositories.txt
Labels: topic: submission

#5952 Update URL of "BS811X_I2C"
  repositories.txt
Labels: topic: submission

#5957 Update repositories.txt
  repositories.txt
Labels: topic: submission

#5958 Update repositories.txt
  repositories.txt
Labels: topic: submission

#5960 IoT
  repositories.txt
Labels: topic: submission

#5965 Added RPAsyncTCP
  repositories.txt
Labels: topic: submission

#5966 Update repositories.txt
  repositories.txt
Labels: topic: submission

#5967 Update repositories.txt
  repositories.txt
Labels: topic: submission

#5968 Update repositories.txt
  repositories.txt
Labels: topic: submission

#5969 Update repositories.txt
  repositories.txt
Labels: topic: submission

#5874 Update URL of "YDLidar"
  registry.txt
Labels: topic: URL change, status: pending backend

#5875 Update URL of "QuickESPNow"
  registry.txt
Labels: topic: URL change, status: pending backend

#5873 So i moved the libraries prperties to the hyperion since i made the f…
  repositories.txt
Labels: topic: URL change, status: pending backend

#5932 Remove "PDLS_EXT3_Basic_BWRY"
  registry.txt
Labels: topic: removal, status: pending backend

#5933 Remove "PDLS_EXT3_Basic_Touch"
  registry.txt
Labels: topic: removal, status: pending backend

#5934 Remove "PDLS_EXT3_Basic_Wide"
  registry.txt
Labels: topic: removal, status: pending backend

#5921 Deprecated libraries
  repositories.txt
Labels: topic: removal, status: pending backend

#5935 Update URL of "MPC_ruih"
  registry.txt
Labels: topic: URL change, status: pending backend

#5922 Update repositories.txt
  repositories.txt
Labels: topic: URL change, status: pending backend

#5962 Update URL of "ESP32 HUB75 LED MATRIX PANEL DMA Display"
  registry.txt
Labels: topic: URL change, status: pending backend

#5963 Update URL of "Json Streaming Parser 2"
  registry.txt
Labels: topic: URL change, status: pending backend

#5964 Remove "WiFiConnect Lite"
  registry.txt
Labels: topic: removal, status: pending backend

#5953 Update repositories.txt
  repositories.txt
Labels: topic: URL change, topic: removal, status: pending backend

#5973 Update repositories.txt
  repositories.txt
Labels: topic: submission

#5974 Update repositories.txt
  repositories.txt
Labels: topic: submission

#5975 Update repositories.txt
  repositories.txt
Labels: topic: submission

#5976 Update repositories.txt
  repositories.txt
Labels: topic: submission

#5977 Update repositories.txt
  repositories.txt
Labels: topic: submission

#5978 Update repositories.txt
  repositories.txt
Labels: topic: submission

#5979 Update repositories.txt, added https://github.com/dac1e/Dcf77Receiver
  repositories.txt
Labels: topic: submission

#5980 Added TTP229_BS81X_Serial
  repositories.txt
Labels: topic: submission

#5981 Update repositories.txt
  repositories.txt
Labels: topic: submission

#5983 Add Sensirion I2C SFM3304 Lib
  repositories.txt
Labels: topic: submission

#5985 Add L298lib Library
  repositories.txt
Labels: topic: submission

#5984 GitHub IoT
  repositories.txt
Labels: topic: submission

#5994 Update repositories.txt
  repositories.txt
Labels: topic: submission

#5995 Update repositories.txt
  repositories.txt
Labels: topic: submission

#5996 Added StatefulGSMLib
  repositories.txt
Labels: topic: submission

#6000 Update repositories.txt - FlipDotMatrix
  repositories.txt
Labels: topic: submission

#6002 Update repositories.txt
  repositories.txt
Labels: topic: submission

#6003 Update repositories.txt
  repositories.txt
Labels: topic: submission

#6004 Add SparkFun TCXO and OCXO libraries
  repositories.txt
Labels: topic: submission

#6005 Update repositories.txt
  repositories.txt
Labels: topic: submission
