Repository arduino/library-registry, pull requests merged in 2025-03, with the labels that each got.

#6009 add BIDFest Tools
  repositories.txt
Labels: topic: submission

#6010 Update repositories.txt
  repositories.txt
Labels: topic: submission

#6011 Add https://github.com/qqqlab/qqqlab-RP2040-Toolbox
  repositories.txt
Labels: topic: submission

#6012 Add Arduino_CloudUtils library
  repositories.txt
Labels: topic: submission

#6013 Update repositories.txt
  repositories.txt
Labels: topic: submission

#6015 YFS201 Sensor
  repositories.txt
Labels: topic: submission

#6017 Update repositories.txt
  repositories.txt
Labels: topic: submission

#6019 Update repositories.txt
  repositories.txt
Labels: topic: submission

#6021 Update repositories.txt
  repositories.txt
Labels: topic: submission

#6022 Added SCPI Red Pitaya arduino library
  repositories.txt
Labels: topic: submission

#6014 Update repositories.txt
  repositories.txt
Labels: topic: submission

#6023 Update repositories.txt
  repositories.txt
Labels: topic: submission

#6025 Added https://github.com/ripred/Minimax
  repositories.txt
Labels: topic: submission

#6026 Update repositories.txt
  repositories.txt
Labels: topic: submission

#6027 Update repositories.txt
  repositories.txt
Labels: topic: submission

#6029 Update repositories.txt
  repositories.txt
Labels: topic: submission

#6030 Update repositories.txt
  repositories.txt
Labels: topic: submission

#6028 Update repositories.txt
  repositories.txt
Labels: topic: submission

#6032 Update repositories.txt
  repositories.txt
Labels: topic: submission

#6033 Added SensorHub library
  repositories.txt
Labels: topic: submission

#6034 Update repositories.txt
  repositories.txt
Labels: topic: submission

#6035 Update repository
  repositories.txt
Labels: topic: submission

#6036 Add LedDisplayFonts library
  repositories.txt
Labels: topic: submission

#5987 Remove "MsTime"
  registry.txt
Labels: conclusion: resolved, topic: removal, status: pending backend

#5982 Update repositories.txt
  repositories.txt
Labels: topic: removal

#5992 Update URL of "SMV_CAN_Bus'
  registry.txt
Labels: topic: URL change, status: pending backend

#5989 Update UCLA-SMV-CAN Library URL
  repositories.txt
Labels: topic: URL change, status: pending backend

#5998 Remove "TabahiConsole"
  registry.txt
Labels: topic: removal, status: pending backend

#5997 Remove TabahiConsole
  repositories.txt
Labels: topic: removal, status: pending backend

#6008 Update URL of "Dcf77Receiver"
  registry.txt
Labels: topic: URL change, status: pending backend

#6001 Renamed https://github.com/dac1e/Dcf77Receiver to https://github.com/…
  repositories.txt
Labels: topic: URL change, status: pending backend

#6038 Update repositories.txt
  repositories.txt
Labels: topic: submission

#6039 Update repositories.txt
  repositories.txt
Labels: topic: submission

#6046 Add TMC51X0
  repositories.txt
Labels: topic: submission

#6047 Add My Stepper8825Lib.
  repositories.txt
Labels: topic: submission

#6048 Add SensEdu-Library
  repositories.txt
Labels: topic: submission

#6049 add Litime_BMS_ESP32
  repositories.txt
Labels: topic: submission

#6054 Add PIDEasy library for PID control
  repositories.txt
Labels: topic: submission

#6055 BME688 Environmental Sensor Library
  repositories.txt
Labels: topic: submission

#6060 MPM10 PM Sensor library
  repositories.txt
Labels: topic: submission

#6061 ML8511 UV Sensor Library
  repositories.txt
Labels: topic: submission

#6062 APDS9960 Library
  repositories.txt
Labels: topic: submission

#6063 ADS111 Series ADC Library
  repositories.txt
Labels: topic: submission

#6064 Update repositories.txt
  repositories.txt
Labels: topic: submission

#6066 Update repositories.txt
  repositories.txt
Labels: topic: submission

#6045 Add qp-arduino
  repositories.txt
Labels: topic: submission

#6068 Add PicoSyslog
  repositories.txt
Labels: topic: submission

#6069 Update repositories.txt
  repositories.txt
Labels: topic: submission

#6070 feat: Add RTOScppESP32
  repositories.txt
Labels: topic: submission

#6072 Update repositories.txt
  repositories.txt
Labels: topic: submission

#6073 Update repositories.txt
  repositories.txt
Labels: topic: submission

#6077 Update repositories.txt
  repositories.txt
Labels: topic: submission

#6078 Update repositories.txt
  repositories.txt
Labels: topic: submission

#6081 Add DShot library for RP2040
  repositories.txt
Labels: topic: submission

#6082 add M5StamPLC Library
  repositories.txt
Labels: topic: submission

#6084 Winduino
  repositories.txt
Labels: topic: submission

#6085 Update repositories.txt
  repositories.txt
Labels: topic: submission

#6086 Update repositories.txt
  repositories.txt
Labels: topic: submission

#6087 HTTPWebServer
  repositories.txt
Labels: topic: submission

#6088 Add ATD-S3 Driver Library | HMI with ESP32-S3
  repositories.txt
Labels: topic: submission

#6089 Update repositories.txt
  repositories.txt
Labels: topic: submission

#6090 Update repositories.txt
  repositories.txt
Labels: topic: submission

#6091 Add AutomationTimers Library
  repositories.txt
Labels: topic: submission

#6092 add https://github.com/qqqlab/ESP32-Serial-RMT-UART
  repositories.txt
Labels: topic: submission

#6094 https://github.com/manzarehassin/softRTC
  repositories.txt
Labels: topic: submission

#6097 add https://github.com/manzarehassin/tinyRTCds1307
  repositories.txt
Labels: topic: submission

#6099 Update repositories.txt
  repositories.txt
Labels: topic: submission

#6101 Update repositories.txt with ESP32ServoController
  repositories.txt
Labels: topic: submission

#6103 Update repositories.txt
  repositories.txt
Labels: topic: submission

#6102 requesting ESPExpress publishment
  repositories.txt
Labels: topic: submission

#6105 Update repositories.txt
  repositories.txt
Labels: topic: submission

#6109 Update repositories.txt
  repositories.txt
Labels: topic: submission

#6110 Update repositories.txt
  repositories.txt
Labels: topic: submission

#6111 add lib
  repositories.txt
Labels: topic: submission

#6114 Update repositories.txt
  repositories.txt
Labels: topic: submission

#6115 Update repositories.txt
  repositories.txt
Labels: topic: submission

#6116 Update repositories.txt
  repositories.txt
Labels: topic: submission

#6117 Update repositories.txt
  repositories.txt
Labels: topic: submission

#6118 Update repositories.txt
  repositories.txt
Labels: topic: submission

#6122 Adding Adafruit TLV320
  repositories.txt
Labels: topic: submission

#6126 Update repositories.txt
  repositories.txt
Labels: topic: submission

#6129 Update repositories.txt
  repositories.txt
Labels: topic: submission

#6104 Update repositories.txt
  repositories.txt
Labels: topic: submission

#6130 Added PrettyOTA library
  repositories.txt
Labels: topic: submission

#6131 Requesting the addition of a new library
  repositories.txt
Labels: topic: submission
