Repository arduino/library-registry, pull requests merged in 2025-08, with the labels that each got.

#6693 Add SparkFun_Authentication_Coprocessor_Arduino_Library
  repositories.txt
Labels: topic: submission

#6694 Hi
  repositories.txt
Labels: topic: submission

#6695 Add SparkFun_Apple_Accessory_Arduino_Library
  repositories.txt
Labels: topic: submission

#6696 Update repositories.txt
  repositories.txt
Labels: topic: submission

#6699 Update repositories.txt
  repositories.txt
Labels: topic: submission

#6698 Remove libraries from `tremaru` organization
  registry.txt
Labels: topic: removal, status: pending backend

#6700 Revoke registry privileges for github.com/tremaru
  .github/workflows/assets/accesslist.yml
Labels: topic: other

#6701 Update repositories.txt
  repositories.txt
Labels: topic: submission

#6702 Restore registry privileges for `github.com/7Semi` and `github.com/7semi-tech`
  .github/workflows/assets/accesslist.yml
Labels: topic: other

#6703 Update repositories.txt
  repositories.txt
Labels: topic: submission

#6705 Update repositories.txt
  repositories.txt
Labels: topic: submission

#6706 Update repositories.txt
  repositories.txt
Labels: topic: submission

#6707 Update repositories.txt
  repositories.txt
Labels: topic: submission

#6708 add lib
  repositories.txt
Labels: topic: submission

#6709 Update repositories.txt
  repositories.txt
Labels: topic: submission

#6713 Added cst816d (capacitive touchscreen) library
  repositories.txt
Labels: topic: submission

#6717 Update repositories.txt
  repositories.txt
Labels: topic: submission

#6719 Update repositories.txt
  repositories.txt
Labels: topic: submission

#6724 Update repositories.txt
  repositories.txt
Labels: topic: submission

#6725 Update repositories.txt
  repositories.txt
Labels: topic: submission

#6726 Update repositories.txt
  repositories.txt
Labels: topic: submission

#6727 Update repositories.txt
  repositories.txt
Labels: topic: submission

#6730 Update repositories.txt
  repositories.txt
Labels: topic: submission

#6731 Update repositories.txt
  repositories.txt
Labels: topic: submission

#6738 Update repositories.txt
  repositories.txt
Labels: topic: submission

#6739 Update repositories.txt
  repositories.txt
Labels: topic: submission

#6740 Add Tinker C6 Library
  repositories.txt
Labels: topic: submission

#6744 Update repositories.txt
  repositories.txt
Labels: topic: submission

#6745 Update repositories.txt
  repositories.txt
Labels: topic: submission

#6746 Add QuickAPConnect to Arduino Library Manager
  repositories.txt
Labels: topic: submission

#6748 Update repositories.txt
  repositories.txt
Labels: topic: submission

#6760 Add FujitsuAC library
  repositories.txt
Labels: topic: submission

#6761 adding Web Server library for Arduino Uno R4 WiFi
  repositories.txt
Labels: topic: submission

#6762 Add BLE OTA Firmware Update library
  repositories.txt
Labels: topic: submission

#6763 Update repositories.txt
  repositories.txt
Labels: topic: submission

#6766 Update repositories.txt
  repositories.txt
Labels: topic: submission

#6774 Update repositories.txt
  repositories.txt
Labels: topic: submission

#6776 Update repositories.txt
  repositories.txt
Labels: topic: submission

#6777 Update repositories.txt
  repositories.txt
Labels: topic: submission

#6778 Added Packet_Device Library V1.0.4
  repositories.txt
Labels: topic: submission

#6779 Update repositories.txt
  repositories.txt
Labels: topic: submission

#6781 Update repositories.txt
  repositories.txt
Labels: topic: submission

#6783 Update repositories.txt
  repositories.txt
Labels: topic: submission

#6785 Update repositories.txt : added Chaino library
  repositories.txt
Labels: topic: submission

#6793 Update repositories.txt
  repositories.txt
Labels: topic: submission

#6800 Update repositories.txt
  repositories.txt
Labels: topic: submission

#6802 Add SendOnlySerial library
  repositories.txt
Labels: topic: submission

#6804 Update repositories.txt
  repositories.txt
Labels: topic: submission

#6806 Update repositories.txt
  repositories.txt
Labels: topic: submission

#6758 Update name of "Twin_AIoT"
  registry.txt
Labels: topic: rename, status: pending backend

#6669 Update repositories.txt
  repositories.txt
Labels: topic: removal, status: pending backend

#6722 Update URL of "DFRobot_GDL"
  registry.txt
Labels: topic: URL change, status: pending backend

#6704 Update repositories.txt
  repositories.txt
Labels: topic: URL change, status: pending backend

#6812 Add Dimmer_ITC Lib
  repositories.txt
Labels: topic: submission

#6813 add some library
  repositories.txt
Labels: topic: submission

#6815 M5Unit-Miniscale
  repositories.txt
Labels: topic: submission

#6818 Add ANBSensorsModbus repository link
  repositories.txt
Labels: topic: submission

#6832 Update repositories.txt
  repositories.txt
Labels: topic: submission

#6835 Add 7Semi SCD4x Arduino Library
  repositories.txt
Labels: topic: submission

#6837 Update repositories.txt
  repositories.txt
Labels: topic: submission

#6841 Add AnalogControlPanel for ATmega328P
  repositories.txt
Labels: topic: submission

#6842 Add 7Semi L89HA GNSS Module Arduino Library
  repositories.txt
Labels: topic: submission

#6845 updated: add new repository link for skytraq-navic
  repositories.txt
Labels: topic: submission

#6851 Add RS_ThingSpeak to Arduino Library Manager
  repositories.txt
Labels: topic: submission

#6853 Add 7Semi ADXL335 Analog Accelerometer Module Arduino Library
  repositories.txt
Labels: topic: submission

#6856 Update repositories.txt
  repositories.txt
Labels: topic: submission

#6860 Add 7Semi INA260 Current/Power/Voltage Monitor Arduino Library
  repositories.txt
Labels: topic: submission

#6861 Add ToFFilter library
  repositories.txt
Labels: topic: submission

#6863 Add SL001_Deepanshu library
  repositories.txt
Labels: topic: submission

#6864 Add PlantMonitor repository link
  repositories.txt
Labels: topic: submission

#6865 Update repositories.txt
  repositories.txt
Labels: topic: submission

#6868 Add SL002_DHT11 library
  repositories.txt
Labels: topic: submission

#6872 Update repositories.txt
  repositories.txt
Labels: topic: submission

#6873 Update repositories.txt
  repositories.txt
Labels: topic: submission
