Repository arduino/library-registry, pull requests merged in 2025-07, with the labels that each got.

#6528 Add D6T sensor library
  repositories.txt
Labels: topic: submission

#6525 Update repositories.txt
  repositories.txt
Labels: topic: submission

#6530 Update repositories.txt
  repositories.txt
Labels: topic: submission

#6531 Add Library to repositories.txt
  repositories.txt
Labels: topic: submission

#6463 Remove "PrettyOTA"
  registry.txt
Labels: topic: removal, status: pending backend

#6459 Update repositories.txt
  repositories.txt
Labels: topic: removal, status: pending backend

#6506 Update URL of "phyphox BLE"
  registry.txt
Labels: topic: URL change, status: pending backend

#6504 Update phyphox-arduino repository to official organization repo
  repositories.txt
Labels: topic: URL change, status: pending backend

#6523 Update URL of "FVS"
  registry.txt
Labels: topic: URL change, status: pending backend

#6485 Update name of "Atmel_M90E32AS_ESP32"
  registry.txt
Labels: topic: rename, status: pending backend

#4978 Update name of "AvrFHT"
  registry.txt
Labels: topic: rename

#6540 Update repositories.txt
  repositories.txt
Labels: topic: submission

#6545 Update repositories.txt
  repositories.txt
Labels: topic: submission

#6548 add esp32easylib
  repositories.txt
Labels: topic: submission

#6549 Update repositories.txt
  repositories.txt
Labels: topic: submission

#6556 Update repositories.txt
  repositories.txt
Labels: topic: submission

#6557 add GlyEngine to Arduino IDE Registry
  repositories.txt
Labels: topic: submission

#6559 Update repositories.txt
  repositories.txt
Labels: topic: submission

#6561 Remove github.com/VasilKalchev/RGBLED from libraries list
  repositories.txt
Labels: topic: removal, type: imperfection

#6566 Update repositories.txt
  repositories.txt
Labels: topic: submission

#6568 Adding MyLibrary to Library Manager
  repositories.txt
Labels: topic: submission

#6570 Update repositories.txt
  repositories.txt
Labels: topic: submission

#6574 Update repositories.txt
  repositories.txt
Labels: topic: submission

#6577 Update repositories.txt
  repositories.txt
Labels: topic: submission

#6578 Update repositories.txt
  repositories.txt
Labels: topic: submission

#6579 SpresenseIMU
  repositories.txt
Labels: topic: submission

#6580 Update repositories.txt
  repositories.txt
Labels: topic: submission

#6581 Update repositories.txt
  repositories.txt
Labels: topic: submission

#6583 add lib
  repositories.txt
Labels: topic: submission

#6584 buzzer lib
  repositories.txt
Labels: topic: submission

#6587 Update repositories.txt
  repositories.txt
Labels: topic: submission

#6588 Update repositories.txt
  repositories.txt
Labels: topic: submission

#6594 add lib
  repositories.txt
Labels: topic: submission

#6597 Update repositories.txt
  repositories.txt
Labels: topic: submission

#6602 Update repositories.txt
  repositories.txt
Labels: topic: submission

#6605 Update repositories.txt
  repositories.txt
Labels: topic: submission

#6607 Add Simple Modbus Slave
  repositories.txt
Labels: topic: submission

#6611 Update repositories.txt
  repositories.txt
Labels: topic: submission

#6614 Update repositories.txt
  repositories.txt
Labels: topic: submission

#6564 Remove inappropriately registered "rgbled" library from registry
  registry.txt
Labels: topic: removal, status: pending backend

#6618 Update repositories.txt
  repositories.txt
Labels: topic: submission

#6619 Update repositories.txt
  repositories.txt
Labels: topic: submission

#6623 Update repositories.txt
  repositories.txt
Labels: topic: submission

#6624 add lib
  repositories.txt
Labels: topic: submission

#6625 Update repositories.txt
  repositories.txt
Labels: topic: submission

#6626 Added MicroSui library
  repositories.txt
Labels: topic: submission

#6627 Update repositories.txt
  repositories.txt
Labels: topic: submission

#6631 Update repositories.txt
  repositories.txt
Labels: topic: submission

#6632 Update repositories.txt
  repositories.txt
Labels: topic: submission

#6637 Update repositories.txt
  repositories.txt
Labels: topic: submission

#6639 LCD control via shift register
  repositories.txt
Labels: topic: submission

#6642 Add lib
  repositories.txt
Labels: topic: submission

#6640 Update repositories.txt
  repositories.txt
Labels: topic: submission

#6643 Update repositories.txt
  repositories.txt
Labels: topic: submission

#6645 Update repositories.txt
  repositories.txt
Labels: topic: submission

#6647 Update repositories.txt
  repositories.txt
Labels: topic: submission

#6648 Update repositories.txt
  repositories.txt
Labels: topic: submission

#6650 Added Consentium EdgeSense lib
  repositories.txt
Labels: topic: submission

#6653 Ajout d'une librairie
  repositories.txt
Labels: topic: submission

#6656 Microchip_RNWF02 Update repositories.txt
  repositories.txt
Labels: topic: submission

#6654 Update repositories.txt
  repositories.txt
Labels: topic: submission

#6661 add lib
  repositories.txt
Labels: topic: submission

#6657 Update repositories.txt
  repositories.txt
Labels: topic: submission

#6660 Update repositories.txt
  repositories.txt
Labels: topic: submission

#6668 Add new library
  repositories.txt
Labels: topic: submission

#6672 Add https://github.com/qqqlab/ESPnow-RC
  repositories.txt
Labels: topic: submission

#6674 Update repositories.txt
  repositories.txt
Labels: topic: submission

#6673 Update repositories.txt
  repositories.txt
Labels: topic: submission

#6681 Update repositories.txt
  repositories.txt
Labels: topic: submission

#6682 Revoke registry privileges for github.com/7semi-Tech
  .github/workflows/assets/accesslist.yml
Labels: topic: other

#6684 Update repositories.txt
  repositories.txt
Labels: topic: submission

#6685 Update repositories.txt
  repositories.txt
Labels: topic: submission

#6686 Update repositories.txt
  repositories.txt
Labels: topic: submission

#6687 Update repositories.txt
  repositories.txt
Labels: topic: submission

#6688 New Library
  repositories.txt
Labels: topic: submission

#6692 Update repositories.txt
  repositories.txt
Labels: topic: submission
