Repository arduino/library-registry, pull requests merged in 2025-09, with the labels that each got.

#6874 M5Module-PPS
  repositories.txt
Labels: topic: submission

#6875 Add Adafruit_PCM51xx repository link
  repositories.txt
Labels: topic: submission

#6877 Add 7Semi ACS772 Current Sensor Arduino Library
  repositories.txt
Labels: topic: submission

#6880 Add AVRactivePower
  repositories.txt
Labels: topic: submission

#6881 Add 7Semi SHT4x Arduino Library
  repositories.txt
Labels: topic: submission

#6884 Add 7Semi DS18B20 Arduino Library
  repositories.txt
Labels: topic: submission

#6892 Update repositories.txt
  repositories.txt
Labels: topic: submission

#6896 Request for Easy_Web_Control_Remote(ESP32)
  repositories.txt
Labels: topic: submission

#6906 Add AyresShell
  repositories.txt
Labels: topic: submission

#6909 Add library: Servomotor
  repositories.txt
Labels: topic: submission

#6910 Add AFMotor-Shield-R4-Compatible
  repositories.txt
Labels: topic: submission

#6912 add driver support st7305 mono TFT screen .
  repositories.txt
Labels: topic: submission

#6913 Add 7Semi ADS126x Arduino Library
  repositories.txt
Labels: topic: submission

#6915 Update repositories.txt
  repositories.txt
Labels: topic: submission

#6921 Add 7Semi ADS7830 Arduino Library
  repositories.txt
Labels: topic: submission

#6925 Update repositories.txt
  repositories.txt
Labels: topic: submission

#6928 add FrecuenciasMIDI and Perilla
  repositories.txt
Labels: topic: submission

#6931 Add new repository link for Boton
  repositories.txt
Labels: topic: submission

#6944 a
  repositories.txt
Labels: topic: submission

#6950 Update repositories.txt
  repositories.txt
Labels: topic: submission

#6952 Add 7Semi MCP23017 Arduino Library
  repositories.txt
Labels: topic: submission

#6953 Update repositories.txt
  repositories.txt
Labels: topic: submission

#6957 ATOM-PRINTER
  repositories.txt
Labels: topic: submission

#6963 Update repositories.txt
  repositories.txt
Labels: topic: submission

#6965 ANTIRTOS_MODERN
  repositories.txt
Labels: topic: submission

#6968 Trim trailing whitespace from repositories list
  repositories.txt
Labels: topic: modification

#6967 Add MyLibrary to library-registry
  repositories.txt
Labels: topic: submission

#6971 Added EdgeVision library
  repositories.txt
Labels: topic: submission

#6976 add esp-mqtt-arduino
  repositories.txt
Labels: topic: submission

#6980 Update repositories.txt
  repositories.txt
Labels: topic: submission

#6987 Update repositories.txt
  repositories.txt
Labels: topic: submission

#6986 Update repositories.txt
  repositories.txt
Labels: topic: submission

#6988 Update repositories.txt
  repositories.txt
Labels: topic: submission

#6994 Add ESP Discord Client library for ESP8266/ESP32 Discord integration
  repositories.txt
Labels: topic: submission

#6996 M5Module-4EncoderMotor
  repositories.txt
Labels: topic: submission

#6998 Add DietSerial
  repositories.txt
Labels: topic: submission

#6923 Update name and URL of "Quick_digital_IO_interrupt"
  registry.txt
Labels: topic: URL change, topic: rename, status: pending backend

#6924 Update name of "Timers_one_for_all"
  registry.txt
Labels: topic: rename, status: pending backend

#6807 Rename Modulino Library
  repositories.txt
Labels: topic: URL change, status: pending backend

#6893 Remove EasySTEAM library
  repositories.txt
Labels: topic: removal, status: pending backend

#4531 Update URL of "Voltmeter"
  registry.txt
Labels: topic: URL change, status: pending backend

#4528 Update URL of "AverageValue"
  registry.txt
Labels: topic: URL change, status: pending backend

#6999 Update repositories.txt
  repositories.txt
Labels: topic: submission

#7001 Update repositories.txt for Pedro Robot v1.0.4
  repositories.txt
Labels: topic: submission

#7002 Update repositories.txt
  repositories.txt
Labels: topic: submission

#7003 Update repositories.txt
  repositories.txt
Labels: topic: submission

#7006 Update repositories.txt
  repositories.txt
Labels: topic: submission
