Repository arduino/library-registry, pull requests merged in 2025-06, with the labels that each got.

#6369 Update repositories.txt
  repositories.txt
Labels: topic: submission

#6371 added bb_imu to the library list
  repositories.txt
Labels: topic: submission

#6372 Add johboh/ieee-802_15_4-network-host and johboh/ieee-802_15_4-network-node
  repositories.txt
Labels: topic: submission

#6373 Update repositories.txt
  repositories.txt
Labels: topic: submission

#6376 Update repositories.txt
  repositories.txt
Labels: topic: submission

#6375 Update repositories.txt
  repositories.txt
Labels: topic: submission

#6380 Update repositories.txt - ThingPlusBLEOSC
  repositories.txt
Labels: topic: submission

#6382 Update repositories.txt
  repositories.txt
Labels: topic: submission

#6383 add WiFiCaptive arduino library
  repositories.txt
Labels: topic: submission

#6384 Update repositories.txt
  repositories.txt
Labels: topic: submission

#6386 Update repositories.txt - Add MCAnemometer-Ultrasonic
  repositories.txt
Labels: topic: submission

#6385 Update repositories.txt
  repositories.txt
Labels: topic: submission

#6393 Adds SparkFun_AS7343_Arduino_Library
  repositories.txt
Labels: topic: submission

#6396 Update repositories.txt
  repositories.txt
Labels: topic: submission

#6401 Update repositories.txt
  repositories.txt
Labels: topic: submission

#6402 Update repositories.txt
  repositories.txt
Labels: topic: submission

#6406 Update repositories.txt
  repositories.txt
Labels: topic: submission

#6407 Update repositories.txt
  repositories.txt
Labels: topic: submission

#6408 Update repositories.txt
  repositories.txt
Labels: topic: submission

#6412 Update repository.txt
  repositories.txt
Labels: topic: submission

#6413 Add gnome-avr
  repositories.txt
Labels: topic: submission

#6419 Add TextFinder library
  repositories.txt
Labels: topic: submission

#6418 Update repositories.txt
  repositories.txt
Labels: topic: submission

#6321 Remove "TLE94112"
  registry.txt
Labels: topic: removal, status: pending backend

#6322 Remove "DigitalPressureSensor"
  registry.txt
Labels: topic: removal, status: pending backend

#6325 Remove "TLE5012B"
  registry.txt
Labels: topic: removal, status: pending backend

#6326 Remove "TLI493D"
  registry.txt
Labels: topic: removal, status: pending backend

#6327 Remove "TLV493D-A1B6"
  registry.txt
Labels: topic: removal, status: pending backend

#6364 Update repositories.txt
  repositories.txt
Labels: topic: submission

#6421 Resolve merge conflict - add EgLang library
  repositories.txt
Labels: topic: submission

#6430 Update repositories.txt
  repositories.txt
Labels: topic: submission

#6436 Update repositories.txt
  repositories.txt
Labels: topic: submission

#6439 Update repositories.txt
  repositories.txt
Labels: topic: submission

#6440 Add ChaCha32Arduino library
  repositories.txt
Labels: topic: submission

#6441 Update repositories.txt
  repositories.txt
Labels: topic: submission

#6444 Add PY32LowPower library to repositories.txt
  repositories.txt
Labels: topic: submission

#6445 esp-arduino-tunnel
  repositories.txt
Labels: topic: submission

#6447 update repositories.txt
  repositories.txt
Labels: topic: submission

#6448 Update repositories.txt
  repositories.txt
Labels: topic: submission

#6451 Update repositories.txt
  repositories.txt
Labels: topic: submission

#6457 Update repositories.txt
  repositories.txt
Labels: topic: submission

#6461 Merge branch 'arduino:main' into main
  repositories.txt
Labels: topic: submission

#6462 Update repositories.txt
  repositories.txt
Labels: topic: submission

#6469 Update repositories.txt
  repositories.txt
Labels: topic: submission

#6470 Update repositories.txt : Added SimpleOLED library
  repositories.txt
Labels: topic: submission

#6473 initMemory
  repositories.txt
Labels: topic: submission

#6474 Update repositories.txt
  repositories.txt
Labels: topic: submission

#6475 Add SchneiderModbusTCP library by mmercalde
  repositories.txt
Labels: topic: submission

#6476 Update repositories.txt
  repositories.txt
Labels: topic: submission

#6478 Fix my alphebetization mistake
  repositories.txt
Labels: type: enhancement, topic: modification

#6480 Update repositories.txt
  repositories.txt
Labels: topic: submission

#6481 Update repositories.txt
  repositories.txt
Labels: topic: submission

#6484 Update repositories.txt
  repositories.txt
Labels: topic: submission

#6486 add lib
  repositories.txt
Labels: topic: submission

#6489 add lib
  repositories.txt
Labels: topic: submission

#6493 Add lowkeyoled to Library Manager
  repositories.txt
Labels: topic: submission

#6494 Update repositories.txt
  repositories.txt
Labels: topic: submission

#6495 Add ArtronShop_BL0940 lib
  repositories.txt
Labels: topic: submission

#6503 Update repositories.txt
  repositories.txt
Labels: topic: submission

#6505 Update repositories.txt
  repositories.txt
Labels: topic: submission

#6507 MCM ATM90E32 Energy Meter Library add
  repositories.txt
Labels: topic: submission

#6508 Adding BleValueSync library
  repositories.txt
Labels: topic: submission

#6512 Update repositories.txt
  repositories.txt
Labels: topic: submission

#6515 Revoke registry privileges for github.com/galihru
  .github/workflows/assets/accesslist.yml
Labels: topic: code, type: imperfection

#6516 Update reference URL for github.com/galihru privilege revocation
  .github/workflows/assets/accesslist.yml
Labels: topic: other

#6518 Update repositories.txt
  repositories.txt
Labels: topic: submission
