Repository arduino/library-registry, pull requests merged in 2025-05, with the labels that each got.

#6254 Update repositories.txt
  repositories.txt
Labels: topic: submission

#6255 Add ACS37800 library.
  repositories.txt
Labels: topic: submission

#6256 Update repositories.txt
  repositories.txt
Labels: topic: submission

#6257 Update repositories.txt
  repositories.txt
Labels: topic: submission

#6260 Add https://github.com/Johboh/GCMEncryption
  repositories.txt
Labels: topic: submission

#6261 Update repositories.txt
  repositories.txt
Labels: topic: submission

#6262 Add https://github.com/Johboh/ieee-802_15_4/
  repositories.txt
Labels: topic: submission

#6265 Update repositories.txt
  repositories.txt
Labels: topic: submission

#6266 Add github.com/IvoryRubble/ArduinoSegaGamepadLibrary
  repositories.txt
Labels: topic: submission

#6267 Update repositories.txt
  repositories.txt
Labels: topic: submission

#6268 Update repositories.txt
  repositories.txt
Labels: topic: submission

#6270 Revoke registry privileges for github.com/4211421036
  .github/workflows/assets/accesslist.yml
Labels: type: enhancement, topic: code, topic: other

#6272 Update repositories.txt
  repositories.txt
Labels: topic: submission

#6274 Update repositories.txt
  repositories.txt
Labels: topic: submission

#6275 Update repositories.txt
  repositories.txt
Labels: topic: submission

#6277 Update repositories.txt
  repositories.txt
Labels: topic: submission

#6279 Update repositories.txt
  repositories.txt
Labels: topic: submission

#6280 Update repositories.txt
  repositories.txt
Labels: topic: submission

#6284 Add FSR16x16_BNL library
  repositories.txt
Labels: topic: submission

#6283 Update repositories.txt with RockBLOCK-9704
  repositories.txt
Labels: topic: submission

#6285 Update repositories.txt
  repositories.txt
Labels: topic: submission

#6286 Update repositories.txt
  repositories.txt
Labels: topic: submission

#6287 Update repositories.txt
  repositories.txt
Labels: topic: submission

#6288 add p2os-arduino link to repositories.txt
  repositories.txt
Labels: topic: submission

#6289 Update repositories.txt (add mecmotor lib)
  repositories.txt
Labels: topic: submission

#6290 Update repositories.txt
  repositories.txt
Labels: topic: submission

#6292 Update repositories.txt
  repositories.txt
Labels: topic: submission

#6293 Update repositories.txt
  repositories.txt
Labels: topic: submission

#6259 Update name of "MDevice"
  registry.txt
Labels: topic: rename, status: pending backend

#6222 Remove "Device"
  registry.txt
Labels: topic: removal, status: pending backend

#6193 Update repositories.txt
  repositories.txt
Labels: topic: removal, status: pending backend

#6246 Update URL of "LightTaskScheduler"
  registry.txt
Labels: topic: URL change, status: pending backend

#6295 Add DIYables TFT Shield library to repositories.txt
  repositories.txt
Labels: topic: submission

#6296 Update repositories.txt
  repositories.txt
Labels: topic: submission

#6297 Update repositories.txt
  repositories.txt
Labels: topic: submission

#6299 Add Thingsly IoT Platform Library
  repositories.txt
Labels: topic: submission

#6303 Add MPU6050Aries library
  repositories.txt
Labels: topic: submission

#6304 Update repositories.txt
  repositories.txt
Labels: topic: submission

#6306 Add MicroSclip
  repositories.txt
Labels: topic: submission

#6308 Update repositories.txt
  repositories.txt
Labels: topic: submission

#6309 Update repositories.txt
  repositories.txt
Labels: topic: submission

#6312 Add PWM2motor_BNL library
  repositories.txt
Labels: topic: submission

#6314 register ArduinoPostgresOverHTTP library to Arduino library manager
  repositories.txt
Labels: topic: submission

#6315 Update repositories.txt
  repositories.txt
Labels: topic: submission

#6316 Add PersistentJsonEEPROM library
  repositories.txt
Labels: topic: submission

#6317 Add PicoLlama LLM library
  repositories.txt
Labels: topic: submission

#6334 Update repositories.txt
  repositories.txt
Labels: topic: submission

#6332 A lightweight library based on JSON and Network Sockets for Arduino communication and control based configured by a Manifesto.
  repositories.txt
Labels: topic: submission

#6336 Update repositories.txt
  repositories.txt
Labels: topic: submission

#6337 Add PT7C4339-RTC
  repositories.txt
Labels: topic: submission

#6340 Add RCduino library to Library Manager index
  repositories.txt
Labels: topic: submission

#6343 Added MjolnFS File System for AT24CX EEPROM
  repositories.txt
Labels: topic: submission

#6347 Update repositories.txt
  repositories.txt
Labels: topic: submission

#6349 chore: add Ewan-Dev/mpu6050 library to repositories.txt
  repositories.txt
Labels: topic: submission

#6355 Update repositories.txt
  repositories.txt
Labels: topic: submission

#6357 Add QMI8658 Arduino Library
  repositories.txt
Labels: topic: submission

#6358 Update repositories.txt
  repositories.txt
Labels: topic: submission

#6359 Add "QuickUltrasonic" library
  repositories.txt
Labels: topic: submission

#6361 CypressCY8CMBR3116
  repositories.txt
Labels: topic: submission

#6365 M5Unit-INFRARED
  repositories.txt
Labels: topic: submission

#6366 M5Unit-CRYPTO
  repositories.txt
Labels: topic: submission

#6368 Add Lexo library for Arduino Library Manager
  repositories.txt
Labels: topic: submission
